// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-chi/chi/v5"
	"github.com/go-playground/validator/v10"
)

// OapiErrorKind represents the type of error that occurred during request processing.
type OapiErrorKind int

const (
	// OapiErrorKindParse indicates a parameter parsing error (invalid path/query/header parameter).
	OapiErrorKindParse OapiErrorKind = iota

	// OapiErrorKindDecode indicates a request body decoding error (invalid JSON, form data, etc.).
	OapiErrorKindDecode

	// OapiErrorKindValidation indicates a request validation error (failed schema validation).
	OapiErrorKindValidation

	// OapiErrorKindService indicates a service/business logic error returned by the service implementation.
	OapiErrorKindService
)

// OapiHandlerError represents an error that occurred during request handling (parse, decode, validation).
// When no typed error response is configured in the OpenAPI spec, this error type is used.
// Custom error handlers can type-assert to this type to access error details.
type OapiHandlerError struct {
	Kind          OapiErrorKind
	OperationID   string
	Message       string
	ParamName     string
	ParamLocation string

	// Err is the error that caused this handler error.
	Err error `json:"-"`
}

func (e OapiHandlerError) Error() string {
	return e.Message
}

// Unwrap returns the underlying error, enabling errors.Is and errors.As.
func (e OapiHandlerError) Unwrap() error {
	return e.Err
}

// OapiErrorResponse is the default JSON error response structure used by OapiDefaultErrorHandler.
type OapiErrorResponse struct {
	Error         string `json:"error"`
	OperationID   string `json:"operation_id,omitempty"`
	ParamName     string `json:"param_name,omitempty"`
	ParamLocation string `json:"param_location,omitempty"`
}

// OapiErrorHandler handles errors that occur during request processing.
// Implement this interface to customize error responses, logging, and metrics.
type OapiErrorHandler interface {
	// HandleError writes an error response to w with the given status code.
	// The err is either an OapiHandlerError (for parse/decode/validation errors)
	// or a typed error matching the OpenAPI spec's error response schema.
	HandleError(w http.ResponseWriter, r *http.Request, statusCode int, err error)
}

// OapiDefaultErrorHandler provides the default error handling behavior.
// It writes JSON error responses. For OapiHandlerError, it uses OapiErrorResponse.
// For typed errors (from OpenAPI spec), it encodes them directly.
type OapiDefaultErrorHandler struct{}

// HandleError implements OapiErrorHandler with default JSON error responses.
func (h *OapiDefaultErrorHandler) HandleError(w http.ResponseWriter, r *http.Request, statusCode int, err error) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(statusCode)

	if handlerErr, ok := err.(OapiHandlerError); ok {
		_ = json.NewEncoder(w).Encode(OapiErrorResponse{
			Error:         handlerErr.Message,
			OperationID:   handlerErr.OperationID,
			ParamName:     handlerErr.ParamName,
			ParamLocation: handlerErr.ParamLocation,
		})
		return
	}

	// Typed error from OpenAPI spec - encode directly
	_ = json.NewEncoder(w).Encode(err)
}

// ServiceInterface defines the service interface for business logic.
type ServiceInterface interface {
	Search(ctx context.Context, opts *SearchServiceRequestOptions) (*SearchResponseData, error)
}

// HTTPAdapter adapts the ServiceInterface to HTTP handlers.
// This struct is generated and should not be modified.
type HTTPAdapter struct {
	svc             ServiceInterface
	errHandler      OapiErrorHandler
	jsonBodyDecoder runtime.JSONBodyDecoderFunc
}

// NewHTTPAdapter creates a new HTTPAdapter wrapping the given service.
// If errHandler is nil, OapiDefaultErrorHandler is used.
func NewHTTPAdapter(svc ServiceInterface, errHandler OapiErrorHandler) *HTTPAdapter {
	if errHandler == nil {
		errHandler = &OapiDefaultErrorHandler{}
	}
	return &HTTPAdapter{svc: svc, errHandler: errHandler, jsonBodyDecoder: runtime.DecodeJSONBody}
}

// Search handles GET /search
func (a *HTTPAdapter) Search(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &SearchServiceRequestOptions{}
	opts.RawRequest = r

	// Parse query parameters
	queryParams := &SearchQuery{}
	query := r.URL.Query()

	if values, ok := query["term"]; ok {
		queryParams.Term = values
	}

	if values, ok := query["tag"]; ok {
		queryParams.Tag = values
	}

	if values, ok := query["id"]; ok {
		parsed, err := runtime.ParseStringSlice[int](values)
		if err != nil {
			a.errHandler.HandleError(w, r, http.StatusBadRequest, OapiHandlerError{
				Kind:          OapiErrorKindParse,
				OperationID:   "Search",
				Message:       err.Error(),
				ParamName:     "id",
				ParamLocation: "query",
				Err:           err,
			})
			return
		}
		queryParams.ID = parsed
	}
	opts.Query = queryParams
	// Validate request
	if err := opts.Validate(); err != nil {
		a.errHandler.HandleError(w, r, http.StatusBadRequest, OapiHandlerError{
			Kind:        OapiErrorKindValidation,
			OperationID: "Search",
			Message:     err.Error(),
			Err:         err,
		})
		return
	}

	// Call business logic
	resp, err := a.svc.Search(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		if resp != nil && resp.Status != 0 {
			code = resp.Status
		}
		a.errHandler.HandleError(w, r, code, err)
		return
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 204
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.WriteHeader(status)
}

// RouterOption is a function that configures the router.
type RouterOption func(*routerConfig)

type routerConfig struct {
	middlewares     []func(http.Handler) http.Handler
	errHandler      OapiErrorHandler
	jsonBodyDecoder runtime.JSONBodyDecoderFunc
}

// WithMiddleware adds middleware to the router.
func WithMiddleware(mw func(http.Handler) http.Handler) RouterOption {
	return func(cfg *routerConfig) {
		cfg.middlewares = append(cfg.middlewares, mw)
	}
}

// WithErrorHandler sets a custom error handler for the router.
// If not set, OapiOapiDefaultErrorHandler is used.
func WithErrorHandler(h OapiErrorHandler) RouterOption {
	return func(cfg *routerConfig) {
		cfg.errHandler = h
	}
}

// WithJSONBodyDecoder sets a custom function for decoding JSON request bodies.
// If not set, runtime.DecodeJSONBody is used.
func WithJSONBodyDecoder(fn runtime.JSONBodyDecoderFunc) RouterOption {
	return func(cfg *routerConfig) {
		cfg.jsonBodyDecoder = fn
	}
}

// NewRouter creates a new chi.Router with the given service implementation.
func NewRouter(svc ServiceInterface, opts ...RouterOption) chi.Router {
	cfg := &routerConfig{}
	for _, opt := range opts {
		opt(cfg)
	}

	r := chi.NewRouter()
	for _, mw := range cfg.middlewares {
		r.Use(mw)
	}

	adapter := NewHTTPAdapter(svc, cfg.errHandler)
	if cfg.jsonBodyDecoder != nil {
		adapter.jsonBodyDecoder = cfg.jsonBodyDecoder
	}
	r.Method("GET", "/search", http.HandlerFunc(adapter.Search))

	return r
}

type Terms = []string

type TagList []string

func (t TagList) Validate() error {
	if t == nil {
		return nil
	}
	if len(t) > 2 {
		return runtime.NewValidationError("Array", fmt.Sprintf("must have at most 2 items, got %d", len(t)))
	}
	return nil
}

type SearchQuery struct {
	Term Terms   `json:"term,omitempty"`
	Tag  TagList `json:"tag,omitempty"`
	ID   IDList  `json:"id,omitempty"`
}

func (s SearchQuery) Validate() error {
	var errors runtime.ValidationErrors
	for i, item := range s.Term {
		if err := typesValidator.Var(item, "omitempty,max=3"); err != nil {
			errors = errors.Append(fmt.Sprintf("Term[%d]", i), err)
		}
	}
	if v, ok := any(s.Tag).(runtime.Validator); ok && v != nil {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Tag", err)
		}
	}
	if v, ok := any(s.ID).(runtime.Validator); ok && v != nil {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

// SearchResponseData wraps the success response with optional headers and status override.
type SearchResponseData struct {
	Body    *struct{}
	Headers http.Header
	Status  int // 0 = use default (204)
}

// NewSearchResponseData creates a new SearchResponseData with the given body.
func NewSearchResponseData(body *struct{}) *SearchResponseData {
	return &SearchResponseData{Body: body}
}

// WithHeaders sets custom headers on the response.
func (r *SearchResponseData) WithHeaders(h http.Header) *SearchResponseData {
	r.Headers = h
	return r
}

// WithStatus overrides the default status code.
func (r *SearchResponseData) WithStatus(code int) *SearchResponseData {
	r.Status = code
	return r
}

// Payload returns the value to be JSON-encoded as the response body. Override
// this template to customize the encoded shape (e.g. to wrap it in an envelope)
// without needing to change the adapter template.
func (r *SearchResponseData) Payload() any {
	if r.Body == nil {
		return nil
	}
	return r.Body
}

// SearchServiceRequestOptions holds all parameters for the Search operation.
type SearchServiceRequestOptions struct {
	Query *SearchQuery
	// RawRequest provides access to the underlying HTTP request for custom content type handling.
	RawRequest *http.Request
}

// Validate validates all the fields in the options.
func (o *SearchServiceRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.Query != nil {
		if v, ok := any(o.Query).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Query", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

type IDList []int

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
