// Code generated by oapi-codegen. DO NOT EDIT.

package circularproperties

import (
	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type PostUsersResponse struct {
	City *Address `json:"city,omitempty"`
}

var schemaTypesValidate *validator.Validate

func init() {
	schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(schemaTypesValidate)
}

// User info.
type User struct{}

func (u User) Validate() error {
	return nil
}

type Address struct {
	City *Address `json:"city,omitempty"`
}

func (a Address) Validate() error {
	if a.City != nil {
		if v, ok := any(a.City).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("City", err)
			}
		}
	}
	return nil
}
