openapi: 3.0.0
info:
  title: API
  description: An example of `oneOf` in responses
  version: 1.0.0

paths:
  /service/gateway:
    post:
      summary: Process payment operations
      operationId: processPayment
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
      responses:
        '500':
          content:
            text/plain:
              schema:
                enum:
                  - Internal Server Error
                type: string
          description: Internal Server Error
