// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type ListResourcesResponse = SpecialResource

type BaseResource struct {
	ID   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

type SpecialResource struct {
	BaseResource           BaseResource            `json:"-"`
	SpecialResource_AllOf1 *SpecialResource_AllOf1 `json:"-"`
}

func (s SpecialResource) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(s.BaseResource).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("BaseResource", err)
		}
	}
	if s.SpecialResource_AllOf1 != nil {
		if v, ok := any(s.SpecialResource_AllOf1).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("SpecialResource_AllOf1", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (s SpecialResource) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(s.BaseResource)
		if err != nil {
			return nil, fmt.Errorf("BaseResource marshal: %w", err)
		}
		parts = append(parts, b)
	}

	{
		b, err := runtime.MarshalJSON(s.SpecialResource_AllOf1)
		if err != nil {
			return nil, fmt.Errorf("SpecialResource_AllOf1 marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (s *SpecialResource) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if err := runtime.UnmarshalJSON(data, &s.BaseResource); err != nil {
		return fmt.Errorf("BaseResource unmarshal: %w", err)
	}

	if s.SpecialResource_AllOf1 == nil {
		s.SpecialResource_AllOf1 = &SpecialResource_AllOf1{}
	}

	if err := runtime.UnmarshalJSON(data, s.SpecialResource_AllOf1); err != nil {
		return fmt.Errorf("SpecialResource_AllOf1 unmarshal: %w", err)
	}

	return nil
}

type SpecialResource_AllOf1 struct {
	Category                          *string                            `json:"category,omitempty"`
	SpecialResource_AllOf1_IfThenElse *SpecialResource_AllOf1_IfThenElse `json:"-"`
}

func (s SpecialResource_AllOf1) Validate() error {
	var errors runtime.ValidationErrors
	if s.SpecialResource_AllOf1_IfThenElse != nil {
		if v, ok := any(s.SpecialResource_AllOf1_IfThenElse).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("SpecialResource_AllOf1_IfThenElse", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (s SpecialResource_AllOf1) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	type _Alias_SpecialResource_AllOf1 SpecialResource_AllOf1
	baseJSON, err := json.Marshal((_Alias_SpecialResource_AllOf1)(s))
	if err != nil {
		return nil, err
	}
	parts = append(parts, baseJSON)

	{
		b, err := runtime.MarshalJSON(s.SpecialResource_AllOf1_IfThenElse)
		if err != nil {
			return nil, fmt.Errorf("SpecialResource_AllOf1_IfThenElse marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (s *SpecialResource_AllOf1) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if len(trim) > 0 {
		type _Alias_SpecialResource_AllOf1 SpecialResource_AllOf1
		var tmp _Alias_SpecialResource_AllOf1
		if err := json.Unmarshal(data, &tmp); err != nil {
			return err
		}
		*s = SpecialResource_AllOf1(tmp)
	}

	if s.SpecialResource_AllOf1_IfThenElse == nil {
		s.SpecialResource_AllOf1_IfThenElse = &SpecialResource_AllOf1_IfThenElse{}
	}

	if err := runtime.UnmarshalJSON(data, s.SpecialResource_AllOf1_IfThenElse); err != nil {
		return fmt.Errorf("SpecialResource_AllOf1_IfThenElse unmarshal: %w", err)
	}

	return nil
}

type SpecialResource_AllOf1_Then struct {
	PremiumFeature *string `json:"premiumFeature,omitempty"`
}

type SpecialResource_AllOf1_Else struct {
	StandardLimit *int `json:"standardLimit,omitempty"`
}

type SpecialResource_AllOf1_IfThenElse struct {
	runtime.Conditional[SpecialResource_AllOf1_Then, SpecialResource_AllOf1_Else]
}

func (s *SpecialResource_AllOf1_IfThenElse) Validate() error {
	if s.IsThen() {
		if v, ok := any(s.Then).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if s.IsElse() {
		if v, ok := any(s.Else).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
