// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"github.com/go-playground/validator/v10"
)

var pathTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type GetNodesIDPath struct {
	// ID The ID of the node
	ID int `json:"id" validate:"required"`
}

func (g GetNodesIDPath) Validate() error {
	return pathTypesValidate.Struct(g)
}

type GetNodesIDResponse struct {
	ID       *int    `json:"id,omitempty"`
	Name     *string `json:"name,omitempty"`
	Children []Node  `json:"children,omitempty"`
}

var schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type Node struct {
	ID       *int    `json:"id,omitempty"`
	Name     *string `json:"name,omitempty"`
	Children []Node  `json:"children,omitempty"`
}

func (n Node) Validate() error {
	return schemaTypesValidate.Struct(n)
}
