// Code generated by oapi-codegen. DO NOT EDIT.
package api

import (
	"context"
)

// HandlerInterface defines the interface for handling API requests.
type HandlerInterface interface {
	// HealthCheck Health check endpoint
	HealthCheck(ctx context.Context) (*HealthCheckResponseData, error)
	// ListUsers List all users
	ListUsers(ctx context.Context, opts *ListUsersRequestOptions) (*ListUsersResponseData, error)
	// CreateUser Create a new user via JSON
	CreateUser(ctx context.Context, opts *CreateUserRequestOptions) (*CreateUserResponseData, error)
	// ImportUsers Import users from CSV file
	ImportUsers(ctx context.Context, opts *ImportUsersRequestOptions) (*ImportUsersResponseData, error)
	// GetUser Get a user by ID
	GetUser(ctx context.Context, opts *GetUserRequestOptions) (*GetUserResponseData, error)
	// DeleteUser Delete a user
	DeleteUser(ctx context.Context, opts *DeleteUserRequestOptions) (*DeleteUserResponseData, error)
	// GetUserAvatar Get user avatar image
	GetUserAvatar(ctx context.Context, opts *GetUserAvatarRequestOptions) (*GetUserAvatarResponseData, error)
	// UploadUserAvatar Upload user avatar
	UploadUserAvatar(ctx context.Context, opts *UploadUserAvatarRequestOptions) (*UploadUserAvatarResponseData, error)
	// SubmitContactForm Submit contact form
	SubmitContactForm(ctx context.Context, opts *SubmitContactFormRequestOptions) (*SubmitContactFormResponseData, error)
	// CreateNote Create a note from plain text
	CreateNote(ctx context.Context, opts *CreateNoteRequestOptions) (*CreateNoteResponseData, error)
	// ProcessXMLData Process XML data (demonstrates custom content type handling)
	ProcessXMLData(ctx context.Context, opts *ProcessXMLDataRequestOptions) (*ProcessXMLDataResponseData, error)
	// ExportData Export all data as binary archive
	ExportData(ctx context.Context) (*ExportDataResponseData, error)
	// GetOAuthToken Get OAuth token (form-encoded response)
	GetOAuthToken(ctx context.Context, opts *GetOAuthTokenRequestOptions) (*GetOAuthTokenResponseData, error)
	// GetItemsByType Get items by type (tests reserved Go keyword as path param)
	GetItemsByType(ctx context.Context, opts *GetItemsByTypeRequestOptions) (*GetItemsByTypeResponseData, error)
	// Search Search with union type response (oneOf)
	Search(ctx context.Context, opts *SearchRequestOptions) (*SearchResponseData, error)
	// GetStatus Get status (uses reusable response)
	GetStatus(ctx context.Context) (*GetStatusResponseData, error)
	// UploadImage Upload image (wildcard content type)
	UploadImage(ctx context.Context, opts *UploadImageRequestOptions) (*UploadImageResponseData, error)
	// ListProducts List products with various query param types
	ListProducts(ctx context.Context, opts *ListProductsRequestOptions) (*ListProductsResponseData, error)
	// GetCategory Get a category by ID (integer path param)
	GetCategory(ctx context.Context, opts *GetCategoryRequestOptions) (*GetCategoryResponseData, error)
	// GetItemsByStatus Get items by active status and rating (boolean + number path params)
	GetItemsByStatus(ctx context.Context, opts *GetItemsByStatusRequestOptions) (*GetItemsByStatusResponseData, error)
	// GetUserPost Get a specific post by a user
	GetUserPost(ctx context.Context, opts *GetUserPostRequestOptions) (*GetUserPostResponseData, error)
	// CreateOrder Create an order (demonstrates typed error responses)
	CreateOrder(ctx context.Context, opts *CreateOrderRequestOptions) (*CreateOrderResponseData, error)
	// CreateCompany Create a company with nested address
	CreateCompany(ctx context.Context, opts *CreateCompanyRequestOptions) (*CreateCompanyResponseData, error)
}
