// Code generated by oapi-codegen. DO NOT EDIT.

package api

import (
	"net/http"

	"github.com/doordash-oss/oapi-codegen-dd/v3/examples/server/chi/other-pkg-mult-files/types"
	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

// ListUsersHandlerRequestOptions holds all parameters for the ListUsers operation.
type ListUsersHandlerRequestOptions struct {
	Query  *types.ListUsersQuery
	Header *types.ListUsersHeaders
	// RawRequest provides access to the underlying HTTP request for custom content type handling.
	RawRequest *http.Request
}

// Validate validates all the fields in the options.
func (o *ListUsersHandlerRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.Query != nil {
		if v, ok := any(o.Query).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Query", err)
			}
		}
	}

	if o.Header != nil {
		if v, ok := any(o.Header).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Header", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// CreateUserHandlerRequestOptions holds all parameters for the CreateUser operation.
type CreateUserHandlerRequestOptions struct {
	Body *types.CreateUserBody
	// RawRequest provides access to the underlying HTTP request for custom content type handling.
	RawRequest *http.Request
}

// Validate validates all the fields in the options.
func (o *CreateUserHandlerRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.Body != nil {
		if v, ok := any(o.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Body", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// ImportUsersHandlerRequestOptions holds all parameters for the ImportUsers operation.
type ImportUsersHandlerRequestOptions struct {
	Body *types.ImportUsersBody
	// RawRequest provides access to the underlying HTTP request for custom content type handling.
	RawRequest *http.Request
}

// Validate validates all the fields in the options.
func (o *ImportUsersHandlerRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.Body != nil {
		if v, ok := any(o.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Body", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetUserHandlerRequestOptions holds all parameters for the GetUser operation.
type GetUserHandlerRequestOptions struct {
	PathParams *types.GetUserPath
	// RawRequest provides access to the underlying HTTP request for custom content type handling.
	RawRequest *http.Request
}

// Validate validates all the fields in the options.
func (o *GetUserHandlerRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// DeleteUserHandlerRequestOptions holds all parameters for the DeleteUser operation.
type DeleteUserHandlerRequestOptions struct {
	PathParams *types.DeleteUserPath
	// RawRequest provides access to the underlying HTTP request for custom content type handling.
	RawRequest *http.Request
}

// Validate validates all the fields in the options.
func (o *DeleteUserHandlerRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetUserAvatarHandlerRequestOptions holds all parameters for the GetUserAvatar operation.
type GetUserAvatarHandlerRequestOptions struct {
	PathParams *types.GetUserAvatarPath
	// RawRequest provides access to the underlying HTTP request for custom content type handling.
	RawRequest *http.Request
}

// Validate validates all the fields in the options.
func (o *GetUserAvatarHandlerRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// UploadUserAvatarHandlerRequestOptions holds all parameters for the UploadUserAvatar operation.
type UploadUserAvatarHandlerRequestOptions struct {
	PathParams *types.UploadUserAvatarPath
	// RawRequest provides access to the underlying HTTP request for custom content type handling.
	RawRequest *http.Request
}

// Validate validates all the fields in the options.
func (o *UploadUserAvatarHandlerRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// SubmitContactFormHandlerRequestOptions holds all parameters for the SubmitContactForm operation.
type SubmitContactFormHandlerRequestOptions struct {
	Body *types.SubmitContactFormBody
	// RawRequest provides access to the underlying HTTP request for custom content type handling.
	RawRequest *http.Request
}

// Validate validates all the fields in the options.
func (o *SubmitContactFormHandlerRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.Body != nil {
		if v, ok := any(o.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Body", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// CreateNoteHandlerRequestOptions holds all parameters for the CreateNote operation.
type CreateNoteHandlerRequestOptions struct {
	Body *types.CreateNoteBody
	// RawRequest provides access to the underlying HTTP request for custom content type handling.
	RawRequest *http.Request
}

// Validate validates all the fields in the options.
func (o *CreateNoteHandlerRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.Body != nil {
		if v, ok := any(o.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Body", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// ProcessXMLDataHandlerRequestOptions holds all parameters for the ProcessXMLData operation.
type ProcessXMLDataHandlerRequestOptions struct {
	// RawRequest provides access to the underlying HTTP request for custom content type handling.
	RawRequest *http.Request
}

// Validate validates all the fields in the options.
func (o *ProcessXMLDataHandlerRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetOAuthTokenHandlerRequestOptions holds all parameters for the GetOAuthToken operation.
type GetOAuthTokenHandlerRequestOptions struct {
	Body *types.GetOAuthTokenBody
	// RawRequest provides access to the underlying HTTP request for custom content type handling.
	RawRequest *http.Request
}

// Validate validates all the fields in the options.
func (o *GetOAuthTokenHandlerRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.Body != nil {
		if v, ok := any(o.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Body", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetItemsByTypeHandlerRequestOptions holds all parameters for the GetItemsByType operation.
type GetItemsByTypeHandlerRequestOptions struct {
	PathParams *types.GetItemsByTypePath
	// RawRequest provides access to the underlying HTTP request for custom content type handling.
	RawRequest *http.Request
}

// Validate validates all the fields in the options.
func (o *GetItemsByTypeHandlerRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// SearchHandlerRequestOptions holds all parameters for the Search operation.
type SearchHandlerRequestOptions struct {
	Query *types.SearchQuery
	// RawRequest provides access to the underlying HTTP request for custom content type handling.
	RawRequest *http.Request
}

// Validate validates all the fields in the options.
func (o *SearchHandlerRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.Query != nil {
		if v, ok := any(o.Query).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Query", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// UploadImageHandlerRequestOptions holds all parameters for the UploadImage operation.
type UploadImageHandlerRequestOptions struct {
	// RawRequest provides access to the underlying HTTP request for custom content type handling.
	RawRequest *http.Request
}

// Validate validates all the fields in the options.
func (o *UploadImageHandlerRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if len(errors) == 0 {
		return nil
	}

	return errors
}

// ListProductsHandlerRequestOptions holds all parameters for the ListProducts operation.
type ListProductsHandlerRequestOptions struct {
	Query *types.ListProductsQuery
	// RawRequest provides access to the underlying HTTP request for custom content type handling.
	RawRequest *http.Request
}

// Validate validates all the fields in the options.
func (o *ListProductsHandlerRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.Query != nil {
		if v, ok := any(o.Query).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Query", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetCategoryHandlerRequestOptions holds all parameters for the GetCategory operation.
type GetCategoryHandlerRequestOptions struct {
	PathParams *types.GetCategoryPath
	Header     *types.GetCategoryHeaders
	// RawRequest provides access to the underlying HTTP request for custom content type handling.
	RawRequest *http.Request
}

// Validate validates all the fields in the options.
func (o *GetCategoryHandlerRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}

	if o.Header != nil {
		if v, ok := any(o.Header).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Header", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetItemsByStatusHandlerRequestOptions holds all parameters for the GetItemsByStatus operation.
type GetItemsByStatusHandlerRequestOptions struct {
	PathParams *types.GetItemsByStatusPath
	// RawRequest provides access to the underlying HTTP request for custom content type handling.
	RawRequest *http.Request
}

// Validate validates all the fields in the options.
func (o *GetItemsByStatusHandlerRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetUserPostHandlerRequestOptions holds all parameters for the GetUserPost operation.
type GetUserPostHandlerRequestOptions struct {
	PathParams *types.GetUserPostPath
	// RawRequest provides access to the underlying HTTP request for custom content type handling.
	RawRequest *http.Request
}

// Validate validates all the fields in the options.
func (o *GetUserPostHandlerRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// CreateOrderHandlerRequestOptions holds all parameters for the CreateOrder operation.
type CreateOrderHandlerRequestOptions struct {
	Body *types.CreateOrderBody
	// RawRequest provides access to the underlying HTTP request for custom content type handling.
	RawRequest *http.Request
}

// Validate validates all the fields in the options.
func (o *CreateOrderHandlerRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.Body != nil {
		if v, ok := any(o.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Body", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// CreateCompanyHandlerRequestOptions holds all parameters for the CreateCompany operation.
type CreateCompanyHandlerRequestOptions struct {
	Body *types.CreateCompanyBody
	// RawRequest provides access to the underlying HTTP request for custom content type handling.
	RawRequest *http.Request
}

// Validate validates all the fields in the options.
func (o *CreateCompanyHandlerRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.Body != nil {
		if v, ok := any(o.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Body", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}
