// Code generated by oapi-codegen. DO NOT EDIT.
package api

import (
	"net/http"
)

// RouterOption is a function that configures the router.
type RouterOption func(*routerConfig)

type routerConfig struct {
	middlewares []func(http.Handler) http.Handler
}

// WithMiddleware adds middleware to the router.
func WithMiddleware(mw func(http.Handler) http.Handler) RouterOption {
	return func(cfg *routerConfig) {
		cfg.middlewares = append(cfg.middlewares, mw)
	}
}

// NewRouter creates a new http.ServeMux with the given handler implementation.
func NewRouter(impl HandlerInterface, opts ...RouterOption) *http.ServeMux {
	cfg := &routerConfig{}
	for _, opt := range opts {
		opt(cfg)
	}

	adapter := NewHTTPAdapter(impl)

	mux := http.NewServeMux()
	mux.HandleFunc("GET /health", applyMiddleware(http.HandlerFunc(adapter.HealthCheck), cfg.middlewares...))
	mux.HandleFunc("GET /users", applyMiddleware(http.HandlerFunc(adapter.ListUsers), cfg.middlewares...))
	mux.HandleFunc("POST /users", applyMiddleware(http.HandlerFunc(adapter.CreateUser), cfg.middlewares...))
	mux.HandleFunc("POST /users/import", applyMiddleware(http.HandlerFunc(adapter.ImportUsers), cfg.middlewares...))
	mux.HandleFunc("GET /users/{id}", applyMiddleware(http.HandlerFunc(adapter.GetUser), cfg.middlewares...))
	mux.HandleFunc("DELETE /users/{id}", applyMiddleware(http.HandlerFunc(adapter.DeleteUser), cfg.middlewares...))
	mux.HandleFunc("GET /users/{id}/avatar", applyMiddleware(http.HandlerFunc(adapter.GetUserAvatar), cfg.middlewares...))
	mux.HandleFunc("PUT /users/{id}/avatar", applyMiddleware(http.HandlerFunc(adapter.UploadUserAvatar), cfg.middlewares...))
	mux.HandleFunc("POST /contact", applyMiddleware(http.HandlerFunc(adapter.SubmitContactForm), cfg.middlewares...))
	mux.HandleFunc("POST /notes", applyMiddleware(http.HandlerFunc(adapter.CreateNote), cfg.middlewares...))
	mux.HandleFunc("POST /xml-data", applyMiddleware(http.HandlerFunc(adapter.ProcessXMLData), cfg.middlewares...))
	mux.HandleFunc("GET /export", applyMiddleware(http.HandlerFunc(adapter.ExportData), cfg.middlewares...))
	mux.HandleFunc("POST /oauth/token", applyMiddleware(http.HandlerFunc(adapter.GetOAuthToken), cfg.middlewares...))
	mux.HandleFunc("GET /items/{type}", applyMiddleware(http.HandlerFunc(adapter.GetItemsByType), cfg.middlewares...))
	mux.HandleFunc("GET /search", applyMiddleware(http.HandlerFunc(adapter.Search), cfg.middlewares...))
	mux.HandleFunc("GET /status", applyMiddleware(http.HandlerFunc(adapter.GetStatus), cfg.middlewares...))
	mux.HandleFunc("POST /images", applyMiddleware(http.HandlerFunc(adapter.UploadImage), cfg.middlewares...))
	mux.HandleFunc("GET /products", applyMiddleware(http.HandlerFunc(adapter.ListProducts), cfg.middlewares...))
	mux.HandleFunc("GET /categories/{categoryId}", applyMiddleware(http.HandlerFunc(adapter.GetCategory), cfg.middlewares...))
	mux.HandleFunc("GET /items/{active}/{rating}", applyMiddleware(http.HandlerFunc(adapter.GetItemsByStatus), cfg.middlewares...))
	mux.HandleFunc("GET /users/{userId}/posts/{postId}", applyMiddleware(http.HandlerFunc(adapter.GetUserPost), cfg.middlewares...))
	mux.HandleFunc("POST /orders", applyMiddleware(http.HandlerFunc(adapter.CreateOrder), cfg.middlewares...))
	mux.HandleFunc("POST /companies", applyMiddleware(http.HandlerFunc(adapter.CreateCompany), cfg.middlewares...))

	return mux
}

// applyMiddleware wraps a handler with the given middleware chain.
func applyMiddleware(h http.Handler, middlewares ...func(http.Handler) http.Handler) http.HandlerFunc {
	for i := len(middlewares) - 1; i >= 0; i-- {
		h = middlewares[i](h)
	}
	return h.ServeHTTP
}
