// Code generated by oapi-codegen. DO NOT EDIT.
package api

import (
	"net/http"

	"github.com/go-chi/chi/v5"
)

// RouterOption is a function that configures the router.
type RouterOption func(*routerConfig)

type routerConfig struct {
	middlewares []func(http.Handler) http.Handler
}

// WithMiddleware adds middleware to the router.
func WithMiddleware(mw func(http.Handler) http.Handler) RouterOption {
	return func(cfg *routerConfig) {
		cfg.middlewares = append(cfg.middlewares, mw)
	}
}

// NewRouter creates a new chi.Router with the given service implementation.
func NewRouter(svc ServiceInterface, opts ...RouterOption) chi.Router {
	cfg := &routerConfig{}
	for _, opt := range opts {
		opt(cfg)
	}

	adapter := NewHTTPAdapter(svc)

	r := chi.NewRouter()
	for _, mw := range cfg.middlewares {
		r.Use(mw)
	}
	r.Method("GET", "/health", http.HandlerFunc(adapter.HealthCheck))
	r.Method("GET", "/users", http.HandlerFunc(adapter.ListUsers))
	r.Method("POST", "/users", http.HandlerFunc(adapter.CreateUser))
	r.Method("POST", "/users/import", http.HandlerFunc(adapter.ImportUsers))
	r.Method("GET", "/users/{id}", http.HandlerFunc(adapter.GetUser))
	r.Method("DELETE", "/users/{id}", http.HandlerFunc(adapter.DeleteUser))
	r.Method("GET", "/users/{id}/avatar", http.HandlerFunc(adapter.GetUserAvatar))
	r.Method("PUT", "/users/{id}/avatar", http.HandlerFunc(adapter.UploadUserAvatar))
	r.Method("POST", "/contact", http.HandlerFunc(adapter.SubmitContactForm))
	r.Method("POST", "/notes", http.HandlerFunc(adapter.CreateNote))
	r.Method("POST", "/xml-data", http.HandlerFunc(adapter.ProcessXMLData))
	r.Method("GET", "/export", http.HandlerFunc(adapter.ExportData))
	r.Method("POST", "/oauth/token", http.HandlerFunc(adapter.GetOAuthToken))
	r.Method("GET", "/items/{type}", http.HandlerFunc(adapter.GetItemsByType))
	r.Method("GET", "/search", http.HandlerFunc(adapter.Search))
	r.Method("GET", "/status", http.HandlerFunc(adapter.GetStatus))
	r.Method("POST", "/images", http.HandlerFunc(adapter.UploadImage))
	r.Method("GET", "/products", http.HandlerFunc(adapter.ListProducts))
	r.Method("GET", "/categories/{categoryId}", http.HandlerFunc(adapter.GetCategory))
	r.Method("GET", "/items/{type}/{rating}", http.HandlerFunc(adapter.GetItemsByStatus))
	r.Method("GET", "/users/{id}/posts/{postId}", http.HandlerFunc(adapter.GetUserPost))
	r.Method("POST", "/orders", http.HandlerFunc(adapter.CreateOrder))
	r.Method("POST", "/companies", http.HandlerFunc(adapter.CreateCompany))

	return r
}
