// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"encoding/json"
	"fmt"

	"github.com/doordash/oapi-codegen/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

var bodyTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type ProcessPaymentBody struct {
	A *string              `json:"a,omitempty"`
	B *string              `json:"b,omitempty"`
	C *ProcessPaymentBodyC `json:"c,omitempty"`
	D *ProcessPaymentBodyD `json:"d,omitempty"`
}

func (p ProcessPaymentBody) Validate() error {
	return bodyTypesValidate.Struct(p)
}

var schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type ProcessPaymentBodyC struct {
	ProcessPaymentBodyCOneOf *ProcessPaymentBodyCOneOf `json:",omitempty"`
}

func (p ProcessPaymentBodyC) Validate() error {
	return schemaTypesValidate.Struct(p)
}

type ProcessPaymentBodyD struct {
	ProcessPaymentBodyDAllOf0 *ProcessPaymentBodyDAllOf0 `json:",omitempty"`
	ProcessPaymentBodyDAllOf1 *ProcessPaymentBodyDAllOf1 `json:",omitempty"`
}

func (p ProcessPaymentBodyD) Validate() error {
	return schemaTypesValidate.Struct(p)
}

type ProcessPaymentBody_D struct {
	ProcessPaymentBodyDAllOf0 *ProcessPaymentBodyDAllOf0 `json:",omitempty"`
	ProcessPaymentBodyDAllOf1 *ProcessPaymentBodyDAllOf1 `json:",omitempty"`
}

type ProcessPaymentBodyDAllOf0 struct {
	ProcessPaymentBodyDAllOf0AnyOf *ProcessPaymentBodyDAllOf0AnyOf `json:",omitempty"`
}

type ProcessPaymentBodyDAllOf1 struct {
	ProcessPaymentBodyDAllOf1AnyOf *ProcessPaymentBodyDAllOf1AnyOf `json:",omitempty"`
}

func UnmarshalAs[T any](v json.RawMessage) (T, error) {
	var res T
	err := json.Unmarshal(v, &res)
	return res, err
}

func marshalJSONWithDiscriminator(data []byte, field, value string) ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)
	if data != nil {
		if err := json.Unmarshal(data, &object); err != nil {
			return nil, err
		}
	}

	object[field], err = json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling discriminator field '%s': %w", field, err)
	}

	return json.Marshal(object)
}

type ProcessPaymentBodyCOneOf struct {
	runtime.Either[string, bool]
}

func (p *ProcessPaymentBodyCOneOf) MarshalJSON() ([]byte, error) {
	data := p.Value()
	if data == nil {
		return nil, nil
	}

	obj, err := json.Marshal(data)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

func (p *ProcessPaymentBodyCOneOf) UnmarshalJSON(data []byte) error {
	return p.Unmarshal(data)
}

type ProcessPaymentBodyDAllOf0AnyOf struct {
	runtime.Either[int, string]
}

func (p *ProcessPaymentBodyDAllOf0AnyOf) MarshalJSON() ([]byte, error) {
	data := p.Value()
	if data == nil {
		return nil, nil
	}

	obj, err := json.Marshal(data)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

func (p *ProcessPaymentBodyDAllOf0AnyOf) UnmarshalJSON(data []byte) error {
	return p.Unmarshal(data)
}

type ProcessPaymentBodyDAllOf1AnyOf struct {
	runtime.Either[bool, float32]
}

func (p *ProcessPaymentBodyDAllOf1AnyOf) MarshalJSON() ([]byte, error) {
	data := p.Value()
	if data == nil {
		return nil, nil
	}

	obj, err := json.Marshal(data)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

func (p *ProcessPaymentBodyDAllOf1AnyOf) UnmarshalJSON(data []byte) error {
	return p.Unmarshal(data)
}
