// Code generated by oapi-codegen. DO NOT EDIT.

package union

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type FileType string

const (
	FileTypeFile FileType = "file"
)

// validFileTypeValues is a map of valid values for FileType
var validFileTypeValues = map[FileType]bool{
	FileTypeFile: true,
}

// Validate checks if the FileType value is valid
func (f FileType) Validate() error {
	if !validFileTypeValues[f] {
		return runtime.NewValidationError("", fmt.Sprintf("invalid FileType value: %v", f))
	}
	return nil
}

type FolderType string

const (
	FolderTypeFolder FolderType = "folder"
)

// validFolderTypeValues is a map of valid values for FolderType
var validFolderTypeValues = map[FolderType]bool{
	FolderTypeFolder: true,
}

// Validate checks if the FolderType value is valid
func (f FolderType) Validate() error {
	if !validFolderTypeValues[f] {
		return runtime.NewValidationError("", fmt.Sprintf("invalid FolderType value: %v", f))
	}
	return nil
}

type WebLinkType string

const (
	WebLinkTypeWebLink WebLinkType = "web_link"
)

// validWebLinkTypeValues is a map of valid values for WebLinkType
var validWebLinkTypeValues = map[WebLinkType]bool{
	WebLinkTypeWebLink: true,
}

// Validate checks if the WebLinkType value is valid
func (w WebLinkType) Validate() error {
	if !validWebLinkTypeValues[w] {
		return runtime.NewValidationError("", fmt.Sprintf("invalid WebLinkType value: %v", w))
	}
	return nil
}

type CollaborationRole string

const (
	CollaborationRoleEditor CollaborationRole = "editor"
	CollaborationRoleOwner  CollaborationRole = "owner"
	CollaborationRoleViewer CollaborationRole = "viewer"
)

// validCollaborationRoleValues is a map of valid values for CollaborationRole
var validCollaborationRoleValues = map[CollaborationRole]bool{
	CollaborationRoleEditor: true,
	CollaborationRoleOwner:  true,
	CollaborationRoleViewer: true,
}

// Validate checks if the CollaborationRole value is valid
func (c CollaborationRole) Validate() error {
	if !validCollaborationRoleValues[c] {
		return runtime.NewValidationError("", fmt.Sprintf("invalid CollaborationRole value: %v", c))
	}
	return nil
}

type GetCollaborationResponseRole string

const (
	GetCollaborationResponseRoleEditor GetCollaborationResponseRole = "editor"
	GetCollaborationResponseRoleOwner  GetCollaborationResponseRole = "owner"
	GetCollaborationResponseRoleViewer GetCollaborationResponseRole = "viewer"
)

// validGetCollaborationResponseRoleValues is a map of valid values for GetCollaborationResponseRole
var validGetCollaborationResponseRoleValues = map[GetCollaborationResponseRole]bool{
	GetCollaborationResponseRoleEditor: true,
	GetCollaborationResponseRoleOwner:  true,
	GetCollaborationResponseRoleViewer: true,
}

// Validate checks if the GetCollaborationResponseRole value is valid
func (g GetCollaborationResponseRole) Validate() error {
	if !validGetCollaborationResponseRoleValues[g] {
		return runtime.NewValidationError("", fmt.Sprintf("invalid GetCollaborationResponseRole value: %v", g))
	}
	return nil
}

type GetCollaborationResponse struct {
	ID   string                           `json:"id" validate:"required"`
	Item *GetCollaboration_Response_Item1 `json:"item,omitempty"`
	Role *GetCollaborationResponseRole    `json:"role,omitempty"`
}

var schemaTypesValidate *validator.Validate

func init() {
	schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(schemaTypesValidate)
}

type File struct {
	Type FileType `json:"type" validate:"required"`
	ID   string   `json:"id" validate:"required"`
	Name *string  `json:"name,omitempty"`
}

func (f File) Validate() error {
	if v, ok := any(f.Type).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			return runtime.NewValidationErrorFromError("Type", err)
		}
	}
	if err := schemaTypesValidate.Var(f.ID, "required"); err != nil {
		return runtime.NewValidationErrorFromError("ID", err)
	}
	return nil
}

type Folder struct {
	Type FolderType `json:"type" validate:"required"`
	ID   string     `json:"id" validate:"required"`
	Name *string    `json:"name,omitempty"`
}

func (f Folder) Validate() error {
	if v, ok := any(f.Type).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			return runtime.NewValidationErrorFromError("Type", err)
		}
	}
	if err := schemaTypesValidate.Var(f.ID, "required"); err != nil {
		return runtime.NewValidationErrorFromError("ID", err)
	}
	return nil
}

type WebLink struct {
	Type WebLinkType `json:"type" validate:"required"`
	ID   string      `json:"id" validate:"required"`
	URL  *string     `json:"url,omitempty"`
}

func (w WebLink) Validate() error {
	if v, ok := any(w.Type).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			return runtime.NewValidationErrorFromError("Type", err)
		}
	}
	if err := schemaTypesValidate.Var(w.ID, "required"); err != nil {
		return runtime.NewValidationErrorFromError("ID", err)
	}
	return nil
}

type Collaboration struct {
	ID   string               `json:"id" validate:"required"`
	Item *Collaboration_Item1 `json:"item,omitempty"`
	Role *CollaborationRole   `json:"role,omitempty"`
}

func (c Collaboration) Validate() error {
	if err := schemaTypesValidate.Var(c.ID, "required"); err != nil {
		return runtime.NewValidationErrorFromError("ID", err)
	}
	if c.Item != nil {
		if v, ok := any(c.Item).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("Item", err)
			}
		}
	}
	if c.Role != nil {
		if v, ok := any(c.Role).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("Role", err)
			}
		}
	}
	return nil
}

type Collaboration_Item1 struct {
	Collaboration_Item_AllOf0 *Collaboration_Item_AllOf0 `json:"-"`
}

func (c Collaboration_Item1) Validate() error {
	if c.Collaboration_Item_AllOf0 != nil {
		if v, ok := any(c.Collaboration_Item_AllOf0).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("Collaboration_Item_AllOf0", err)
			}
		}
	}
	return nil
}

func (c Collaboration_Item1) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(c.Collaboration_Item_AllOf0)
		if err != nil {
			return nil, fmt.Errorf("Collaboration_Item_AllOf0 marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (c *Collaboration_Item1) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if c.Collaboration_Item_AllOf0 == nil {
		c.Collaboration_Item_AllOf0 = &Collaboration_Item_AllOf0{}
	}

	if err := runtime.UnmarshalJSON(data, c.Collaboration_Item_AllOf0); err != nil {
		return fmt.Errorf("Collaboration_Item_AllOf0 unmarshal: %w", err)
	}

	return nil
}

type GetCollaboration_Response_Item1 struct {
	GetCollaboration_Response_Item_AllOf0 *GetCollaboration_Response_Item_AllOf0 `json:"-"`
}

func (g GetCollaboration_Response_Item1) Validate() error {
	if g.GetCollaboration_Response_Item_AllOf0 != nil {
		if v, ok := any(g.GetCollaboration_Response_Item_AllOf0).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("GetCollaboration_Response_Item_AllOf0", err)
			}
		}
	}
	return nil
}

func (g GetCollaboration_Response_Item1) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(g.GetCollaboration_Response_Item_AllOf0)
		if err != nil {
			return nil, fmt.Errorf("GetCollaboration_Response_Item_AllOf0 marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (g *GetCollaboration_Response_Item1) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if g.GetCollaboration_Response_Item_AllOf0 == nil {
		g.GetCollaboration_Response_Item_AllOf0 = &GetCollaboration_Response_Item_AllOf0{}
	}

	if err := runtime.UnmarshalJSON(data, g.GetCollaboration_Response_Item_AllOf0); err != nil {
		return fmt.Errorf("GetCollaboration_Response_Item_AllOf0 unmarshal: %w", err)
	}

	return nil
}

var unionTypesValidate *validator.Validate

func init() {
	unionTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(unionTypesValidate)
}

type Collaboration_Item struct {
	Collaboration_Item_AllOf0 *Collaboration_Item_AllOf0 `json:"-"`
}

func (c Collaboration_Item) Validate() error {
	if c.Collaboration_Item_AllOf0 != nil {
		if v, ok := any(c.Collaboration_Item_AllOf0).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("Collaboration_Item_AllOf0", err)
			}
		}
	}
	return nil
}

func (c Collaboration_Item) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(c.Collaboration_Item_AllOf0)
		if err != nil {
			return nil, fmt.Errorf("Collaboration_Item_AllOf0 marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (c *Collaboration_Item) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if c.Collaboration_Item_AllOf0 == nil {
		c.Collaboration_Item_AllOf0 = &Collaboration_Item_AllOf0{}
	}

	if err := runtime.UnmarshalJSON(data, c.Collaboration_Item_AllOf0); err != nil {
		return fmt.Errorf("Collaboration_Item_AllOf0 unmarshal: %w", err)
	}

	return nil
}

type Collaboration_Item_AllOf0 struct {
	Collaboration_Item_AllOf0_OneOf *Collaboration_Item_AllOf0_OneOf `json:"-"`
}

func (c Collaboration_Item_AllOf0) Validate() error {
	if c.Collaboration_Item_AllOf0_OneOf != nil {
		if v, ok := any(c.Collaboration_Item_AllOf0_OneOf).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("Collaboration_Item_AllOf0_OneOf", err)
			}
		}
	}
	return nil
}

func (c Collaboration_Item_AllOf0) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(c.Collaboration_Item_AllOf0_OneOf)
		if err != nil {
			return nil, fmt.Errorf("Collaboration_Item_AllOf0_OneOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (c *Collaboration_Item_AllOf0) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if c.Collaboration_Item_AllOf0_OneOf == nil {
		c.Collaboration_Item_AllOf0_OneOf = &Collaboration_Item_AllOf0_OneOf{}
	}

	if err := runtime.UnmarshalJSON(data, c.Collaboration_Item_AllOf0_OneOf); err != nil {
		return fmt.Errorf("Collaboration_Item_AllOf0_OneOf unmarshal: %w", err)
	}

	return nil
}

type GetCollaboration_Response_Item struct {
	GetCollaboration_Response_Item_AllOf0 *GetCollaboration_Response_Item_AllOf0 `json:"-"`
}

func (g GetCollaboration_Response_Item) Validate() error {
	if g.GetCollaboration_Response_Item_AllOf0 != nil {
		if v, ok := any(g.GetCollaboration_Response_Item_AllOf0).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("GetCollaboration_Response_Item_AllOf0", err)
			}
		}
	}
	return nil
}

func (g GetCollaboration_Response_Item) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(g.GetCollaboration_Response_Item_AllOf0)
		if err != nil {
			return nil, fmt.Errorf("GetCollaboration_Response_Item_AllOf0 marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (g *GetCollaboration_Response_Item) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if g.GetCollaboration_Response_Item_AllOf0 == nil {
		g.GetCollaboration_Response_Item_AllOf0 = &GetCollaboration_Response_Item_AllOf0{}
	}

	if err := runtime.UnmarshalJSON(data, g.GetCollaboration_Response_Item_AllOf0); err != nil {
		return fmt.Errorf("GetCollaboration_Response_Item_AllOf0 unmarshal: %w", err)
	}

	return nil
}

type GetCollaboration_Response_Item_AllOf0 struct {
	GetCollaboration_Response_Item_AllOf0_OneOf *GetCollaboration_Response_Item_AllOf0_OneOf `json:"-"`
}

func (g GetCollaboration_Response_Item_AllOf0) Validate() error {
	if g.GetCollaboration_Response_Item_AllOf0_OneOf != nil {
		if v, ok := any(g.GetCollaboration_Response_Item_AllOf0_OneOf).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("GetCollaboration_Response_Item_AllOf0_OneOf", err)
			}
		}
	}
	return nil
}

func (g GetCollaboration_Response_Item_AllOf0) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(g.GetCollaboration_Response_Item_AllOf0_OneOf)
		if err != nil {
			return nil, fmt.Errorf("GetCollaboration_Response_Item_AllOf0_OneOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (g *GetCollaboration_Response_Item_AllOf0) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if g.GetCollaboration_Response_Item_AllOf0_OneOf == nil {
		g.GetCollaboration_Response_Item_AllOf0_OneOf = &GetCollaboration_Response_Item_AllOf0_OneOf{}
	}

	if err := runtime.UnmarshalJSON(data, g.GetCollaboration_Response_Item_AllOf0_OneOf); err != nil {
		return fmt.Errorf("GetCollaboration_Response_Item_AllOf0_OneOf unmarshal: %w", err)
	}

	return nil
}

func UnmarshalAs[T any](v json.RawMessage) (T, error) {
	var res T
	err := json.Unmarshal(v, &res)
	return res, err
}

func marshalJSONWithDiscriminator(data []byte, field, value string) ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)
	if data != nil {
		if err := json.Unmarshal(data, &object); err != nil {
			return nil, err
		}
	}

	object[field], err = json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling discriminator field '%s': %w", field, err)
	}

	return json.Marshal(object)
}

type Collaboration_Item_AllOf0_OneOf struct {
	union json.RawMessage
}

func (c *Collaboration_Item_AllOf0_OneOf) Validate() error {
	return nil
}

// Raw returns the union data inside the Collaboration_Item_AllOf0_OneOf as bytes
func (c *Collaboration_Item_AllOf0_OneOf) Raw() json.RawMessage {
	return c.union
}

// AsFile returns the union data inside the Collaboration_Item_AllOf0_OneOf as a File
func (c *Collaboration_Item_AllOf0_OneOf) AsFile() (File, error) {
	return UnmarshalAs[File](c.union)
}

// FromFile overwrites any union data inside the Collaboration_Item_AllOf0_OneOf as the provided File
func (c *Collaboration_Item_AllOf0_OneOf) FromFile(val File) error {
	bts, err := json.Marshal(val)
	c.union = bts
	return err
}

// AsFolder returns the union data inside the Collaboration_Item_AllOf0_OneOf as a Folder
func (c *Collaboration_Item_AllOf0_OneOf) AsFolder() (Folder, error) {
	return UnmarshalAs[Folder](c.union)
}

// FromFolder overwrites any union data inside the Collaboration_Item_AllOf0_OneOf as the provided Folder
func (c *Collaboration_Item_AllOf0_OneOf) FromFolder(val Folder) error {
	bts, err := json.Marshal(val)
	c.union = bts
	return err
}

// AsWebLink returns the union data inside the Collaboration_Item_AllOf0_OneOf as a WebLink
func (c *Collaboration_Item_AllOf0_OneOf) AsWebLink() (WebLink, error) {
	return UnmarshalAs[WebLink](c.union)
}

// FromWebLink overwrites any union data inside the Collaboration_Item_AllOf0_OneOf as the provided WebLink
func (c *Collaboration_Item_AllOf0_OneOf) FromWebLink(val WebLink) error {
	bts, err := json.Marshal(val)
	c.union = bts
	return err
}

func (c Collaboration_Item_AllOf0_OneOf) MarshalJSON() ([]byte, error) {
	bts, err := c.union.MarshalJSON()

	return bts, err
}

func (c *Collaboration_Item_AllOf0_OneOf) UnmarshalJSON(bts []byte) error {
	err := c.union.UnmarshalJSON(bts)

	return err
}

type GetCollaboration_Response_Item_AllOf0_OneOf struct {
	union json.RawMessage
}

func (g *GetCollaboration_Response_Item_AllOf0_OneOf) Validate() error {
	return nil
}

// Raw returns the union data inside the GetCollaboration_Response_Item_AllOf0_OneOf as bytes
func (g *GetCollaboration_Response_Item_AllOf0_OneOf) Raw() json.RawMessage {
	return g.union
}

// AsFile returns the union data inside the GetCollaboration_Response_Item_AllOf0_OneOf as a File
func (g *GetCollaboration_Response_Item_AllOf0_OneOf) AsFile() (File, error) {
	return UnmarshalAs[File](g.union)
}

// FromFile overwrites any union data inside the GetCollaboration_Response_Item_AllOf0_OneOf as the provided File
func (g *GetCollaboration_Response_Item_AllOf0_OneOf) FromFile(val File) error {
	bts, err := json.Marshal(val)
	g.union = bts
	return err
}

// AsFolder returns the union data inside the GetCollaboration_Response_Item_AllOf0_OneOf as a Folder
func (g *GetCollaboration_Response_Item_AllOf0_OneOf) AsFolder() (Folder, error) {
	return UnmarshalAs[Folder](g.union)
}

// FromFolder overwrites any union data inside the GetCollaboration_Response_Item_AllOf0_OneOf as the provided Folder
func (g *GetCollaboration_Response_Item_AllOf0_OneOf) FromFolder(val Folder) error {
	bts, err := json.Marshal(val)
	g.union = bts
	return err
}

// AsWebLink returns the union data inside the GetCollaboration_Response_Item_AllOf0_OneOf as a WebLink
func (g *GetCollaboration_Response_Item_AllOf0_OneOf) AsWebLink() (WebLink, error) {
	return UnmarshalAs[WebLink](g.union)
}

// FromWebLink overwrites any union data inside the GetCollaboration_Response_Item_AllOf0_OneOf as the provided WebLink
func (g *GetCollaboration_Response_Item_AllOf0_OneOf) FromWebLink(val WebLink) error {
	bts, err := json.Marshal(val)
	g.union = bts
	return err
}

func (g GetCollaboration_Response_Item_AllOf0_OneOf) MarshalJSON() ([]byte, error) {
	bts, err := g.union.MarshalJSON()

	return bts, err
}

func (g *GetCollaboration_Response_Item_AllOf0_OneOf) UnmarshalJSON(bts []byte) error {
	err := g.union.UnmarshalJSON(bts)

	return err
}
