// Code generated by oapi-codegen. DO NOT EDIT.

package globalparams

import (
	"github.com/go-playground/validator/v10"
)

var queryTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type GetItemsQuery struct {
	// Filter Filter items (first definition - string)
	Filter *string `json:"filter,omitempty"`
}

func (g GetItemsQuery) Validate() error {
	return queryTypesValidate.Struct(g)
}

type CreateItemQuery struct {
	// Filter Filter items (first definition - string)
	Filter *string `json:"filter,omitempty"`
}

func (c CreateItemQuery) Validate() error {
	return queryTypesValidate.Struct(c)
}

type GetItemsResponse struct {
	Items []string `json:"items,omitempty"`
}
