openapi: "3.0.0"
info:
  version: 1.0.0
  title: Error Mapping with Reference
paths:
  /files:
    get:
      operationId: getFiles
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                properties:
                  name:
                    type: string
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
components:
  schemas:
    error:
      description: An error response from the Stripe API
      properties:
        error:
          $ref: '#/components/schemas/api_errors'
      required:
        - error
      type: object
    api_errors:
      properties:
        message:
          type: string
        type:
          type: string
      required:
        - type
      title: APIErrors
      type: object
