// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type ListItemsResponse = Item

type Item struct {
	Level           *string          `json:"level,omitempty"`
	Item_IfThenElse *Item_IfThenElse `json:"-"`
}

func (i Item) Validate() error {
	var errors runtime.ValidationErrors
	if i.Item_IfThenElse != nil {
		if v, ok := any(i.Item_IfThenElse).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Item_IfThenElse", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (i Item) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	type _Alias_Item Item
	baseJSON, err := json.Marshal((_Alias_Item)(i))
	if err != nil {
		return nil, err
	}
	parts = append(parts, baseJSON)

	{
		b, err := runtime.MarshalJSON(i.Item_IfThenElse)
		if err != nil {
			return nil, fmt.Errorf("Item_IfThenElse marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (i *Item) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if len(trim) > 0 {
		type _Alias_Item Item
		var tmp _Alias_Item
		if err := json.Unmarshal(data, &tmp); err != nil {
			return err
		}
		*i = Item(tmp)
	}

	if i.Item_IfThenElse == nil {
		i.Item_IfThenElse = &Item_IfThenElse{}
	}

	if err := runtime.UnmarshalJSON(data, i.Item_IfThenElse); err != nil {
		return fmt.Errorf("Item_IfThenElse unmarshal: %w", err)
	}

	return nil
}

type Item_Then struct {
	OuterField  *string `json:"outerField,omitempty"`
	NestedField *int    `json:"nestedField,omitempty"`
}

type Item_Else struct {
	FallbackField *bool `json:"fallbackField,omitempty"`
}

type Item_IfThenElse struct {
	runtime.Conditional[Item_Then, Item_Else]
}

func (i *Item_IfThenElse) Validate() error {
	if i.IsThen() {
		if v, ok := any(i.Then).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if i.IsElse() {
		if v, ok := any(i.Else).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
