// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type SpecificErrorIssuesAnyOf0Issue string

const (
	SpecificErrorIssuesAnyOf0IssueERRORA SpecificErrorIssuesAnyOf0Issue = "ERROR_A"
)

// validSpecificErrorIssuesAnyOf0IssueValues is a map of valid values for SpecificErrorIssuesAnyOf0Issue
var validSpecificErrorIssuesAnyOf0IssueValues = map[SpecificErrorIssuesAnyOf0Issue]bool{
	SpecificErrorIssuesAnyOf0IssueERRORA: true,
}

// Validate checks if the SpecificErrorIssuesAnyOf0Issue value is valid
func (s SpecificErrorIssuesAnyOf0Issue) Validate() error {
	if !validSpecificErrorIssuesAnyOf0IssueValues[s] {
		return runtime.NewValidationError("", fmt.Sprintf("invalid SpecificErrorIssuesAnyOf0Issue value: %v", s))
	}
	return nil
}

type SpecificErrorIssuesAnyOf0Description string

const (
	SpecificErrorIssuesAnyOf0DescriptionThisIsErrorTypeA SpecificErrorIssuesAnyOf0Description = "This is error type A"
)

// validSpecificErrorIssuesAnyOf0DescriptionValues is a map of valid values for SpecificErrorIssuesAnyOf0Description
var validSpecificErrorIssuesAnyOf0DescriptionValues = map[SpecificErrorIssuesAnyOf0Description]bool{
	SpecificErrorIssuesAnyOf0DescriptionThisIsErrorTypeA: true,
}

// Validate checks if the SpecificErrorIssuesAnyOf0Description value is valid
func (s SpecificErrorIssuesAnyOf0Description) Validate() error {
	if !validSpecificErrorIssuesAnyOf0DescriptionValues[s] {
		return runtime.NewValidationError("", fmt.Sprintf("invalid SpecificErrorIssuesAnyOf0Description value: %v", s))
	}
	return nil
}

type SpecificErrorIssuesAnyOf1Issue string

const (
	SpecificErrorIssuesAnyOf1IssueERRORB SpecificErrorIssuesAnyOf1Issue = "ERROR_B"
)

// validSpecificErrorIssuesAnyOf1IssueValues is a map of valid values for SpecificErrorIssuesAnyOf1Issue
var validSpecificErrorIssuesAnyOf1IssueValues = map[SpecificErrorIssuesAnyOf1Issue]bool{
	SpecificErrorIssuesAnyOf1IssueERRORB: true,
}

// Validate checks if the SpecificErrorIssuesAnyOf1Issue value is valid
func (s SpecificErrorIssuesAnyOf1Issue) Validate() error {
	if !validSpecificErrorIssuesAnyOf1IssueValues[s] {
		return runtime.NewValidationError("", fmt.Sprintf("invalid SpecificErrorIssuesAnyOf1Issue value: %v", s))
	}
	return nil
}

type SpecificErrorIssuesAnyOf1Description string

const (
	SpecificErrorIssuesAnyOf1DescriptionThisIsErrorTypeB SpecificErrorIssuesAnyOf1Description = "This is error type B"
)

// validSpecificErrorIssuesAnyOf1DescriptionValues is a map of valid values for SpecificErrorIssuesAnyOf1Description
var validSpecificErrorIssuesAnyOf1DescriptionValues = map[SpecificErrorIssuesAnyOf1Description]bool{
	SpecificErrorIssuesAnyOf1DescriptionThisIsErrorTypeB: true,
}

// Validate checks if the SpecificErrorIssuesAnyOf1Description value is valid
func (s SpecificErrorIssuesAnyOf1Description) Validate() error {
	if !validSpecificErrorIssuesAnyOf1DescriptionValues[s] {
		return runtime.NewValidationError("", fmt.Sprintf("invalid SpecificErrorIssuesAnyOf1Description value: %v", s))
	}
	return nil
}

type SpecificErrorIssuesAnyOf2Issue string

const (
	SpecificErrorIssuesAnyOf2IssueERRORC SpecificErrorIssuesAnyOf2Issue = "ERROR_C"
)

// validSpecificErrorIssuesAnyOf2IssueValues is a map of valid values for SpecificErrorIssuesAnyOf2Issue
var validSpecificErrorIssuesAnyOf2IssueValues = map[SpecificErrorIssuesAnyOf2Issue]bool{
	SpecificErrorIssuesAnyOf2IssueERRORC: true,
}

// Validate checks if the SpecificErrorIssuesAnyOf2Issue value is valid
func (s SpecificErrorIssuesAnyOf2Issue) Validate() error {
	if !validSpecificErrorIssuesAnyOf2IssueValues[s] {
		return runtime.NewValidationError("", fmt.Sprintf("invalid SpecificErrorIssuesAnyOf2Issue value: %v", s))
	}
	return nil
}

type SpecificErrorIssuesAnyOf2Description string

const (
	SpecificErrorIssuesAnyOf2DescriptionThisIsErrorTypeC SpecificErrorIssuesAnyOf2Description = "This is error type C"
)

// validSpecificErrorIssuesAnyOf2DescriptionValues is a map of valid values for SpecificErrorIssuesAnyOf2Description
var validSpecificErrorIssuesAnyOf2DescriptionValues = map[SpecificErrorIssuesAnyOf2Description]bool{
	SpecificErrorIssuesAnyOf2DescriptionThisIsErrorTypeC: true,
}

// Validate checks if the SpecificErrorIssuesAnyOf2Description value is valid
func (s SpecificErrorIssuesAnyOf2Description) Validate() error {
	if !validSpecificErrorIssuesAnyOf2DescriptionValues[s] {
		return runtime.NewValidationError("", fmt.Sprintf("invalid SpecificErrorIssuesAnyOf2Description value: %v", s))
	}
	return nil
}

type CombinedErrorMergedIssuesAnyOf0Issue string

const (
	CombinedErrorMergedIssuesAnyOf0IssueERRORA CombinedErrorMergedIssuesAnyOf0Issue = "ERROR_A"
)

// validCombinedErrorMergedIssuesAnyOf0IssueValues is a map of valid values for CombinedErrorMergedIssuesAnyOf0Issue
var validCombinedErrorMergedIssuesAnyOf0IssueValues = map[CombinedErrorMergedIssuesAnyOf0Issue]bool{
	CombinedErrorMergedIssuesAnyOf0IssueERRORA: true,
}

// Validate checks if the CombinedErrorMergedIssuesAnyOf0Issue value is valid
func (c CombinedErrorMergedIssuesAnyOf0Issue) Validate() error {
	if !validCombinedErrorMergedIssuesAnyOf0IssueValues[c] {
		return runtime.NewValidationError("", fmt.Sprintf("invalid CombinedErrorMergedIssuesAnyOf0Issue value: %v", c))
	}
	return nil
}

type CombinedErrorMergedIssuesAnyOf0Description string

const (
	CombinedErrorMergedIssuesAnyOf0DescriptionThisIsErrorTypeA CombinedErrorMergedIssuesAnyOf0Description = "This is error type A"
)

// validCombinedErrorMergedIssuesAnyOf0DescriptionValues is a map of valid values for CombinedErrorMergedIssuesAnyOf0Description
var validCombinedErrorMergedIssuesAnyOf0DescriptionValues = map[CombinedErrorMergedIssuesAnyOf0Description]bool{
	CombinedErrorMergedIssuesAnyOf0DescriptionThisIsErrorTypeA: true,
}

// Validate checks if the CombinedErrorMergedIssuesAnyOf0Description value is valid
func (c CombinedErrorMergedIssuesAnyOf0Description) Validate() error {
	if !validCombinedErrorMergedIssuesAnyOf0DescriptionValues[c] {
		return runtime.NewValidationError("", fmt.Sprintf("invalid CombinedErrorMergedIssuesAnyOf0Description value: %v", c))
	}
	return nil
}

type CombinedErrorMergedIssuesAnyOf1Issue string

const (
	CombinedErrorMergedIssuesAnyOf1IssueERRORB CombinedErrorMergedIssuesAnyOf1Issue = "ERROR_B"
)

// validCombinedErrorMergedIssuesAnyOf1IssueValues is a map of valid values for CombinedErrorMergedIssuesAnyOf1Issue
var validCombinedErrorMergedIssuesAnyOf1IssueValues = map[CombinedErrorMergedIssuesAnyOf1Issue]bool{
	CombinedErrorMergedIssuesAnyOf1IssueERRORB: true,
}

// Validate checks if the CombinedErrorMergedIssuesAnyOf1Issue value is valid
func (c CombinedErrorMergedIssuesAnyOf1Issue) Validate() error {
	if !validCombinedErrorMergedIssuesAnyOf1IssueValues[c] {
		return runtime.NewValidationError("", fmt.Sprintf("invalid CombinedErrorMergedIssuesAnyOf1Issue value: %v", c))
	}
	return nil
}

type CombinedErrorMergedIssuesAnyOf1Description string

const (
	CombinedErrorMergedIssuesAnyOf1DescriptionThisIsErrorTypeB CombinedErrorMergedIssuesAnyOf1Description = "This is error type B"
)

// validCombinedErrorMergedIssuesAnyOf1DescriptionValues is a map of valid values for CombinedErrorMergedIssuesAnyOf1Description
var validCombinedErrorMergedIssuesAnyOf1DescriptionValues = map[CombinedErrorMergedIssuesAnyOf1Description]bool{
	CombinedErrorMergedIssuesAnyOf1DescriptionThisIsErrorTypeB: true,
}

// Validate checks if the CombinedErrorMergedIssuesAnyOf1Description value is valid
func (c CombinedErrorMergedIssuesAnyOf1Description) Validate() error {
	if !validCombinedErrorMergedIssuesAnyOf1DescriptionValues[c] {
		return runtime.NewValidationError("", fmt.Sprintf("invalid CombinedErrorMergedIssuesAnyOf1Description value: %v", c))
	}
	return nil
}

type CombinedErrorMergedIssuesAnyOf2Issue string

const (
	CombinedErrorMergedIssuesAnyOf2IssueERRORC CombinedErrorMergedIssuesAnyOf2Issue = "ERROR_C"
)

// validCombinedErrorMergedIssuesAnyOf2IssueValues is a map of valid values for CombinedErrorMergedIssuesAnyOf2Issue
var validCombinedErrorMergedIssuesAnyOf2IssueValues = map[CombinedErrorMergedIssuesAnyOf2Issue]bool{
	CombinedErrorMergedIssuesAnyOf2IssueERRORC: true,
}

// Validate checks if the CombinedErrorMergedIssuesAnyOf2Issue value is valid
func (c CombinedErrorMergedIssuesAnyOf2Issue) Validate() error {
	if !validCombinedErrorMergedIssuesAnyOf2IssueValues[c] {
		return runtime.NewValidationError("", fmt.Sprintf("invalid CombinedErrorMergedIssuesAnyOf2Issue value: %v", c))
	}
	return nil
}

type CombinedErrorMergedIssuesAnyOf2Description string

const (
	CombinedErrorMergedIssuesAnyOf2DescriptionThisIsErrorTypeC CombinedErrorMergedIssuesAnyOf2Description = "This is error type C"
)

// validCombinedErrorMergedIssuesAnyOf2DescriptionValues is a map of valid values for CombinedErrorMergedIssuesAnyOf2Description
var validCombinedErrorMergedIssuesAnyOf2DescriptionValues = map[CombinedErrorMergedIssuesAnyOf2Description]bool{
	CombinedErrorMergedIssuesAnyOf2DescriptionThisIsErrorTypeC: true,
}

// Validate checks if the CombinedErrorMergedIssuesAnyOf2Description value is valid
func (c CombinedErrorMergedIssuesAnyOf2Description) Validate() error {
	if !validCombinedErrorMergedIssuesAnyOf2DescriptionValues[c] {
		return runtime.NewValidationError("", fmt.Sprintf("invalid CombinedErrorMergedIssuesAnyOf2Description value: %v", c))
	}
	return nil
}

var bodyTypesValidate *validator.Validate

func init() {
	bodyTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(bodyTypesValidate)
}

type TestEndpointBody = CombinedError

var schemaTypesValidate *validator.Validate

func init() {
	schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(schemaTypesValidate)
}

type BaseError struct {
	Name    *string           `json:"name,omitempty"`
	Message *string           `json:"message,omitempty"`
	Issues  *BaseError_Issues `json:"issues,omitempty"`
}

func (b BaseError) Validate() error {
	if b.Issues != nil {
		if v, ok := any(b.Issues).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("Issues", err)
			}
		}
	}
	return nil
}

type BaseError_Issues []BaseError_Issues_Item

func (b BaseError_Issues) Validate() error {
	for i, item := range b {
		if v, ok := any(item).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError(fmt.Sprintf("[%d]", i), err)
			}
		}
	}
	return nil
}

type BaseError_Issues_Item struct {
	Field *string `json:"field,omitempty"`
	Issue *string `json:"issue,omitempty"`
}

func (b BaseError_Issues_Item) Validate() error {
	return schemaTypesValidate.Struct(b)
}

type SpecificError struct {
	Issues *SpecificError_Issues `json:"issues,omitempty"`
}

func (s SpecificError) Validate() error {
	if s.Issues != nil {
		if v, ok := any(s.Issues).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("Issues", err)
			}
		}
	}
	return nil
}

type SpecificError_Issues []SpecificError_Issues_Item

func (s SpecificError_Issues) Validate() error {
	for i, item := range s {
		if v, ok := any(item).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError(fmt.Sprintf("[%d]", i), err)
			}
		}
	}
	return nil
}

type SpecificError_Issues_Item struct {
	SpecificError_Issues_AnyOf *SpecificError_Issues_AnyOf `json:"-"`
}

func (s SpecificError_Issues_Item) Validate() error {
	if s.SpecificError_Issues_AnyOf != nil {
		if v, ok := any(s.SpecificError_Issues_AnyOf).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("SpecificError_Issues_AnyOf", err)
			}
		}
	}
	return nil
}

func (s SpecificError_Issues_Item) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(s.SpecificError_Issues_AnyOf)
		if err != nil {
			return nil, fmt.Errorf("SpecificError_Issues_AnyOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (s *SpecificError_Issues_Item) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if s.SpecificError_Issues_AnyOf == nil {
		s.SpecificError_Issues_AnyOf = &SpecificError_Issues_AnyOf{}
	}

	if err := runtime.UnmarshalJSON(data, s.SpecificError_Issues_AnyOf); err != nil {
		return fmt.Errorf("SpecificError_Issues_AnyOf unmarshal: %w", err)
	}

	return nil
}

type CombinedError struct {
	Name    *string                      `json:"name,omitempty"`
	Message *string                      `json:"message,omitempty"`
	Issues  *CombinedError_Merged_Issues `json:"issues,omitempty"`
}

func (c CombinedError) Validate() error {
	if c.Issues != nil {
		if v, ok := any(c.Issues).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("Issues", err)
			}
		}
	}
	return nil
}

type CombinedError_Merged_Issues []CombinedError_Merged_Issues_Item

func (c CombinedError_Merged_Issues) Validate() error {
	for i, item := range c {
		if v, ok := any(item).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError(fmt.Sprintf("[%d]", i), err)
			}
		}
	}
	return nil
}

type CombinedError_Merged_Issues_Item struct {
	CombinedError_Merged_Issues_AnyOf *CombinedError_Merged_Issues_AnyOf `json:"-"`
}

func (c CombinedError_Merged_Issues_Item) Validate() error {
	if c.CombinedError_Merged_Issues_AnyOf != nil {
		if v, ok := any(c.CombinedError_Merged_Issues_AnyOf).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("CombinedError_Merged_Issues_AnyOf", err)
			}
		}
	}
	return nil
}

func (c CombinedError_Merged_Issues_Item) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(c.CombinedError_Merged_Issues_AnyOf)
		if err != nil {
			return nil, fmt.Errorf("CombinedError_Merged_Issues_AnyOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (c *CombinedError_Merged_Issues_Item) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if c.CombinedError_Merged_Issues_AnyOf == nil {
		c.CombinedError_Merged_Issues_AnyOf = &CombinedError_Merged_Issues_AnyOf{}
	}

	if err := runtime.UnmarshalJSON(data, c.CombinedError_Merged_Issues_AnyOf); err != nil {
		return fmt.Errorf("CombinedError_Merged_Issues_AnyOf unmarshal: %w", err)
	}

	return nil
}

var unionTypesValidate *validator.Validate

func init() {
	unionTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(unionTypesValidate)
}

type SpecificError_Issues_AnyOf_0 struct {
	Issue       *SpecificErrorIssuesAnyOf0Issue       `json:"issue,omitempty"`
	Description *SpecificErrorIssuesAnyOf0Description `json:"description,omitempty"`
}

func (s SpecificError_Issues_AnyOf_0) Validate() error {
	if s.Issue != nil {
		if v, ok := any(s.Issue).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("Issue", err)
			}
		}
	}
	if s.Description != nil {
		if v, ok := any(s.Description).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("Description", err)
			}
		}
	}
	return nil
}

type SpecificError_Issues_AnyOf_1 struct {
	Issue       *SpecificErrorIssuesAnyOf1Issue       `json:"issue,omitempty"`
	Description *SpecificErrorIssuesAnyOf1Description `json:"description,omitempty"`
}

func (s SpecificError_Issues_AnyOf_1) Validate() error {
	if s.Issue != nil {
		if v, ok := any(s.Issue).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("Issue", err)
			}
		}
	}
	if s.Description != nil {
		if v, ok := any(s.Description).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("Description", err)
			}
		}
	}
	return nil
}

type SpecificError_Issues_AnyOf_2 struct {
	Issue       *SpecificErrorIssuesAnyOf2Issue       `json:"issue,omitempty"`
	Description *SpecificErrorIssuesAnyOf2Description `json:"description,omitempty"`
}

func (s SpecificError_Issues_AnyOf_2) Validate() error {
	if s.Issue != nil {
		if v, ok := any(s.Issue).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("Issue", err)
			}
		}
	}
	if s.Description != nil {
		if v, ok := any(s.Description).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("Description", err)
			}
		}
	}
	return nil
}

type CombinedError_Merged_Issues_AnyOf_0 struct {
	Issue       *CombinedErrorMergedIssuesAnyOf0Issue       `json:"issue,omitempty"`
	Description *CombinedErrorMergedIssuesAnyOf0Description `json:"description,omitempty"`
}

func (c CombinedError_Merged_Issues_AnyOf_0) Validate() error {
	if c.Issue != nil {
		if v, ok := any(c.Issue).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("Issue", err)
			}
		}
	}
	if c.Description != nil {
		if v, ok := any(c.Description).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("Description", err)
			}
		}
	}
	return nil
}

type CombinedError_Merged_Issues_AnyOf_1 struct {
	Issue       *CombinedErrorMergedIssuesAnyOf1Issue       `json:"issue,omitempty"`
	Description *CombinedErrorMergedIssuesAnyOf1Description `json:"description,omitempty"`
}

func (c CombinedError_Merged_Issues_AnyOf_1) Validate() error {
	if c.Issue != nil {
		if v, ok := any(c.Issue).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("Issue", err)
			}
		}
	}
	if c.Description != nil {
		if v, ok := any(c.Description).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("Description", err)
			}
		}
	}
	return nil
}

type CombinedError_Merged_Issues_AnyOf_2 struct {
	Issue       *CombinedErrorMergedIssuesAnyOf2Issue       `json:"issue,omitempty"`
	Description *CombinedErrorMergedIssuesAnyOf2Description `json:"description,omitempty"`
}

func (c CombinedError_Merged_Issues_AnyOf_2) Validate() error {
	if c.Issue != nil {
		if v, ok := any(c.Issue).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("Issue", err)
			}
		}
	}
	if c.Description != nil {
		if v, ok := any(c.Description).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("Description", err)
			}
		}
	}
	return nil
}

func UnmarshalAs[T any](v json.RawMessage) (T, error) {
	var res T
	err := json.Unmarshal(v, &res)
	return res, err
}

func marshalJSONWithDiscriminator(data []byte, field, value string) ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)
	if data != nil {
		if err := json.Unmarshal(data, &object); err != nil {
			return nil, err
		}
	}

	object[field], err = json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling discriminator field '%s': %w", field, err)
	}

	return json.Marshal(object)
}

type SpecificError_Issues_AnyOf struct {
	union json.RawMessage
}

func (s *SpecificError_Issues_AnyOf) Validate() error {
	return nil
}

// Raw returns the union data inside the SpecificError_Issues_AnyOf as bytes
func (s *SpecificError_Issues_AnyOf) Raw() json.RawMessage {
	return s.union
}

// AsSpecificError_Issues_AnyOf_0 returns the union data inside the SpecificError_Issues_AnyOf as a SpecificError_Issues_AnyOf_0
func (s *SpecificError_Issues_AnyOf) AsSpecificError_Issues_AnyOf_0() (SpecificError_Issues_AnyOf_0, error) {
	return UnmarshalAs[SpecificError_Issues_AnyOf_0](s.union)
}

// FromSpecificError_Issues_AnyOf_0 overwrites any union data inside the SpecificError_Issues_AnyOf as the provided SpecificError_Issues_AnyOf_0
func (s *SpecificError_Issues_AnyOf) FromSpecificError_Issues_AnyOf_0(val SpecificError_Issues_AnyOf_0) error {
	bts, err := json.Marshal(val)
	s.union = bts
	return err
}

// AsSpecificError_Issues_AnyOf_1 returns the union data inside the SpecificError_Issues_AnyOf as a SpecificError_Issues_AnyOf_1
func (s *SpecificError_Issues_AnyOf) AsSpecificError_Issues_AnyOf_1() (SpecificError_Issues_AnyOf_1, error) {
	return UnmarshalAs[SpecificError_Issues_AnyOf_1](s.union)
}

// FromSpecificError_Issues_AnyOf_1 overwrites any union data inside the SpecificError_Issues_AnyOf as the provided SpecificError_Issues_AnyOf_1
func (s *SpecificError_Issues_AnyOf) FromSpecificError_Issues_AnyOf_1(val SpecificError_Issues_AnyOf_1) error {
	bts, err := json.Marshal(val)
	s.union = bts
	return err
}

// AsSpecificError_Issues_AnyOf_2 returns the union data inside the SpecificError_Issues_AnyOf as a SpecificError_Issues_AnyOf_2
func (s *SpecificError_Issues_AnyOf) AsSpecificError_Issues_AnyOf_2() (SpecificError_Issues_AnyOf_2, error) {
	return UnmarshalAs[SpecificError_Issues_AnyOf_2](s.union)
}

// FromSpecificError_Issues_AnyOf_2 overwrites any union data inside the SpecificError_Issues_AnyOf as the provided SpecificError_Issues_AnyOf_2
func (s *SpecificError_Issues_AnyOf) FromSpecificError_Issues_AnyOf_2(val SpecificError_Issues_AnyOf_2) error {
	bts, err := json.Marshal(val)
	s.union = bts
	return err
}

func (s SpecificError_Issues_AnyOf) MarshalJSON() ([]byte, error) {
	bts, err := s.union.MarshalJSON()

	return bts, err
}

func (s *SpecificError_Issues_AnyOf) UnmarshalJSON(bts []byte) error {
	err := s.union.UnmarshalJSON(bts)

	return err
}

type CombinedError_Merged_Issues_AnyOf struct {
	union json.RawMessage
}

func (c *CombinedError_Merged_Issues_AnyOf) Validate() error {
	return nil
}

// Raw returns the union data inside the CombinedError_Merged_Issues_AnyOf as bytes
func (c *CombinedError_Merged_Issues_AnyOf) Raw() json.RawMessage {
	return c.union
}

// AsCombinedError_Merged_Issues_AnyOf_0 returns the union data inside the CombinedError_Merged_Issues_AnyOf as a CombinedError_Merged_Issues_AnyOf_0
func (c *CombinedError_Merged_Issues_AnyOf) AsCombinedError_Merged_Issues_AnyOf_0() (CombinedError_Merged_Issues_AnyOf_0, error) {
	return UnmarshalAs[CombinedError_Merged_Issues_AnyOf_0](c.union)
}

// FromCombinedError_Merged_Issues_AnyOf_0 overwrites any union data inside the CombinedError_Merged_Issues_AnyOf as the provided CombinedError_Merged_Issues_AnyOf_0
func (c *CombinedError_Merged_Issues_AnyOf) FromCombinedError_Merged_Issues_AnyOf_0(val CombinedError_Merged_Issues_AnyOf_0) error {
	bts, err := json.Marshal(val)
	c.union = bts
	return err
}

// AsCombinedError_Merged_Issues_AnyOf_1 returns the union data inside the CombinedError_Merged_Issues_AnyOf as a CombinedError_Merged_Issues_AnyOf_1
func (c *CombinedError_Merged_Issues_AnyOf) AsCombinedError_Merged_Issues_AnyOf_1() (CombinedError_Merged_Issues_AnyOf_1, error) {
	return UnmarshalAs[CombinedError_Merged_Issues_AnyOf_1](c.union)
}

// FromCombinedError_Merged_Issues_AnyOf_1 overwrites any union data inside the CombinedError_Merged_Issues_AnyOf as the provided CombinedError_Merged_Issues_AnyOf_1
func (c *CombinedError_Merged_Issues_AnyOf) FromCombinedError_Merged_Issues_AnyOf_1(val CombinedError_Merged_Issues_AnyOf_1) error {
	bts, err := json.Marshal(val)
	c.union = bts
	return err
}

// AsCombinedError_Merged_Issues_AnyOf_2 returns the union data inside the CombinedError_Merged_Issues_AnyOf as a CombinedError_Merged_Issues_AnyOf_2
func (c *CombinedError_Merged_Issues_AnyOf) AsCombinedError_Merged_Issues_AnyOf_2() (CombinedError_Merged_Issues_AnyOf_2, error) {
	return UnmarshalAs[CombinedError_Merged_Issues_AnyOf_2](c.union)
}

// FromCombinedError_Merged_Issues_AnyOf_2 overwrites any union data inside the CombinedError_Merged_Issues_AnyOf as the provided CombinedError_Merged_Issues_AnyOf_2
func (c *CombinedError_Merged_Issues_AnyOf) FromCombinedError_Merged_Issues_AnyOf_2(val CombinedError_Merged_Issues_AnyOf_2) error {
	bts, err := json.Marshal(val)
	c.union = bts
	return err
}

func (c CombinedError_Merged_Issues_AnyOf) MarshalJSON() ([]byte, error) {
	bts, err := c.union.MarshalJSON()

	return bts, err
}

func (c *CombinedError_Merged_Issues_AnyOf) UnmarshalJSON(bts []byte) error {
	err := c.union.UnmarshalJSON(bts)

	return err
}
