// Code generated by oapi-codegen. DO NOT EDIT.

package namingconflict2

import (
	"github.com/go-playground/validator/v10"
)

type SourceType string

const (
	SourceTypeACHCreditTransfer SourceType = "ach_credit_transfer"
	SourceTypeAlipay2           SourceType = "alipay"
)

type PaymentSourceType string

const (
	PaymentSourceTypeACHCreditTransfer PaymentSourceType = "ach_credit_transfer"
	PaymentSourceTypeAlipay            PaymentSourceType = "alipay"
)

var schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type Payment struct {
	Source *Payment_Source `json:"source,omitempty"`
}

func (p Payment) Validate() error {
	return schemaTypesValidate.Struct(p)
}

type Payment_Source struct {
	Type *PaymentSourceType `json:"type,omitempty"`
}

func (p Payment_Source) Validate() error {
	return schemaTypesValidate.Struct(p)
}

type Choice = SourceType

type SourceTypeAlipay struct {
	DataString          *string `json:"data_string,omitempty"`
	NativeURL           *string `json:"native_url,omitempty"`
	StatementDescriptor *string `json:"statement_descriptor,omitempty"`
}

func (s SourceTypeAlipay) Validate() error {
	return schemaTypesValidate.Struct(s)
}
