// Code generated by oapi-codegen. DO NOT EDIT.

package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/adaptor"
)

// ErrorKind represents the type of error that occurred during request processing.
type ErrorKind int

const (
	// ErrorKindParse indicates a parameter parsing error (invalid path/query/header parameter).
	ErrorKindParse ErrorKind = iota

	// ErrorKindDecode indicates a request body decoding error (invalid JSON, form data, etc.).
	ErrorKindDecode

	// ErrorKindValidation indicates a request validation error (failed schema validation).
	ErrorKindValidation

	// ErrorKindService indicates a service/business logic error returned by the service implementation.
	ErrorKindService
)

// ErrorContext provides context about an error that occurred during request processing.
type ErrorContext struct {
	// Kind indicates the type of error (parse, decode, validation, service).
	Kind ErrorKind

	// Err is the underlying error.
	Err error

	// ParamName is the name of the parameter that failed to parse (only set for ErrorKindParse).
	ParamName string

	// StatusCode is the suggested HTTP status code for the error.
	// For service errors, this may be determined by the error type (e.g., typed error responses).
	StatusCode int
}

// ErrorResponse is the default error response structure for parse, decode, and validation errors.
type ErrorResponse struct {
	Error string `json:"error"`
}

// ErrorHandler handles errors that occur during request processing.
// Implement this interface to customize error responses, logging, and metrics.
type ErrorHandler interface {
	// HandleError writes an error response. The ErrorContext provides details about the error.
	// Implementations should write the response status and body to w.
	HandleError(w http.ResponseWriter, r *http.Request, ctx ErrorContext)
}

// DefaultErrorHandler provides the default error handling behavior.
// It writes JSON error responses with appropriate status codes.
// Customize this implementation to add logging, metrics, or change the error format.
type DefaultErrorHandler struct{}

// HandleError implements ErrorHandler with default JSON error responses.
// It respects the Accept header: if the client accepts JSON, it returns JSON;
// otherwise, it returns plain text.
func (h *DefaultErrorHandler) HandleError(w http.ResponseWriter, r *http.Request, ctx ErrorContext) {
	// Check if client accepts JSON
	accept := r.Header.Get("Accept")
	wantsJSON := accept == "" || strings.Contains(accept, "application/json") || strings.Contains(accept, "*/*")

	if !wantsJSON {
		// Return plain text
		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
		w.WriteHeader(ctx.StatusCode)
		switch ctx.Kind {
		case ErrorKindParse:
			fmt.Fprintf(w, "invalid parameter %q: %v", ctx.ParamName, ctx.Err)
		case ErrorKindDecode, ErrorKindValidation, ErrorKindService:
			fmt.Fprint(w, ctx.Err.Error())
		}
		return
	}

	// Return JSON
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(ctx.StatusCode)
	switch ctx.Kind {
	case ErrorKindParse:
		_ = json.NewEncoder(w).Encode(ErrorResponse{
			Error: fmt.Sprintf("invalid parameter %q: %v", ctx.ParamName, ctx.Err),
		})
	case ErrorKindDecode, ErrorKindValidation:
		_ = json.NewEncoder(w).Encode(ErrorResponse{
			Error: ctx.Err.Error(),
		})
	case ErrorKindService:
		// Service errors are encoded directly - they may have custom structure
		_ = json.NewEncoder(w).Encode(ctx.Err)
	}
}

// ServiceInterface defines the service interface for business logic.
type ServiceInterface interface {
	// HealthCheck Health check endpoint
	HealthCheck(ctx context.Context) (*HealthCheckResponseData, error)
	// ListUsers List all users
	ListUsers(ctx context.Context, opts *ListUsersServiceRequestOptions) (*ListUsersResponseData, error)
	// CreateUser Create a new user
	CreateUser(ctx context.Context, opts *CreateUserServiceRequestOptions) (*CreateUserResponseData, error)
	// GetUser Get a user by ID
	GetUser(ctx context.Context, opts *GetUserServiceRequestOptions) (*GetUserResponseData, error)
	// DeleteUser Delete a user
	DeleteUser(ctx context.Context, opts *DeleteUserServiceRequestOptions) (*DeleteUserResponseData, error)
}

// HTTPAdapter adapts the ServiceInterface to HTTP handlers.
// This struct is generated and should not be modified.
type HTTPAdapter struct {
	svc        ServiceInterface
	errHandler ErrorHandler
}

// NewHTTPAdapter creates a new HTTPAdapter wrapping the given service.
// If errHandler is nil, DefaultErrorHandler is used.
func NewHTTPAdapter(svc ServiceInterface, errHandler ErrorHandler) *HTTPAdapter {
	if errHandler == nil {
		errHandler = &DefaultErrorHandler{}
	}
	return &HTTPAdapter{svc: svc, errHandler: errHandler}
}

// handleParseError handles parameter parsing errors using the error handler.
// Returns true if an error was handled (caller should return), false otherwise.
func (a *HTTPAdapter) handleParseError(w http.ResponseWriter, r *http.Request, paramName string, err error) bool {
	if err != nil {
		a.errHandler.HandleError(w, r, ErrorContext{
			Kind:       ErrorKindParse,
			Err:        err,
			ParamName:  paramName,
			StatusCode: http.StatusBadRequest,
		})
		return true
	}
	return false
}

// handleDecodeError handles request body decoding errors using the error handler.
func (a *HTTPAdapter) handleDecodeError(w http.ResponseWriter, r *http.Request, err error) {
	a.errHandler.HandleError(w, r, ErrorContext{
		Kind:       ErrorKindDecode,
		Err:        err,
		StatusCode: http.StatusBadRequest,
	})
}

// handleServiceError handles service/business logic errors using the error handler.
func (a *HTTPAdapter) handleServiceError(w http.ResponseWriter, r *http.Request, err error, code int) {
	a.errHandler.HandleError(w, r, ErrorContext{
		Kind:       ErrorKindService,
		Err:        err,
		StatusCode: code,
	})
}

// handleValidationError handles request validation errors using the error handler.
func (a *HTTPAdapter) handleValidationError(w http.ResponseWriter, r *http.Request, err error) {
	a.errHandler.HandleError(w, r, ErrorContext{
		Kind:       ErrorKindValidation,
		Err:        err,
		StatusCode: http.StatusBadRequest,
	})
}

// HTTP handler adapters - parse request, call interface, write response

// HealthCheck handles GET /health
func (a *HTTPAdapter) HealthCheck(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// Call business logic
	resp, err := a.svc.HealthCheck(ctx)
	if err != nil {
		code := http.StatusInternalServerError
		a.handleServiceError(w, r, err, code)
		return
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

// ListUsers handles GET /users
func (a *HTTPAdapter) ListUsers(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &ListUsersServiceRequestOptions{}
	opts.RawRequest = r

	// Parse query parameters
	queryParams := &ListUsersQuery{}
	query := r.URL.Query()
	if queryParamLimitStr := query.Get("limit"); queryParamLimitStr != "" {
		queryParamLimit, err := runtime.ParseString[int](queryParamLimitStr)
		if a.handleParseError(w, r, "limit", err) {
			return
		}
		queryParams.Limit = &queryParamLimit
	}
	opts.Query = queryParams

	// Call business logic
	resp, err := a.svc.ListUsers(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		a.handleServiceError(w, r, err, code)
		return
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

// CreateUser handles POST /users
func (a *HTTPAdapter) CreateUser(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &CreateUserServiceRequestOptions{}
	opts.RawRequest = r

	// Parse request body
	defer r.Body.Close()
	var body CreateUserBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		a.handleDecodeError(w, r, err)
		return
	}
	opts.Body = &body

	// Call business logic
	resp, err := a.svc.CreateUser(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		if _, ok := err.(*CreateUserErrorResponse); ok {
			code = 400
		}
		a.handleServiceError(w, r, err, code)
		return
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 201
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

// GetUser handles GET /users/{id}
func (a *HTTPAdapter) GetUser(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &GetUserServiceRequestOptions{}
	opts.RawRequest = r

	// Parse path parameters
	pathParams := &GetUserPath{}
	pathParamIDStr := r.PathValue("id")
	pathParams.ID = pathParamIDStr
	opts.PathParams = pathParams

	// Call business logic
	resp, err := a.svc.GetUser(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		a.handleServiceError(w, r, err, code)
		return
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

// DeleteUser handles DELETE /users/{id}
func (a *HTTPAdapter) DeleteUser(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &DeleteUserServiceRequestOptions{}
	opts.RawRequest = r

	// Parse path parameters
	pathParams := &DeleteUserPath{}
	pathParamIDStr := r.PathValue("id")
	pathParams.ID = pathParamIDStr
	opts.PathParams = pathParams

	// Call business logic
	resp, err := a.svc.DeleteUser(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		a.handleServiceError(w, r, err, code)
		return
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 204
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.WriteHeader(status)
}

// RouterOption is a function that configures the router.
type RouterOption func(*routerConfig)

type routerConfig struct {
	middlewares []app.HandlerFunc
	errHandler  ErrorHandler
}

// WithMiddleware adds middleware to the router.
func WithMiddleware(mw app.HandlerFunc) RouterOption {
	return func(cfg *routerConfig) {
		cfg.middlewares = append(cfg.middlewares, mw)
	}
}

// WithErrorHandler sets a custom error handler for the router.
// If not set, DefaultErrorHandler is used.
func WithErrorHandler(h ErrorHandler) RouterOption {
	return func(cfg *routerConfig) {
		cfg.errHandler = h
	}
}

// NewRouter registers routes on the given Hertz server with the service implementation.
func NewRouter(h *server.Hertz, svc ServiceInterface, opts ...RouterOption) {
	cfg := &routerConfig{}
	for _, opt := range opts {
		opt(cfg)
	}

	adapter := NewHTTPAdapter(svc, cfg.errHandler)

	// Apply middleware to all routes
	for _, mw := range cfg.middlewares {
		h.Use(mw)
	}
	h.Handle("GET", "/health", func(ctx context.Context, c *app.RequestContext) {
		req, err := adaptor.GetCompatRequest(&c.Request)
		if err != nil {
			c.String(500, "failed to get compat request: %v", err)
			return
		}
		rw := adaptor.GetCompatResponseWriter(&c.Response)
		adapter.HealthCheck(rw, req)
	})
	h.Handle("GET", "/users", func(ctx context.Context, c *app.RequestContext) {
		req, err := adaptor.GetCompatRequest(&c.Request)
		if err != nil {
			c.String(500, "failed to get compat request: %v", err)
			return
		}
		rw := adaptor.GetCompatResponseWriter(&c.Response)
		adapter.ListUsers(rw, req)
	})
	h.Handle("POST", "/users", func(ctx context.Context, c *app.RequestContext) {
		req, err := adaptor.GetCompatRequest(&c.Request)
		if err != nil {
			c.String(500, "failed to get compat request: %v", err)
			return
		}
		rw := adaptor.GetCompatResponseWriter(&c.Response)
		adapter.CreateUser(rw, req)
	})
	h.Handle("GET", "/users/{id}", func(ctx context.Context, c *app.RequestContext) {
		req, err := adaptor.GetCompatRequest(&c.Request)
		if err != nil {
			c.String(500, "failed to get compat request: %v", err)
			return
		}
		// Copy path params to request for http.Handler compatibility
		req.SetPathValue("id", c.Param("id"))
		rw := adaptor.GetCompatResponseWriter(&c.Response)
		adapter.GetUser(rw, req)
	})
	h.Handle("DELETE", "/users/{id}", func(ctx context.Context, c *app.RequestContext) {
		req, err := adaptor.GetCompatRequest(&c.Request)
		if err != nil {
			c.String(500, "failed to get compat request: %v", err)
			return
		}
		// Copy path params to request for http.Handler compatibility
		req.SetPathValue("id", c.Param("id"))
		rw := adaptor.GetCompatResponseWriter(&c.Response)
		adapter.DeleteUser(rw, req)
	})
}

// Handler returns an http.Handler for use with net/http or testing.
// This provides a standard http.Handler interface without requiring a Hertz server.
func Handler(svc ServiceInterface, opts ...RouterOption) http.Handler {
	cfg := &routerConfig{}
	for _, opt := range opts {
		opt(cfg)
	}

	adapter := NewHTTPAdapter(svc, cfg.errHandler)
	mux := http.NewServeMux()
	mux.HandleFunc("GET /health", adapter.HealthCheck)
	mux.HandleFunc("GET /users", adapter.ListUsers)
	mux.HandleFunc("POST /users", adapter.CreateUser)
	mux.HandleFunc("GET /users/{id}", adapter.GetUser)
	mux.HandleFunc("DELETE /users/{id}", adapter.DeleteUser)

	return mux
}

type GetUserPath struct {
	ID string `json:"id" validate:"required"`
}

func (g GetUserPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type DeleteUserPath struct {
	ID string `json:"id" validate:"required"`
}

func (d DeleteUserPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(d))
}

type CreateUserBody = CreateUserRequest

type ListUsersQuery struct {
	Limit *int `json:"limit,omitempty"`
}

// HealthCheckResponseData wraps the success response with optional headers and status override.
type HealthCheckResponseData struct {
	Body    *HealthCheckResponse
	Headers http.Header
	Status  int // 0 = use default (200)
}

// NewHealthCheckResponseData creates a new HealthCheckResponseData with the given body.
func NewHealthCheckResponseData(body *HealthCheckResponse) *HealthCheckResponseData {
	return &HealthCheckResponseData{Body: body}
}

// WithHeaders sets custom headers on the response.
func (r *HealthCheckResponseData) WithHeaders(h http.Header) *HealthCheckResponseData {
	r.Headers = h
	return r
}

// WithStatus overrides the default status code.
func (r *HealthCheckResponseData) WithStatus(code int) *HealthCheckResponseData {
	r.Status = code
	return r
}

// ListUsersResponseData wraps the success response with optional headers and status override.
type ListUsersResponseData struct {
	Body    *ListUsersResponse
	Headers http.Header
	Status  int // 0 = use default (200)
}

// NewListUsersResponseData creates a new ListUsersResponseData with the given body.
func NewListUsersResponseData(body *ListUsersResponse) *ListUsersResponseData {
	return &ListUsersResponseData{Body: body}
}

// WithHeaders sets custom headers on the response.
func (r *ListUsersResponseData) WithHeaders(h http.Header) *ListUsersResponseData {
	r.Headers = h
	return r
}

// WithStatus overrides the default status code.
func (r *ListUsersResponseData) WithStatus(code int) *ListUsersResponseData {
	r.Status = code
	return r
}

// CreateUserResponseData wraps the success response with optional headers and status override.
type CreateUserResponseData struct {
	Body    *CreateUserResponse
	Headers http.Header
	Status  int // 0 = use default (201)
}

// NewCreateUserResponseData creates a new CreateUserResponseData with the given body.
func NewCreateUserResponseData(body *CreateUserResponse) *CreateUserResponseData {
	return &CreateUserResponseData{Body: body}
}

// WithHeaders sets custom headers on the response.
func (r *CreateUserResponseData) WithHeaders(h http.Header) *CreateUserResponseData {
	r.Headers = h
	return r
}

// WithStatus overrides the default status code.
func (r *CreateUserResponseData) WithStatus(code int) *CreateUserResponseData {
	r.Status = code
	return r
}

// GetUserResponseData wraps the success response with optional headers and status override.
type GetUserResponseData struct {
	Body    *GetUserResponse
	Headers http.Header
	Status  int // 0 = use default (200)
}

// NewGetUserResponseData creates a new GetUserResponseData with the given body.
func NewGetUserResponseData(body *GetUserResponse) *GetUserResponseData {
	return &GetUserResponseData{Body: body}
}

// WithHeaders sets custom headers on the response.
func (r *GetUserResponseData) WithHeaders(h http.Header) *GetUserResponseData {
	r.Headers = h
	return r
}

// WithStatus overrides the default status code.
func (r *GetUserResponseData) WithStatus(code int) *GetUserResponseData {
	r.Status = code
	return r
}

// DeleteUserResponseData wraps the success response with optional headers and status override.
type DeleteUserResponseData struct {
	Body    *struct{}
	Headers http.Header
	Status  int // 0 = use default (204)
}

// NewDeleteUserResponseData creates a new DeleteUserResponseData with the given body.
func NewDeleteUserResponseData(body *struct{}) *DeleteUserResponseData {
	return &DeleteUserResponseData{Body: body}
}

// WithHeaders sets custom headers on the response.
func (r *DeleteUserResponseData) WithHeaders(h http.Header) *DeleteUserResponseData {
	r.Headers = h
	return r
}

// WithStatus overrides the default status code.
func (r *DeleteUserResponseData) WithStatus(code int) *DeleteUserResponseData {
	r.Status = code
	return r
}

type HealthCheckResponse = HealthStatus

type ListUsersResponse []User

type CreateUserResponse = User

type CreateUserErrorResponse struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

func (r CreateUserErrorResponse) Error() string {
	res0 := r.Message
	if res0 == nil {
		return "unknown error"
	}
	res1 := *res0
	return res1
}

func NewCreateUserErrorResponse(message string) CreateUserErrorResponse {
	return CreateUserErrorResponse{Message: runtime.Ptr(message)}
}

type GetUserResponse = User

type GetUserErrorResponse = Error

// ListUsersServiceRequestOptions holds all parameters for the ListUsers operation.
type ListUsersServiceRequestOptions struct {
	Query *ListUsersQuery
	// RawRequest provides access to the underlying HTTP request for custom content type handling.
	RawRequest *http.Request
}

// Validate validates all the fields in the options.
func (o *ListUsersServiceRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.Query != nil {
		if v, ok := any(o.Query).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Query", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// CreateUserServiceRequestOptions holds all parameters for the CreateUser operation.
type CreateUserServiceRequestOptions struct {
	Body *CreateUserBody
	// RawRequest provides access to the underlying HTTP request for custom content type handling.
	RawRequest *http.Request
}

// Validate validates all the fields in the options.
func (o *CreateUserServiceRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.Body != nil {
		if v, ok := any(o.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Body", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetUserServiceRequestOptions holds all parameters for the GetUser operation.
type GetUserServiceRequestOptions struct {
	PathParams *GetUserPath
	// RawRequest provides access to the underlying HTTP request for custom content type handling.
	RawRequest *http.Request
}

// Validate validates all the fields in the options.
func (o *GetUserServiceRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// DeleteUserServiceRequestOptions holds all parameters for the DeleteUser operation.
type DeleteUserServiceRequestOptions struct {
	PathParams *DeleteUserPath
	// RawRequest provides access to the underlying HTTP request for custom content type handling.
	RawRequest *http.Request
}

// Validate validates all the fields in the options.
func (o *DeleteUserServiceRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

type HealthStatus struct {
	Status string `json:"status" validate:"required"`
}

func (h HealthStatus) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(h))
}

type User struct {
	ID    string `json:"id" validate:"required"`
	Name  string `json:"name" validate:"required"`
	Email string `json:"email" validate:"required"`
}

func (u User) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(u))
}

type CreateUserRequest struct {
	Name  string `json:"name" validate:"required"`
	Email string `json:"email" validate:"required"`
}

func (c CreateUserRequest) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(c))
}

type Error struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

func (s Error) Error() string {
	return "unmapped client error"
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
