// Code generated by oapi-codegen. DO NOT EDIT.
package api

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
)

// OapiErrorKind represents the type of error that occurred during request processing.
type OapiErrorKind int

const (
	// OapiErrorKindParse indicates a parameter parsing error (invalid path/query/header parameter).
	OapiErrorKindParse OapiErrorKind = iota

	// OapiErrorKindDecode indicates a request body decoding error (invalid JSON, form data, etc.).
	OapiErrorKindDecode

	// OapiErrorKindValidation indicates a request validation error (failed schema validation).
	OapiErrorKindValidation

	// OapiErrorKindService indicates a service/business logic error returned by the service implementation.
	OapiErrorKindService
)

// OapiErrorContext provides context about an error that occurred during request processing.
type OapiErrorContext struct {
	// Kind indicates the type of error (parse, decode, validation, service).
	Kind OapiErrorKind

	// Err is the underlying error.
	Err error

	// ParamName is the name of the parameter that failed to parse (only set for OapiErrorKindParse).
	ParamName string

	// StatusCode is the suggested HTTP status code for the error.
	// For service errors, this may be determined by the error type (e.g., typed error responses).
	StatusCode int
}

// OapiErrorResponse is the default error response structure for parse, decode, and validation errors.
type OapiErrorResponse struct {
	Error string `json:"error"`
}

// OapiErrorHandler handles errors that occur during request processing.
// Implement this interface to customize error responses, logging, and metrics.
type OapiErrorHandler interface {
	// HandleError writes an error response. The OapiErrorContext provides details about the error.
	// Implementations should write the response status and body to w.
	HandleError(w http.ResponseWriter, r *http.Request, ctx OapiErrorContext)
}

// OapiDefaultErrorHandler provides the default error handling behavior.
// It writes JSON error responses with appropriate status codes.
// Customize this implementation to add logging, metrics, or change the error format.
type OapiDefaultErrorHandler struct{}

// HandleError implements OapiErrorHandler with default JSON error responses.
// It respects the Accept header: if the client accepts JSON, it returns JSON;
// otherwise, it returns plain text.
func (h *OapiDefaultErrorHandler) HandleError(w http.ResponseWriter, r *http.Request, ctx OapiErrorContext) {
	// Check if client accepts JSON
	accept := r.Header.Get("Accept")
	wantsJSON := accept == "" || strings.Contains(accept, "application/json") || strings.Contains(accept, "*/*")

	if !wantsJSON {
		// Return plain text
		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
		w.WriteHeader(ctx.StatusCode)
		switch ctx.Kind {
		case OapiErrorKindParse:
			fmt.Fprintf(w, "invalid parameter %q: %v", ctx.ParamName, ctx.Err)
		case OapiErrorKindDecode, OapiErrorKindValidation, OapiErrorKindService:
			fmt.Fprint(w, ctx.Err.Error())
		}
		return
	}

	// Return JSON
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(ctx.StatusCode)
	switch ctx.Kind {
	case OapiErrorKindParse:
		_ = json.NewEncoder(w).Encode(OapiErrorResponse{
			Error: fmt.Sprintf("invalid parameter %q: %v", ctx.ParamName, ctx.Err),
		})
	case OapiErrorKindDecode, OapiErrorKindValidation:
		_ = json.NewEncoder(w).Encode(OapiErrorResponse{
			Error: ctx.Err.Error(),
		})
	case OapiErrorKindService:
		// Service errors are encoded directly - they may have custom structure
		_ = json.NewEncoder(w).Encode(ctx.Err)
	}
}
