// Code generated by oapi-codegen. DO NOT EDIT.

package types

import (
	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

type GetUserPath struct {
	ID string `json:"id" validate:"required"`
}

func (g GetUserPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type DeleteUserPath struct {
	ID string `json:"id" validate:"required"`
}

func (d DeleteUserPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(d))
}

type GetUserAvatarPath struct {
	ID string `json:"id" validate:"required"`
}

func (g GetUserAvatarPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type UploadUserAvatarPath struct {
	ID string `json:"id" validate:"required"`
}

func (u UploadUserAvatarPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(u))
}

type GetItemsByTypePath struct {
	Type string `json:"type" validate:"required"`
}

func (g GetItemsByTypePath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type GetCategoryPath struct {
	CategoryID int `json:"categoryId" validate:"required"`
}

func (g GetCategoryPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type GetItemsByStatusPath struct {
	Type   string  `json:"type" validate:"required"`
	Rating float32 `json:"rating" validate:"required"`
}

func (g GetItemsByStatusPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type GetUserPostPath struct {
	ID     string `json:"id" validate:"required"`
	PostID string `json:"postId" validate:"required"`
}

func (g GetUserPostPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}
