// Code generated by oapi-codegen. DO NOT EDIT.

package types

import (
	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

type ListUsersQuery struct {
	Limit *int `json:"limit,omitempty"`
}

type SearchQuery struct {
	Q string `json:"q" validate:"required"`
}

func (s SearchQuery) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(s))
}

type ListProductsQuery struct {
	// Ids Filter by product IDs (string array)
	Ids []string `json:"ids,omitempty"`

	// Tags Filter by tags (string array)
	Tags []string `json:"tags,omitempty"`

	// CategoryIds Filter by category IDs (integer array)
	CategoryIds []int `json:"categoryIds,omitempty"`

	// MinPrice Minimum price (number/float)
	MinPrice *float32 `json:"minPrice,omitempty"`

	// Active Filter by active status (boolean)
	Active *bool `json:"active,omitempty"`
}
