// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

var pathTypesValidate *validator.Validate

func init() {
	pathTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(pathTypesValidate)
}

type PostBillingPortalConfigurationsConfigurationPath struct {
	Configuration string `json:"configuration" validate:"required"`
}

func (p PostBillingPortalConfigurationsConfigurationPath) Validate() error {
	return pathTypesValidate.Struct(p)
}

var bodyTypesValidate *validator.Validate

func init() {
	bodyTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(bodyTypesValidate)
}

type PostUsersBody = User

var responseTypesValidate *validator.Validate

func init() {
	responseTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(responseTypesValidate)
}

type PostUsersResponse struct {
	Name string `json:"name" validate:"required"`

	// Active Whether the user is active
	Active bool `json:"active"`

	// Verified Optional boolean field
	Verified *bool `json:"verified,omitempty"`
}

func (p PostUsersResponse) Validate() error {
	return responseTypesValidate.Struct(p)
}

type PostBillingPortalConfigurationsConfigurationResponse struct {
	Features PortalFeatures `json:"features" validate:"required"`
}

func (p PostBillingPortalConfigurationsConfigurationResponse) Validate() error {
	if v, ok := any(p.Features).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			return runtime.NewValidationErrorFromError("Features", err)
		}
	}
	return nil
}

var schemaTypesValidate *validator.Validate

func init() {
	schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(schemaTypesValidate)
}

type User struct {
	Name string `json:"name" validate:"required"`

	// Active Whether the user is active
	Active bool `json:"active"`

	// Verified Optional boolean field
	Verified *bool `json:"verified,omitempty"`
}

func (u User) Validate() error {
	return schemaTypesValidate.Struct(u)
}

type PortalFeatures struct {
	InvoiceHistory PortalInvoiceList `json:"invoice_history" validate:"required"`
}

func (p PortalFeatures) Validate() error {
	if v, ok := any(p.InvoiceHistory).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			return runtime.NewValidationErrorFromError("InvoiceHistory", err)
		}
	}
	return nil
}

type PortalInvoiceList struct {
	// Enabled Whether invoice history is enabled
	Enabled bool `json:"enabled"`
}

func (p PortalInvoiceList) Validate() error {
	return schemaTypesValidate.Struct(p)
}
