// Code generated by oapi-codegen. DO NOT EDIT.

package multiple

import (
	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
	"github.com/google/uuid"
)

var schemaTypesValidate *validator.Validate

func init() {
	schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(schemaTypesValidate)
}

type LinksSelf struct {
	Self *string `json:"self,omitempty"`
}

func (l LinksSelf) Validate() error {
	return schemaTypesValidate.Struct(l)
}

type Problem struct {
	Type     *string `json:"type,omitempty"`
	Title    *string `json:"title,omitempty"`
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   *int    `json:"status,omitempty"`
}

func (p Problem) Validate() error {
	return schemaTypesValidate.Struct(p)
}

type Booking struct {
	ID            *uuid.UUID `json:"id,omitempty"`
	TripID        *uuid.UUID `json:"trip_id,omitempty"`
	PassengerName *string    `json:"passenger_name,omitempty"`
	HasBicycle    *bool      `json:"has_bicycle,omitempty"`
	HasDog        *bool      `json:"has_dog,omitempty"`
}

func (b Booking) Validate() error {
	if b.ID != nil {
		if v, ok := any(b.ID).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("ID", err)
			}
		}
	}
	if b.TripID != nil {
		if v, ok := any(b.TripID).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("TripID", err)
			}
		}
	}
	return nil
}
