// Code generated by oapi-codegen. DO NOT EDIT.

package streaming

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
	"github.com/google/uuid"
)

// Client is the client for the API implementing the Client interface.
type Client struct {
	apiClient runtime.APIClient
}

// NewClient creates a new instance of the Client client.
func NewClient(apiClient runtime.APIClient) *Client {
	return &Client{apiClient: apiClient}
}

// NewDefaultClient creates a new instance of the Client client with default api client.
func NewDefaultClient(baseURL string, opts ...runtime.APIClientOption) (*Client, error) {
	apiClient, err := runtime.NewAPIClient(baseURL, opts...)
	if err != nil {
		return nil, fmt.Errorf("error creating API client: %w", err)
	}
	return &Client{apiClient: apiClient}, nil
}

// ClientInterface is the interface for the API client.
type ClientInterface interface {
	// Chat Answer with one document, or stream chunks when asked to
	Chat(ctx context.Context, options *ChatRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ChatResponse, error)
	ChatWithResponse(ctx context.Context, options *ChatRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ChatResp, error)
	ChatStream(ctx context.Context, options *ChatRequestOptions, reqEditors ...runtime.RequestEditorFn) (*runtime.Stream[Chunk], error)
	ChatStreamWithResponse(ctx context.Context, options *ChatRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ChatResp, error)

	// GetEvents Subscribe to an endless Server-Sent Events stream
	GetEvents(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*GetEventsResponse, error)
	GetEventsWithResponse(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*GetEventsResp, error)
	GetEventsStream(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*runtime.Stream[Event], error)
	GetEventsStreamWithResponse(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*GetEventsResp, error)

	// StreamLogs Tail newline-delimited log records
	StreamLogs(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*StreamLogsResponse, error)
	StreamLogsWithResponse(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*StreamLogsResp, error)
	StreamLogsStream(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*runtime.Stream[StreamLogsResponseItem], error)
	StreamLogsStreamWithResponse(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*StreamLogsResp, error)
}

// Chat Answer with one document, or stream chunks when asked to
func (c *Client) Chat(ctx context.Context, options *ChatRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ChatResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL:  c.apiClient.GetBaseURL() + "/chat",
		Method:      "POST",
		Options:     options,
		ContentType: "application/json",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*ChatResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			return nil, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(ChatResponse)
		// Handle empty response body gracefully
		if len(bodyBytes) == 0 {
			return target, nil
		}
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			return nil, &runtime.ResponseDecodeError{
				StatusCode:    resp.StatusCode,
				ContentType:   resp.Headers.Get("Content-Type"),
				ContentLength: len(bodyBytes),
				TargetType:    "ChatResponse",
				Body:          bodyBytes,
				Err:           err,
			}
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/chat")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// GetEvents Subscribe to an endless Server-Sent Events stream
func (c *Client) GetEvents(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*GetEventsResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/events",
		Method:     "GET",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*GetEventsResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(GetEventsErrorResponse)
			// Handle empty error response body gracefully - skip unmarshal if no content
			if len(bodyBytes) > 0 {
				if err = json.Unmarshal(bodyBytes, target); err != nil {
					return nil, &runtime.ResponseDecodeError{
						StatusCode:    resp.StatusCode,
						ContentType:   resp.Headers.Get("Content-Type"),
						ContentLength: len(bodyBytes),
						TargetType:    "GetEventsErrorResponse",
						Body:          bodyBytes,
						Err:           err,
					}
				}
			}
			// Return error with (possibly empty) target
			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		result := GetEventsResponse(bodyBytes)
		return &result, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/events")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// StreamLogs Tail newline-delimited log records
func (c *Client) StreamLogs(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*StreamLogsResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/logs",
		Method:     "GET",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*StreamLogsResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			return nil, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode),
				runtime.WithStatusCode(resp.StatusCode))
		}
		result := StreamLogsResponse(bodyBytes)
		return &result, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/logs")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

var _ ClientInterface = (*Client)(nil)

// ChatRequestOptions is the options needed to make a request to Chat.
type ChatRequestOptions struct {
	Body *ChatBody
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *ChatRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.Body != nil {
		if v, ok := any(o.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Body", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *ChatRequestOptions) GetPathParams() (map[string]any, error) {
	return nil, nil
}

// GetQuery returns the query params as a map.
func (o *ChatRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *ChatRequestOptions) GetBody() any {
	return o.Body
}

// GetHeader returns the headers as a map.
func (o *ChatRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// ChatStream consumes the text/event-stream response of
// Chat as a live stream. The body is never buffered, so this works against
// an endless stream. The caller must Close the returned stream.
func (c *Client) ChatStream(ctx context.Context, options *ChatRequestOptions, reqEditors ...runtime.RequestEditorFn) (*runtime.Stream[Chunk], error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL:  c.apiClient.GetBaseURL() + "/chat",
		Method:      "POST",
		Stream:      "text/event-stream",
		Options:     options,
		ContentType: "application/json",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/chat")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}

	if resp.StatusCode != 200 {

		if resp.Raw != nil && resp.Raw.Body != nil {
			_ = resp.Raw.Body.Close()
		}
		return nil, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode),
			runtime.WithStatusCode(resp.StatusCode))
	}

	// Buffered at the streaming status means the server answered with another
	// content type. Say so rather than return a stream that yields nothing.
	if !resp.Streaming {
		return nil, runtime.NewClientAPIError(
			fmt.Errorf("expected a text/event-stream stream, got Content-Type %q", resp.Headers.Get("Content-Type")),
			runtime.WithStatusCode(resp.StatusCode))
	}

	return runtime.NewEventStream[Chunk](resp.Raw), nil
}

// ChatStreamWithResponse is the envelope form: it populates
// Stream200 instead of the buffered body field.
func (c *Client) ChatStreamWithResponse(ctx context.Context, options *ChatRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ChatResp, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL:  c.apiClient.GetBaseURL() + "/chat",
		Method:      "POST",
		Stream:      "text/event-stream",
		Options:     options,
		ContentType: "application/json",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/chat")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}

	out := &ChatResp{
		HTTPResponse: resp.Raw,
		Body:         resp.Content,
		StatusCode:   resp.StatusCode,
	}

	switch resp.StatusCode {
	case 200:
		if !resp.Streaming {
			return out, runtime.NewClientAPIError(
				fmt.Errorf("expected a text/event-stream stream, got Content-Type %q", resp.Headers.Get("Content-Type")),
				runtime.WithStatusCode(resp.StatusCode))
		}
		out.Stream200 = runtime.NewEventStream[Chunk](resp.Raw)
		return out, nil
	default:

		if resp.Raw != nil && resp.Raw.Body != nil {
			_ = resp.Raw.Body.Close()
		}
		return out, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode), runtime.WithStatusCode(resp.StatusCode))
	}
}

// GetEventsStream consumes the text/event-stream response of
// GetEvents as a live stream. The body is never buffered, so this works against
// an endless stream. The caller must Close the returned stream.
func (c *Client) GetEventsStream(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*runtime.Stream[Event], error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/events",
		Method:     "GET",
		Stream:     "text/event-stream",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/events")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}

	if resp.StatusCode != 200 {

		if resp.Raw != nil && resp.Raw.Body != nil {
			_ = resp.Raw.Body.Close()
		}
		target := new(GetEventsErrorResponse)
		if len(resp.Content) > 0 {
			if err = json.Unmarshal(resp.Content, target); err != nil {
				return nil, &runtime.ResponseDecodeError{
					StatusCode:    resp.StatusCode,
					ContentType:   resp.Headers.Get("Content-Type"),
					ContentLength: len(resp.Content),
					TargetType:    "GetEventsErrorResponse",
					Body:          resp.Content,
					Err:           err,
				}
			}
		}
		if errTarget, ok := any(*target).(error); ok {
			return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
		}
		return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
			runtime.WithStatusCode(resp.StatusCode))
	}

	// Buffered at the streaming status means the server answered with another
	// content type. Say so rather than return a stream that yields nothing.
	if !resp.Streaming {
		return nil, runtime.NewClientAPIError(
			fmt.Errorf("expected a text/event-stream stream, got Content-Type %q", resp.Headers.Get("Content-Type")),
			runtime.WithStatusCode(resp.StatusCode))
	}

	return runtime.NewEventStream[Event](resp.Raw), nil
}

// GetEventsStreamWithResponse is the envelope form: it populates
// Stream200 instead of the buffered body field.
func (c *Client) GetEventsStreamWithResponse(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*GetEventsResp, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/events",
		Method:     "GET",
		Stream:     "text/event-stream",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/events")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}

	out := &GetEventsResp{
		HTTPResponse: resp.Raw,
		Body:         resp.Content,
		StatusCode:   resp.StatusCode,
	}

	switch resp.StatusCode {
	case 200:
		if !resp.Streaming {
			return out, runtime.NewClientAPIError(
				fmt.Errorf("expected a text/event-stream stream, got Content-Type %q", resp.Headers.Get("Content-Type")),
				runtime.WithStatusCode(resp.StatusCode))
		}
		out.Stream200 = runtime.NewEventStream[Event](resp.Raw)
		return out, nil
	case 500:
		out.JSON500 = new(GetEventsErrorResponse)
		bodyBytes := resp.Content
		if len(bodyBytes) > 0 {
			if err := json.Unmarshal(bodyBytes, out.JSON500); err != nil {
				return out, &runtime.ResponseDecodeError{
					StatusCode:    resp.StatusCode,
					ContentType:   resp.Headers.Get("Content-Type"),
					ContentLength: len(bodyBytes),
					TargetType:    "GetEventsErrorResponse",
					Body:          bodyBytes,
					Err:           err,
				}
			}
		}
		return out, runtime.NewClientAPIError(fmt.Errorf("API error (status %d)", resp.StatusCode), runtime.WithStatusCode(resp.StatusCode))
	default:

		if resp.Raw != nil && resp.Raw.Body != nil {
			_ = resp.Raw.Body.Close()
		}
		return out, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode), runtime.WithStatusCode(resp.StatusCode))
	}
}

// StreamLogsStream consumes the application/x-ndjson response of
// StreamLogs as a live stream. The body is never buffered, so this works against
// an endless stream. The caller must Close the returned stream.
func (c *Client) StreamLogsStream(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*runtime.Stream[StreamLogsResponseItem], error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/logs",
		Method:     "GET",
		Stream:     "application/x-ndjson",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/logs")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}

	if resp.StatusCode != 200 {

		if resp.Raw != nil && resp.Raw.Body != nil {
			_ = resp.Raw.Body.Close()
		}
		return nil, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode),
			runtime.WithStatusCode(resp.StatusCode))
	}

	// Buffered at the streaming status means the server answered with another
	// content type. Say so rather than return a stream that yields nothing.
	if !resp.Streaming {
		return nil, runtime.NewClientAPIError(
			fmt.Errorf("expected a application/x-ndjson stream, got Content-Type %q", resp.Headers.Get("Content-Type")),
			runtime.WithStatusCode(resp.StatusCode))
	}

	return runtime.NewLineStream[StreamLogsResponseItem](resp.Raw), nil
}

// StreamLogsStreamWithResponse is the envelope form: it populates
// Stream200 instead of the buffered body field.
func (c *Client) StreamLogsStreamWithResponse(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*StreamLogsResp, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/logs",
		Method:     "GET",
		Stream:     "application/x-ndjson",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/logs")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}

	out := &StreamLogsResp{
		HTTPResponse: resp.Raw,
		Body:         resp.Content,
		StatusCode:   resp.StatusCode,
	}

	switch resp.StatusCode {
	case 200:
		if !resp.Streaming {
			return out, runtime.NewClientAPIError(
				fmt.Errorf("expected a application/x-ndjson stream, got Content-Type %q", resp.Headers.Get("Content-Type")),
				runtime.WithStatusCode(resp.StatusCode))
		}
		out.Stream200 = runtime.NewLineStream[StreamLogsResponseItem](resp.Raw)
		return out, nil
	default:

		if resp.Raw != nil && resp.Raw.Body != nil {
			_ = resp.Raw.Body.Close()
		}
		return out, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode), runtime.WithStatusCode(resp.StatusCode))
	}
}

// Chat Answer with one document, or stream chunks when asked to
func (c *Client) ChatWithResponse(ctx context.Context, options *ChatRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ChatResp, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL:  c.apiClient.GetBaseURL() + "/chat",
		Method:      "POST",
		Options:     options,
		ContentType: "application/json",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/chat")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}

	out := &ChatResp{
		HTTPResponse: resp.Raw,
		Body:         resp.Content,
		StatusCode:   resp.StatusCode,
	}

	switch resp.StatusCode {
	case 200:
		out.JSON200 = new(ChatResponse)
		bodyBytes := resp.Content
		if len(bodyBytes) > 0 {
			if err := json.Unmarshal(bodyBytes, out.JSON200); err != nil {
				return out, &runtime.ResponseDecodeError{
					StatusCode:    resp.StatusCode,
					ContentType:   resp.Headers.Get("Content-Type"),
					ContentLength: len(bodyBytes),
					TargetType:    "ChatResponse",
					Body:          bodyBytes,
					Err:           err,
				}
			}
		}
		return out, nil
	default:
		return out, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode), runtime.WithStatusCode(resp.StatusCode))
	}
}

// GetEvents Subscribe to an endless Server-Sent Events stream
func (c *Client) GetEventsWithResponse(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*GetEventsResp, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/events",
		Method:     "GET",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/events")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}

	out := &GetEventsResp{
		HTTPResponse: resp.Raw,
		Body:         resp.Content,
		StatusCode:   resp.StatusCode,
	}

	switch resp.StatusCode {
	case 200:
		return out, nil
	case 500:
		out.JSON500 = new(GetEventsErrorResponse)
		bodyBytes := resp.Content
		if len(bodyBytes) > 0 {
			if err := json.Unmarshal(bodyBytes, out.JSON500); err != nil {
				return out, &runtime.ResponseDecodeError{
					StatusCode:    resp.StatusCode,
					ContentType:   resp.Headers.Get("Content-Type"),
					ContentLength: len(bodyBytes),
					TargetType:    "GetEventsErrorResponse",
					Body:          bodyBytes,
					Err:           err,
				}
			}
		}
		return out, runtime.NewClientAPIError(fmt.Errorf("API error (status %d)", resp.StatusCode), runtime.WithStatusCode(resp.StatusCode))
	default:
		return out, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode), runtime.WithStatusCode(resp.StatusCode))
	}
}

// StreamLogs Tail newline-delimited log records
func (c *Client) StreamLogsWithResponse(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*StreamLogsResp, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/logs",
		Method:     "GET",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/logs")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}

	out := &StreamLogsResp{
		HTTPResponse: resp.Raw,
		Body:         resp.Content,
		StatusCode:   resp.StatusCode,
	}

	switch resp.StatusCode {
	case 200:
		return out, nil
	default:
		return out, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode), runtime.WithStatusCode(resp.StatusCode))
	}
}

type ChunkFinishReason string

const (
	ContentFilter ChunkFinishReason = "content_filter"
	Length        ChunkFinishReason = "length"
	Stop          ChunkFinishReason = "stop"
)

// Validate checks if the ChunkFinishReason value is valid
func (c ChunkFinishReason) Validate() error {
	switch c {
	case ContentFilter, Length, Stop:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid ChunkFinishReason value, got: %v", c))
	}
}

type EventType string

const (
	Created EventType = "created"
	Deleted EventType = "deleted"
	Updated EventType = "updated"
)

// Validate checks if the EventType value is valid
func (e EventType) Validate() error {
	switch e {
	case Created, Deleted, Updated:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid EventType value, got: %v", e))
	}
}

type StreamLogsResponseLevel string

const (
	Debug StreamLogsResponseLevel = "debug"
	Error StreamLogsResponseLevel = "error"
	Info  StreamLogsResponseLevel = "info"
	Warn  StreamLogsResponseLevel = "warn"
)

// Validate checks if the StreamLogsResponseLevel value is valid
func (s StreamLogsResponseLevel) Validate() error {
	switch s {
	case Debug, Error, Info, Warn:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid StreamLogsResponseLevel value, got: %v", s))
	}
}

type ChatBody struct {
	Prompt string `json:"prompt" validate:"required"`
	Stream *bool  `json:"stream,omitempty"`
}

func (c ChatBody) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(c))
}

type ChatResponse = Completion

type GetEventsResponse = []byte

type GetEventsErrorResponse = ServiceError

type StreamLogsResponse = []byte

type StreamLogsResponseItem struct {
	Level   StreamLogsResponseLevel     `json:"level" validate:"required"`
	Message string                      `json:"message" validate:"required"`
	At      time.Time                   `json:"at" validate:"required"`
	Source  *StreamLogs_Response_Source `json:"source,omitempty"`
}

type ChatResp struct {
	HTTPResponse *http.Response
	Body         []byte
	StatusCode   int
	JSON200      *ChatResponse
	Stream200    *runtime.Stream[Chunk]
}

type GetEventsResp struct {
	HTTPResponse *http.Response
	Body         []byte
	StatusCode   int
	Stream200    *runtime.Stream[Event]
	JSON500      *GetEventsErrorResponse
}

type StreamLogsResp struct {
	HTTPResponse *http.Response
	Body         []byte
	StatusCode   int
	Stream200    *runtime.Stream[StreamLogsResponseItem]
}

type Completion struct {
	ID    string `json:"id" validate:"required"`
	Text  string `json:"text" validate:"required"`
	Usage Usage  `json:"usage"`
}

func (c Completion) Validate() error {
	var errors runtime.ValidationErrors
	if err := typesValidator.Var(c.ID, "required"); err != nil {
		errors = errors.Append("ID", err)
	}
	if err := typesValidator.Var(c.Text, "required"); err != nil {
		errors = errors.Append("Text", err)
	}
	if v, ok := any(c.Usage).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Usage", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type Usage struct {
	PromptTokens     int `json:"promptTokens"`
	CompletionTokens int `json:"completionTokens"`
}

type Chunk struct {
	Index        int                `json:"index"`
	Delta        string             `json:"delta" validate:"required"`
	FinishReason *ChunkFinishReason `json:"finishReason,omitempty"`
}

func (c Chunk) Validate() error {
	var errors runtime.ValidationErrors
	if err := typesValidator.Var(c.Delta, "required"); err != nil {
		errors = errors.Append("Delta", err)
	}
	if c.FinishReason != nil {
		if v, ok := any(c.FinishReason).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("FinishReason", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type Event struct {
	Seq       int       `json:"seq"`
	Type      EventType `json:"type" validate:"required"`
	CreatedAt time.Time `json:"createdAt" validate:"required"`
	Actor     Actor     `json:"actor"`
	Tags      []string  `json:"tags,omitempty"`
}

func (e Event) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(e.Type).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Type", err)
		}
	}
	if err := typesValidator.Var(e.CreatedAt, "required"); err != nil {
		errors = errors.Append("CreatedAt", err)
	}
	if v, ok := any(e.Actor).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Actor", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type Actor struct {
	ID   uuid.UUID `json:"id" validate:"required"`
	Name string    `json:"name" validate:"required"`
}

func (a Actor) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(a.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if err := typesValidator.Var(a.Name, "required"); err != nil {
		errors = errors.Append("Name", err)
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type ServiceError struct {
	Message string `json:"message" validate:"required"`
}

func (s ServiceError) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(s))
}

func (s ServiceError) Error() string {
	return "unmapped client error"
}

type StreamLogs_Response_Source struct {
	Service string  `json:"service" validate:"required"`
	Host    *string `json:"host,omitempty"`
}

func (s StreamLogs_Response_Source) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(s))
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
