// Code generated by oapi-codegen. DO NOT EDIT.
package api

import (
	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

// ServiceInterface defines the service interface for business logic.
type ServiceInterface interface {
}

// HTTPAdapter adapts the ServiceInterface to HTTP handlers.
// This struct is generated and should not be modified.
type HTTPAdapter struct {
	svc         ServiceInterface
	errHandler  OapiErrorHandler
	bodyDecoder runtime.BodyDecoderFunc
}

// NewHTTPAdapter creates a new HTTPAdapter wrapping the given service.
// If errHandler is nil, OapiDefaultErrorHandler is used.
func NewHTTPAdapter(svc ServiceInterface, errHandler OapiErrorHandler) *HTTPAdapter {
	if errHandler == nil {
		errHandler = &OapiDefaultErrorHandler{}
	}
	return &HTTPAdapter{svc: svc, errHandler: errHandler, bodyDecoder: runtime.DecodeJSONBody}
}
