// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type ListConfigsResponse = Config

type Config struct {
	Enabled *bool `json:"enabled,omitempty"`
	Timeout *int  `json:"timeout,omitempty"`
	Retries *int  `json:"retries,omitempty"`
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
