// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"fmt"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

// EmailActivityResponseCommonFieldsStatus The message's status.
type EmailActivityResponseCommonFieldsStatus string

const (
	EmailActivityResponseCommonFieldsStatusDelivered    EmailActivityResponseCommonFieldsStatus = "delivered"
	EmailActivityResponseCommonFieldsStatusNotDelivered EmailActivityResponseCommonFieldsStatus = "not delivered"
	EmailActivityResponseCommonFieldsStatusProcessed    EmailActivityResponseCommonFieldsStatus = "processed"
)

// Validate checks if the EmailActivityResponseCommonFieldsStatus value is valid
func (e EmailActivityResponseCommonFieldsStatus) Validate() error {
	switch e {
	case EmailActivityResponseCommonFieldsStatusDelivered, EmailActivityResponseCommonFieldsStatusNotDelivered, EmailActivityResponseCommonFieldsStatusProcessed:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid EmailActivityResponseCommonFieldsStatus value, got: %v", e))
	}
}

// GetMsgIDResponseStatus1 Quick summary of the status of a message
type GetMsgIDResponseStatus1 string

const (
	GetMsgIDResponseStatus1Delivered    GetMsgIDResponseStatus1 = "delivered"
	GetMsgIDResponseStatus1NotDelivered GetMsgIDResponseStatus1 = "not delivered"
	GetMsgIDResponseStatus1Processed    GetMsgIDResponseStatus1 = "processed"
)

// Validate checks if the GetMsgIDResponseStatus1 value is valid
func (g GetMsgIDResponseStatus1) Validate() error {
	switch g {
	case GetMsgIDResponseStatus1Delivered, GetMsgIDResponseStatus1NotDelivered, GetMsgIDResponseStatus1Processed:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid GetMsgIDResponseStatus1 value, got: %v", g))
	}
}

// GetMsgIDResponseStatus The message's status.
type GetMsgIDResponseStatus string

const (
	GetMsgIDResponseStatusDelivered    GetMsgIDResponseStatus = "delivered"
	GetMsgIDResponseStatusNotDelivered GetMsgIDResponseStatus = "not delivered"
	GetMsgIDResponseStatusProcessed    GetMsgIDResponseStatus = "processed"
)

// Validate checks if the GetMsgIDResponseStatus value is valid
func (g GetMsgIDResponseStatus) Validate() error {
	switch g {
	case GetMsgIDResponseStatusDelivered, GetMsgIDResponseStatusNotDelivered, GetMsgIDResponseStatusProcessed:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid GetMsgIDResponseStatus value, got: %v", g))
	}
}

// GetMsgIDResponseEventsBounceType1 Use to distinguish between types of bounces
type GetMsgIDResponseEventsBounceType1 string

const (
	GetMsgIDResponseEventsBounceType1Blocked GetMsgIDResponseEventsBounceType1 = "blocked"
	GetMsgIDResponseEventsBounceType1Bounced GetMsgIDResponseEventsBounceType1 = "bounced"
	GetMsgIDResponseEventsBounceType1Expired GetMsgIDResponseEventsBounceType1 = "expired"
)

// Validate checks if the GetMsgIDResponseEventsBounceType1 value is valid
func (g GetMsgIDResponseEventsBounceType1) Validate() error {
	switch g {
	case GetMsgIDResponseEventsBounceType1Blocked, GetMsgIDResponseEventsBounceType1Bounced, GetMsgIDResponseEventsBounceType1Expired:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid GetMsgIDResponseEventsBounceType1 value, got: %v", g))
	}
}

// GetMsgIDResponseEventsBounceType Use to distinguish between types of bounces
type GetMsgIDResponseEventsBounceType string

const (
	GetMsgIDResponseEventsBounceTypeHard GetMsgIDResponseEventsBounceType = "hard"
	GetMsgIDResponseEventsBounceTypeSoft GetMsgIDResponseEventsBounceType = "soft"
)

// Validate checks if the GetMsgIDResponseEventsBounceType value is valid
func (g GetMsgIDResponseEventsBounceType) Validate() error {
	switch g {
	case GetMsgIDResponseEventsBounceTypeHard, GetMsgIDResponseEventsBounceTypeSoft:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid GetMsgIDResponseEventsBounceType value, got: %v", g))
	}
}

type GetMsgIDResponse struct {
	// Status The message's status.
	Status *GetMsgIDResponseStatus `json:"status,omitempty"`

	// Events List of events related to email message
	Events *GetMsgID_Response_Events `json:"events,omitempty"`
}

type EmailActivityResponseCommonFields struct {
	// Status The message's status.
	Status *EmailActivityResponseCommonFieldsStatus `json:"status,omitempty"`
}

func (e EmailActivityResponseCommonFields) Validate() error {
	var errors runtime.ValidationErrors
	if e.Status != nil {
		if v, ok := any(e.Status).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Status", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

// GetMsgID_Response_Events1 List of events related to email message
type GetMsgID_Response_Events1 []GetMsgID_Response_Events_Item1

func (g GetMsgID_Response_Events1) Validate() error {
	if g == nil {
		return nil
	}
	var errors runtime.ValidationErrors
	for i, item := range g {
		if v, ok := any(item).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append(fmt.Sprintf("[%d]", i), err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetMsgID_Response_Events_Item1 struct {
	// BounceType Use to distinguish between types of bounces
	BounceType *GetMsgIDResponseEventsBounceType1 `json:"bounce_type,omitempty"`
}

func (g GetMsgID_Response_Events_Item1) Validate() error {
	var errors runtime.ValidationErrors
	if g.BounceType != nil {
		if v, ok := any(g.BounceType).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("BounceType", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

// GetMsgID_Response_Events List of events related to email message
type GetMsgID_Response_Events []GetMsgID_Response_Events_Item

func (g GetMsgID_Response_Events) Validate() error {
	if g == nil {
		return nil
	}
	var errors runtime.ValidationErrors
	for i, item := range g {
		if v, ok := any(item).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append(fmt.Sprintf("[%d]", i), err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetMsgID_Response_Events_Item struct {
	// BounceType Use to distinguish between types of bounces
	BounceType *GetMsgIDResponseEventsBounceType `json:"bounce_type,omitempty"`
}

func (g GetMsgID_Response_Events_Item) Validate() error {
	var errors runtime.ValidationErrors
	if g.BounceType != nil {
		if v, ok := any(g.BounceType).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("BounceType", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
