// Code generated by oapi-codegen. DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-chi/chi/v5"
)

// ServiceInterface defines the service interface for business logic.
type ServiceInterface interface {
	// HealthCheck Health check endpoint
	HealthCheck(ctx context.Context) (*HealthCheckResponseData, error)
	// ListUsers List all users
	ListUsers(ctx context.Context, opts *ListUsersServiceRequestOptions) (*ListUsersResponseData, error)
	// CreateUser Create a new user via JSON
	CreateUser(ctx context.Context, opts *CreateUserServiceRequestOptions) (*CreateUserResponseData, error)
	// ImportUsers Import users from CSV file
	ImportUsers(ctx context.Context, opts *ImportUsersServiceRequestOptions) (*ImportUsersResponseData, error)
	// GetUser Get a user by ID
	GetUser(ctx context.Context, opts *GetUserServiceRequestOptions) (*GetUserResponseData, error)
	// DeleteUser Delete a user
	DeleteUser(ctx context.Context, opts *DeleteUserServiceRequestOptions) (*DeleteUserResponseData, error)
	// GetUserAvatar Get user avatar image
	GetUserAvatar(ctx context.Context, opts *GetUserAvatarServiceRequestOptions) (*GetUserAvatarResponseData, error)
	// UploadUserAvatar Upload user avatar
	UploadUserAvatar(ctx context.Context, opts *UploadUserAvatarServiceRequestOptions) (*UploadUserAvatarResponseData, error)
	// SubmitContactForm Submit contact form
	SubmitContactForm(ctx context.Context, opts *SubmitContactFormServiceRequestOptions) (*SubmitContactFormResponseData, error)
	// CreateNote Create a note from plain text
	CreateNote(ctx context.Context, opts *CreateNoteServiceRequestOptions) (*CreateNoteResponseData, error)
	// ProcessXMLData Process XML data (demonstrates custom content type handling)
	ProcessXMLData(ctx context.Context, opts *ProcessXMLDataServiceRequestOptions) (*ProcessXMLDataResponseData, error)
	// ExportData Export all data as binary archive
	ExportData(ctx context.Context) (*ExportDataResponseData, error)
	// GetOAuthToken Get OAuth token (form-encoded response)
	GetOAuthToken(ctx context.Context, opts *GetOAuthTokenServiceRequestOptions) (*GetOAuthTokenResponseData, error)
	// GetItemsByType Get items by type (tests reserved Go keyword as path param)
	GetItemsByType(ctx context.Context, opts *GetItemsByTypeServiceRequestOptions) (*GetItemsByTypeResponseData, error)
	// Search Search with union type response (oneOf)
	Search(ctx context.Context, opts *SearchServiceRequestOptions) (*SearchResponseData, error)
	// GetStatus Get status (uses reusable response)
	GetStatus(ctx context.Context) (*GetStatusResponseData, error)
	// UploadImage Upload image (wildcard content type)
	UploadImage(ctx context.Context, opts *UploadImageServiceRequestOptions) (*UploadImageResponseData, error)
	// ListProducts List products with various query param types
	ListProducts(ctx context.Context, opts *ListProductsServiceRequestOptions) (*ListProductsResponseData, error)
	// GetCategory Get a category by ID (integer path param)
	GetCategory(ctx context.Context, opts *GetCategoryServiceRequestOptions) (*GetCategoryResponseData, error)
	// GetItemsByStatus Get items by active status and rating (boolean + number path params)
	GetItemsByStatus(ctx context.Context, opts *GetItemsByStatusServiceRequestOptions) (*GetItemsByStatusResponseData, error)
	// GetUserPost Get a specific post by a user
	GetUserPost(ctx context.Context, opts *GetUserPostServiceRequestOptions) (*GetUserPostResponseData, error)
	// CreateOrder Create an order (demonstrates typed error responses)
	CreateOrder(ctx context.Context, opts *CreateOrderServiceRequestOptions) (*CreateOrderResponseData, error)
	// CreateCompany Create a company with nested address
	CreateCompany(ctx context.Context, opts *CreateCompanyServiceRequestOptions) (*CreateCompanyResponseData, error)
}

// HTTPAdapter adapts the ServiceInterface to HTTP handlers.
// This struct is generated and should not be modified.
type HTTPAdapter struct {
	svc ServiceInterface
}

// NewHTTPAdapter creates a new HTTPAdapter wrapping the given service.
func NewHTTPAdapter(svc ServiceInterface) *HTTPAdapter {
	return &HTTPAdapter{svc: svc}
}

// returnParseError writes a 400 Bad Request response if err is not nil.
// Returns true if an error was written (caller should return), false otherwise.
func returnParseError(w http.ResponseWriter, paramName string, err error) bool {
	if err != nil {
		http.Error(w, fmt.Sprintf("invalid parameter %q: %v", paramName, err), http.StatusBadRequest)
		return true
	}
	return false
}

// HTTP handler adapters - parse request, call interface, write response

// HealthCheck handles GET /health
func (a *HTTPAdapter) HealthCheck(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// Call business logic
	resp, err := a.svc.HealthCheck(ctx)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_, _ = fmt.Fprintf(w, "%v", *resp.Body)
	}
}

// ListUsers handles GET /users
func (a *HTTPAdapter) ListUsers(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &ListUsersServiceRequestOptions{}
	opts.RawRequest = r

	// Parse query parameters
	queryParams := &ListUsersQuery{}
	query := r.URL.Query()
	if queryParamLimitStr := query.Get("limit"); queryParamLimitStr != "" {
		queryParamLimit, err := runtime.ParseString[int](queryParamLimitStr)
		if returnParseError(w, "limit", err) {
			return
		}
		queryParams.Limit = &queryParamLimit
	}
	opts.Query = queryParams

	// Parse header parameters
	headerParams := &ListUsersHeaders{}
	headers := r.Header
	if headerValues := headers[http.CanonicalHeaderKey("X-Request-ID")]; len(headerValues) > 0 {
		headerParamXRequestID := headerValues[0]
		headerParams.XRequestID = headerParamXRequestID
	}
	opts.Header = headerParams

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := a.svc.ListUsers(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

// CreateUser handles POST /users
func (a *HTTPAdapter) CreateUser(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &CreateUserServiceRequestOptions{}
	opts.RawRequest = r

	// Parse request body
	defer r.Body.Close()
	var body CreateUserBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	opts.Body = &body

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := a.svc.CreateUser(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		if _, ok := err.(*CreateUserErrorResponse); ok {
			code = 400
		}
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 201
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

// ImportUsers handles POST /users/import
func (a *HTTPAdapter) ImportUsers(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &ImportUsersServiceRequestOptions{}
	opts.RawRequest = r

	// Parse request body
	defer r.Body.Close()
	if err := r.ParseMultipartForm(32 << 20); err != nil { // 32MB max memory
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var body ImportUsersBody
	if fileHeaders := r.MultipartForm.File["file"]; len(fileHeaders) > 0 {
		body.File.InitFromMultipart(fileHeaders[0])
	}
	if values := r.MultipartForm.Value["overwrite"]; len(values) > 0 {

		if v, err := runtime.ParseString[bool](values[0]); err == nil {
			body.Overwrite = &v
		}
	}
	opts.Body = &body

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := a.svc.ImportUsers(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

// GetUser handles GET /users/{id}
func (a *HTTPAdapter) GetUser(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &GetUserServiceRequestOptions{}
	opts.RawRequest = r

	// Parse path parameters
	pathParams := &GetUserPath{}
	pathParamIDStr := chi.URLParam(r, "id")
	pathParams.ID = pathParamIDStr
	opts.PathParams = pathParams

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := a.svc.GetUser(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		if _, ok := err.(*GetUserErrorResponse); ok {
			code = 404
		}
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

// DeleteUser handles DELETE /users/{id}
func (a *HTTPAdapter) DeleteUser(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &DeleteUserServiceRequestOptions{}
	opts.RawRequest = r

	// Parse path parameters
	pathParams := &DeleteUserPath{}
	pathParamIDStr := chi.URLParam(r, "id")
	pathParams.ID = pathParamIDStr
	opts.PathParams = pathParams

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := a.svc.DeleteUser(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 204
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.WriteHeader(status)
}

// GetUserAvatar handles GET /users/{id}/avatar
func (a *HTTPAdapter) GetUserAvatar(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &GetUserAvatarServiceRequestOptions{}
	opts.RawRequest = r

	// Parse path parameters
	pathParams := &GetUserAvatarPath{}
	pathParamIDStr := chi.URLParam(r, "id")
	pathParams.ID = pathParamIDStr
	opts.PathParams = pathParams

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := a.svc.GetUserAvatar(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		if _, ok := err.(*GetUserAvatarErrorResponse); ok {
			code = 404
		}
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/octet-stream")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		data, err := resp.Body.Bytes()
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		_, _ = w.Write(data)
	}
}

// UploadUserAvatar handles PUT /users/{id}/avatar
func (a *HTTPAdapter) UploadUserAvatar(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &UploadUserAvatarServiceRequestOptions{}
	opts.RawRequest = r

	// Parse path parameters
	pathParams := &UploadUserAvatarPath{}
	pathParamIDStr := chi.URLParam(r, "id")
	pathParams.ID = pathParamIDStr
	opts.PathParams = pathParams
	// Parse request body
	defer r.Body.Close()

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := a.svc.UploadUserAvatar(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 204
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.WriteHeader(status)
}

// SubmitContactForm handles POST /contact
func (a *HTTPAdapter) SubmitContactForm(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &SubmitContactFormServiceRequestOptions{}
	opts.RawRequest = r

	// Parse request body
	defer r.Body.Close()
	var body SubmitContactFormBody
	formBytes, err := io.ReadAll(r.Body)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	jsonBytes, err := runtime.ConvertFormFields(formBytes)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := json.Unmarshal(jsonBytes, &body); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	opts.Body = &body

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := a.svc.SubmitContactForm(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

// CreateNote handles POST /notes
func (a *HTTPAdapter) CreateNote(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &CreateNoteServiceRequestOptions{}
	opts.RawRequest = r

	// Parse request body
	defer r.Body.Close()
	bodyBytes, err := io.ReadAll(r.Body)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	body := CreateNoteBody(string(bodyBytes))
	opts.Body = &body

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := a.svc.CreateNote(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 201
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_, _ = fmt.Fprintf(w, "%v", *resp.Body)
	}
}

// ProcessXMLData handles POST /xml-data
func (a *HTTPAdapter) ProcessXMLData(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &ProcessXMLDataServiceRequestOptions{}
	opts.RawRequest = r

	// Parse request body
	defer r.Body.Close()

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := a.svc.ProcessXMLData(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/xml")

	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_, _ = w.Write(resp.Body)
	}
}

// ExportData handles GET /export
func (a *HTTPAdapter) ExportData(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// Call business logic
	resp, err := a.svc.ExportData(ctx)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/octet-stream")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		data, err := resp.Body.Bytes()
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		_, _ = w.Write(data)
	}
}

// GetOAuthToken handles POST /oauth/token
func (a *HTTPAdapter) GetOAuthToken(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &GetOAuthTokenServiceRequestOptions{}
	opts.RawRequest = r

	// Parse request body
	defer r.Body.Close()
	var body GetOAuthTokenBody
	formBytes, err := io.ReadAll(r.Body)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	jsonBytes, err := runtime.ConvertFormFields(formBytes)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := json.Unmarshal(jsonBytes, &body); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	opts.Body = &body

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := a.svc.GetOAuthToken(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/x-www-form-urlencoded")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		formData, err := runtime.EncodeFormFields(resp.Body, nil)
		if err == nil {
			_, _ = w.Write([]byte(formData))
		}
	}
}

// GetItemsByType handles GET /items/{type}
func (a *HTTPAdapter) GetItemsByType(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &GetItemsByTypeServiceRequestOptions{}
	opts.RawRequest = r

	// Parse path parameters
	pathParams := &GetItemsByTypePath{}
	pathParamTypeStr := chi.URLParam(r, "type")
	pathParams.Type = pathParamTypeStr
	opts.PathParams = pathParams

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := a.svc.GetItemsByType(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

// Search handles GET /search
func (a *HTTPAdapter) Search(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &SearchServiceRequestOptions{}
	opts.RawRequest = r

	// Parse query parameters
	queryParams := &SearchQuery{}
	query := r.URL.Query()
	if queryParamQStr := query.Get("q"); queryParamQStr != "" {
		queryParamQ := queryParamQStr
		queryParams.Q = queryParamQ
	}
	opts.Query = queryParams

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := a.svc.Search(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

// GetStatus handles GET /status
func (a *HTTPAdapter) GetStatus(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// Call business logic
	resp, err := a.svc.GetStatus(ctx)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

// UploadImage handles POST /images
func (a *HTTPAdapter) UploadImage(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &UploadImageServiceRequestOptions{}
	opts.RawRequest = r

	// Parse request body
	defer r.Body.Close()

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := a.svc.UploadImage(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 201
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

// ListProducts handles GET /products
func (a *HTTPAdapter) ListProducts(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &ListProductsServiceRequestOptions{}
	opts.RawRequest = r

	// Parse query parameters
	queryParams := &ListProductsQuery{}
	query := r.URL.Query()

	if values, ok := query["ids"]; ok {
		queryParams.Ids = values
	}

	if values, ok := query["tags"]; ok {
		queryParams.Tags = values
	}

	if values, ok := query["categoryIds"]; ok {
		parsed, err := runtime.ParseStringSlice[int](values)
		if returnParseError(w, "categoryIds", err) {
			return
		}
		queryParams.CategoryIds = parsed
	}
	if queryParamMinPriceStr := query.Get("minPrice"); queryParamMinPriceStr != "" {
		queryParamMinPrice, err := runtime.ParseString[float32](queryParamMinPriceStr)
		if returnParseError(w, "minPrice", err) {
			return
		}
		queryParams.MinPrice = &queryParamMinPrice
	}
	if queryParamActiveStr := query.Get("active"); queryParamActiveStr != "" {
		queryParamActive, err := runtime.ParseString[bool](queryParamActiveStr)
		if returnParseError(w, "active", err) {
			return
		}
		queryParams.Active = &queryParamActive
	}
	opts.Query = queryParams

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := a.svc.ListProducts(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

// GetCategory handles GET /categories/{categoryId}
func (a *HTTPAdapter) GetCategory(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &GetCategoryServiceRequestOptions{}
	opts.RawRequest = r

	// Parse path parameters
	pathParams := &GetCategoryPath{}
	pathParamCategoryIDStr := chi.URLParam(r, "categoryId")

	pathParamCategoryID, err := runtime.ParseString[int](pathParamCategoryIDStr)
	if returnParseError(w, "categoryId", err) {
		return
	}
	pathParams.CategoryID = pathParamCategoryID
	opts.PathParams = pathParams

	// Parse header parameters
	headerParams := &GetCategoryHeaders{}
	headers := r.Header
	if headerValues := headers[http.CanonicalHeaderKey("X-Include-Products")]; len(headerValues) > 0 {
		headerParamXIncludeProducts, err := runtime.ParseString[bool](headerValues[0])
		if returnParseError(w, "X-Include-Products", err) {
			return
		}
		headerParams.XIncludeProducts = &headerParamXIncludeProducts
	}
	if headerValues := headers[http.CanonicalHeaderKey("X-Max-Depth")]; len(headerValues) > 0 {
		headerParamXMaxDepth, err := runtime.ParseString[int](headerValues[0])
		if returnParseError(w, "X-Max-Depth", err) {
			return
		}
		headerParams.XMaxDepth = &headerParamXMaxDepth
	}
	if headerValues := headers[http.CanonicalHeaderKey("X-Price-Threshold")]; len(headerValues) > 0 {
		headerParamXPriceThreshold, err := runtime.ParseString[float32](headerValues[0])
		if returnParseError(w, "X-Price-Threshold", err) {
			return
		}
		headerParams.XPriceThreshold = &headerParamXPriceThreshold
	}
	opts.Header = headerParams

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := a.svc.GetCategory(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

// GetItemsByStatus handles GET /items/{active}/{rating}
func (a *HTTPAdapter) GetItemsByStatus(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &GetItemsByStatusServiceRequestOptions{}
	opts.RawRequest = r

	// Parse path parameters
	pathParams := &GetItemsByStatusPath{}
	pathParamActiveStr := chi.URLParam(r, "active")

	pathParamActive, err := runtime.ParseString[bool](pathParamActiveStr)
	if returnParseError(w, "active", err) {
		return
	}
	pathParams.Active = pathParamActive
	pathParamRatingStr := chi.URLParam(r, "rating")

	pathParamRating, err := runtime.ParseString[float32](pathParamRatingStr)
	if returnParseError(w, "rating", err) {
		return
	}
	pathParams.Rating = pathParamRating
	opts.PathParams = pathParams

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := a.svc.GetItemsByStatus(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

// GetUserPost handles GET /users/{userId}/posts/{postId}
func (a *HTTPAdapter) GetUserPost(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &GetUserPostServiceRequestOptions{}
	opts.RawRequest = r

	// Parse path parameters
	pathParams := &GetUserPostPath{}
	pathParamUserIDStr := chi.URLParam(r, "userId")
	pathParams.UserID = pathParamUserIDStr
	pathParamPostIDStr := chi.URLParam(r, "postId")
	pathParams.PostID = pathParamPostIDStr
	opts.PathParams = pathParams

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := a.svc.GetUserPost(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

// CreateOrder handles POST /orders
func (a *HTTPAdapter) CreateOrder(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &CreateOrderServiceRequestOptions{}
	opts.RawRequest = r

	// Parse request body
	defer r.Body.Close()
	var body CreateOrderBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	opts.Body = &body

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := a.svc.CreateOrder(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 201
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

// CreateCompany handles POST /companies
func (a *HTTPAdapter) CreateCompany(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &CreateCompanyServiceRequestOptions{}
	opts.RawRequest = r

	// Parse request body
	defer r.Body.Close()
	var body CreateCompanyBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	opts.Body = &body

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := a.svc.CreateCompany(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 201
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}
