// Code generated by oapi-codegen. DO NOT EDIT.
package api

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

// HTTPAdapter adapts the HandlerInterface to HTTP handlers.
// This struct is generated and should not be modified.
type HTTPAdapter struct {
	impl HandlerInterface
}

// NewHTTPAdapter creates a new HTTPAdapter wrapping the given implementation.
func NewHTTPAdapter(impl HandlerInterface) *HTTPAdapter {
	return &HTTPAdapter{impl: impl}
}

// returnParseError writes a 400 Bad Request response if err is not nil.
// Returns true if an error was written (caller should return), false otherwise.
func returnParseError(w http.ResponseWriter, paramName string, err error) bool {
	if err != nil {
		http.Error(w, fmt.Sprintf("invalid parameter %q: %v", paramName, err), http.StatusBadRequest)
		return true
	}
	return false
}

// HTTP handler adapters - parse request, call interface, write response

func (h *HTTPAdapter) HealthCheck(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// Call business logic
	resp, err := h.impl.HealthCheck(ctx)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_, _ = fmt.Fprintf(w, "%v", *resp.Body)
	}
}

func (h *HTTPAdapter) ListUsers(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &ListUsersHandlerRequestOptions{}
	opts.RawRequest = r

	// Parse query parameters
	queryParams := &ListUsersQuery{}
	query := r.URL.Query()
	if queryParamLimitStr := query.Get("limit"); queryParamLimitStr != "" {
		queryParamLimit, err := runtime.ParseString[int](queryParamLimitStr)
		if returnParseError(w, "limit", err) {
			return
		}
		queryParams.Limit = &queryParamLimit
	}
	opts.Query = queryParams

	// Parse header parameters
	headerParams := &ListUsersHeaders{}
	headers := r.Header
	if headerValues := headers[http.CanonicalHeaderKey("X-Request-ID")]; len(headerValues) > 0 {
		headerParamXRequestID := headerValues[0]
		headerParams.XRequestID = headerParamXRequestID
	}
	opts.Header = headerParams

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := h.impl.ListUsers(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

func (h *HTTPAdapter) CreateUser(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &CreateUserHandlerRequestOptions{}
	opts.RawRequest = r

	// Parse request body
	defer r.Body.Close()
	var body CreateUserBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	opts.Body = &body

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := h.impl.CreateUser(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		if _, ok := err.(*CreateUserErrorResponse); ok {
			code = 400
		}
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 201
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

func (h *HTTPAdapter) ImportUsers(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &ImportUsersHandlerRequestOptions{}
	opts.RawRequest = r

	// Parse request body
	defer r.Body.Close()
	if err := r.ParseMultipartForm(32 << 20); err != nil { // 32MB max memory
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var body ImportUsersBody
	if fileHeaders := r.MultipartForm.File["file"]; len(fileHeaders) > 0 {
		body.File.InitFromMultipart(fileHeaders[0])
	}
	if values := r.MultipartForm.Value["overwrite"]; len(values) > 0 {
		body.Overwrite = new(bool)
		*body.Overwrite = values[0] == "true"
	}
	opts.Body = &body

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := h.impl.ImportUsers(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

func (h *HTTPAdapter) GetUser(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &GetUserHandlerRequestOptions{}
	opts.RawRequest = r

	// Parse path parameters
	pathParams := &GetUserPath{}
	pathParamIDStr := r.PathValue("id")
	pathParams.ID = pathParamIDStr
	opts.PathParams = pathParams

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := h.impl.GetUser(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		if _, ok := err.(*GetUserErrorResponse); ok {
			code = 404
		}
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

func (h *HTTPAdapter) DeleteUser(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &DeleteUserHandlerRequestOptions{}
	opts.RawRequest = r

	// Parse path parameters
	pathParams := &DeleteUserPath{}
	pathParamIDStr := r.PathValue("id")
	pathParams.ID = pathParamIDStr
	opts.PathParams = pathParams

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := h.impl.DeleteUser(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 204
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.WriteHeader(status)
}

func (h *HTTPAdapter) GetUserAvatar(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &GetUserAvatarHandlerRequestOptions{}
	opts.RawRequest = r

	// Parse path parameters
	pathParams := &GetUserAvatarPath{}
	pathParamIDStr := r.PathValue("id")
	pathParams.ID = pathParamIDStr
	opts.PathParams = pathParams

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := h.impl.GetUserAvatar(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		if _, ok := err.(*GetUserAvatarErrorResponse); ok {
			code = 404
		}
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/octet-stream")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		data, err := resp.Body.Bytes()
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		_, _ = w.Write(data)
	}
}

func (h *HTTPAdapter) UploadUserAvatar(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &UploadUserAvatarHandlerRequestOptions{}
	opts.RawRequest = r

	// Parse path parameters
	pathParams := &UploadUserAvatarPath{}
	pathParamIDStr := r.PathValue("id")
	pathParams.ID = pathParamIDStr
	opts.PathParams = pathParams
	// Parse request body
	defer r.Body.Close()

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := h.impl.UploadUserAvatar(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 204
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.WriteHeader(status)
}

func (h *HTTPAdapter) SubmitContactForm(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &SubmitContactFormHandlerRequestOptions{}
	opts.RawRequest = r

	// Parse request body
	defer r.Body.Close()
	var body SubmitContactFormBody
	formBytes, err := io.ReadAll(r.Body)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	jsonBytes, err := runtime.ConvertFormFields(formBytes)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := json.Unmarshal(jsonBytes, &body); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	opts.Body = &body

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := h.impl.SubmitContactForm(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

func (h *HTTPAdapter) CreateNote(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &CreateNoteHandlerRequestOptions{}
	opts.RawRequest = r

	// Parse request body
	defer r.Body.Close()
	bodyBytes, err := io.ReadAll(r.Body)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	body := CreateNoteBody(string(bodyBytes))
	opts.Body = &body

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := h.impl.CreateNote(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 201
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_, _ = fmt.Fprintf(w, "%v", *resp.Body)
	}
}

func (h *HTTPAdapter) ProcessXMLData(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &ProcessXMLDataHandlerRequestOptions{}
	opts.RawRequest = r

	// Parse request body
	defer r.Body.Close()

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := h.impl.ProcessXMLData(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/xml")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_, _ = w.Write(resp.Body)
	}
}

func (h *HTTPAdapter) ExportData(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// Call business logic
	resp, err := h.impl.ExportData(ctx)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/octet-stream")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		data, err := resp.Body.Bytes()
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		_, _ = w.Write(data)
	}
}

func (h *HTTPAdapter) GetOAuthToken(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &GetOAuthTokenHandlerRequestOptions{}
	opts.RawRequest = r

	// Parse request body
	defer r.Body.Close()
	var body GetOAuthTokenBody
	formBytes, err := io.ReadAll(r.Body)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	jsonBytes, err := runtime.ConvertFormFields(formBytes)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := json.Unmarshal(jsonBytes, &body); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	opts.Body = &body

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := h.impl.GetOAuthToken(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/x-www-form-urlencoded")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		formData, err := runtime.EncodeFormFields(resp.Body, nil)
		if err == nil {
			_, _ = w.Write([]byte(formData))
		}
	}
}

func (h *HTTPAdapter) GetItemsByType(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &GetItemsByTypeHandlerRequestOptions{}
	opts.RawRequest = r

	// Parse path parameters
	pathParams := &GetItemsByTypePath{}
	pathParamTypeStr := r.PathValue("type")
	pathParams.Type = pathParamTypeStr
	opts.PathParams = pathParams

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := h.impl.GetItemsByType(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

func (h *HTTPAdapter) Search(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &SearchHandlerRequestOptions{}
	opts.RawRequest = r

	// Parse query parameters
	queryParams := &SearchQuery{}
	query := r.URL.Query()
	if queryParamQStr := query.Get("q"); queryParamQStr != "" {
		queryParamQ := queryParamQStr
		queryParams.Q = queryParamQ
	}
	opts.Query = queryParams

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := h.impl.Search(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

func (h *HTTPAdapter) GetStatus(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// Call business logic
	resp, err := h.impl.GetStatus(ctx)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

func (h *HTTPAdapter) UploadImage(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &UploadImageHandlerRequestOptions{}
	opts.RawRequest = r

	// Parse request body
	defer r.Body.Close()

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := h.impl.UploadImage(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 201
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

func (h *HTTPAdapter) ListProducts(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &ListProductsHandlerRequestOptions{}
	opts.RawRequest = r

	// Parse query parameters
	queryParams := &ListProductsQuery{}
	query := r.URL.Query()

	if values, ok := query["ids"]; ok {
		queryParams.Ids = values
	}

	if values, ok := query["tags"]; ok {
		queryParams.Tags = values
	}

	if values, ok := query["categoryIds"]; ok {
		parsed, err := runtime.ParseStringSlice[int](values)
		if returnParseError(w, "categoryIds", err) {
			return
		}
		queryParams.CategoryIds = parsed
	}
	if queryParamMinPriceStr := query.Get("minPrice"); queryParamMinPriceStr != "" {
		queryParamMinPrice, err := runtime.ParseString[float32](queryParamMinPriceStr)
		if returnParseError(w, "minPrice", err) {
			return
		}
		queryParams.MinPrice = &queryParamMinPrice
	}
	if queryParamActiveStr := query.Get("active"); queryParamActiveStr != "" {
		queryParamActive, err := runtime.ParseString[bool](queryParamActiveStr)
		if returnParseError(w, "active", err) {
			return
		}
		queryParams.Active = &queryParamActive
	}
	opts.Query = queryParams

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := h.impl.ListProducts(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

func (h *HTTPAdapter) GetCategory(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &GetCategoryHandlerRequestOptions{}
	opts.RawRequest = r

	// Parse path parameters
	pathParams := &GetCategoryPath{}
	pathParamCategoryIDStr := r.PathValue("categoryId")

	pathParamCategoryID, err := runtime.ParseString[int](pathParamCategoryIDStr)
	if returnParseError(w, "categoryId", err) {
		return
	}
	pathParams.CategoryID = pathParamCategoryID
	opts.PathParams = pathParams

	// Parse header parameters
	headerParams := &GetCategoryHeaders{}
	headers := r.Header
	if headerValues := headers[http.CanonicalHeaderKey("X-Include-Products")]; len(headerValues) > 0 {
		headerParamXIncludeProducts, err := runtime.ParseString[bool](headerValues[0])
		if returnParseError(w, "X-Include-Products", err) {
			return
		}
		headerParams.XIncludeProducts = &headerParamXIncludeProducts
	}
	if headerValues := headers[http.CanonicalHeaderKey("X-Max-Depth")]; len(headerValues) > 0 {
		headerParamXMaxDepth, err := runtime.ParseString[int](headerValues[0])
		if returnParseError(w, "X-Max-Depth", err) {
			return
		}
		headerParams.XMaxDepth = &headerParamXMaxDepth
	}
	if headerValues := headers[http.CanonicalHeaderKey("X-Price-Threshold")]; len(headerValues) > 0 {
		headerParamXPriceThreshold, err := runtime.ParseString[float32](headerValues[0])
		if returnParseError(w, "X-Price-Threshold", err) {
			return
		}
		headerParams.XPriceThreshold = &headerParamXPriceThreshold
	}
	opts.Header = headerParams

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := h.impl.GetCategory(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

func (h *HTTPAdapter) GetItemsByStatus(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &GetItemsByStatusHandlerRequestOptions{}
	opts.RawRequest = r

	// Parse path parameters
	pathParams := &GetItemsByStatusPath{}
	pathParamActiveStr := r.PathValue("active")

	pathParamActive, err := runtime.ParseString[bool](pathParamActiveStr)
	if returnParseError(w, "active", err) {
		return
	}
	pathParams.Active = pathParamActive
	pathParamRatingStr := r.PathValue("rating")

	pathParamRating, err := runtime.ParseString[float32](pathParamRatingStr)
	if returnParseError(w, "rating", err) {
		return
	}
	pathParams.Rating = pathParamRating
	opts.PathParams = pathParams

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := h.impl.GetItemsByStatus(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

func (h *HTTPAdapter) GetUserPost(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &GetUserPostHandlerRequestOptions{}
	opts.RawRequest = r

	// Parse path parameters
	pathParams := &GetUserPostPath{}
	pathParamUserIDStr := r.PathValue("userId")
	pathParams.UserID = pathParamUserIDStr
	pathParamPostIDStr := r.PathValue("postId")
	pathParams.PostID = pathParamPostIDStr
	opts.PathParams = pathParams

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := h.impl.GetUserPost(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

func (h *HTTPAdapter) CreateOrder(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &CreateOrderHandlerRequestOptions{}
	opts.RawRequest = r

	// Parse request body
	defer r.Body.Close()
	var body CreateOrderBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	opts.Body = &body

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := h.impl.CreateOrder(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 201
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

func (h *HTTPAdapter) CreateCompany(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &CreateCompanyHandlerRequestOptions{}
	opts.RawRequest = r

	// Parse request body
	defer r.Body.Close()
	var body CreateCompanyBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	opts.Body = &body

	// Validate request
	if err := opts.Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call business logic
	resp, err := h.impl.CreateCompany(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(code)
		_ = json.NewEncoder(w).Encode(err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				http.Error(w, "internal validation error", http.StatusInternalServerError)
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 201
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}
