// Code generated by oapi-codegen. DO NOT EDIT.

package api

import (
	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

type CreateUserBody = CreateUserRequest

type ImportUsersBody struct {
	// File CSV file with user data
	File runtime.File `json:"file" validate:"required"`

	// Overwrite Overwrite existing users
	Overwrite *bool `json:"overwrite,omitempty"`
}

func (i ImportUsersBody) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(i.File).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("File", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type UploadUserAvatarBody = runtime.File

type SubmitContactFormBody struct {
	Name    string `json:"name" validate:"required"`
	Email   string `json:"email" validate:"required"`
	Message string `json:"message" validate:"required"`
}

func (s SubmitContactFormBody) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(s))
}

type CreateNoteBody = string

type ProcessXMLDataBody = XMLPayload

type GetOAuthTokenBody struct {
	GrantType    string  `json:"grant_type" validate:"required"`
	ClientID     string  `json:"client_id" validate:"required"`
	ClientSecret *string `json:"client_secret,omitempty"`
}

func (g GetOAuthTokenBody) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type UploadImageBody = runtime.File

type CreateOrderBody = CreateOrderRequest

type CreateCompanyBody = CreateCompanyRequest
