// Code generated by oapi-codegen. DO NOT EDIT.

package api

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

type StatusResponse struct {
	Status *string `json:"status,omitempty"`
	Uptime *int    `json:"uptime,omitempty"`
}

type HealthCheckResponse = string

type ListUsersResponse []User

type CreateUserResponse = User

type CreateUserErrorResponse struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

func (r CreateUserErrorResponse) Error() string {
	res0 := r.Message
	if res0 == nil {
		return "unknown error"
	}
	res1 := *res0
	return res1
}

type ImportUsersResponse = ImportResult

type GetUserResponse = User

type GetUserErrorResponse struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

func (r GetUserErrorResponse) Error() string {
	res0 := r.Message
	if res0 == nil {
		return "unknown error"
	}
	res1 := *res0
	return res1
}

type GetUserAvatarResponse = runtime.File

type GetUserAvatarErrorResponse string

func (r GetUserAvatarErrorResponse) Error() string {
	return "unmapped client error"
}

type SubmitContactFormResponse map[string]any

type CreateNoteResponse = int

type ProcessXMLDataResponse = XMLPayload

type ExportDataResponse = runtime.File

type GetOAuthTokenResponse = TokenResponse

type GetItemsByTypeResponse []string

type SearchResponse struct {
	Search_Response_OneOf *Search_Response_OneOf `json:"-"`
}

func (s SearchResponse) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(s.Search_Response_OneOf)
		if err != nil {
			return nil, fmt.Errorf("Search_Response_OneOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (s *SearchResponse) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if s.Search_Response_OneOf == nil {
		s.Search_Response_OneOf = &Search_Response_OneOf{}
	}

	if err := runtime.UnmarshalJSON(data, s.Search_Response_OneOf); err != nil {
		return fmt.Errorf("Search_Response_OneOf unmarshal: %w", err)
	}

	return nil
}

type GetStatusResponse = StatusResponse

type UploadImageResponse struct {
	ID  *string `json:"id,omitempty"`
	URL *string `json:"url,omitempty"`
}

type ListProductsResponse []Product

type GetCategoryResponse = Category

type GetItemsByStatusResponse []string

type GetUserPostResponse = Post

type GetUserPostErrorResponse = NotFoundError

type CreateOrderResponse = Order

type CreateOrderErrorResponse = ValidationError

type CreateOrderErrorResponseJSON = ConflictError

type CreateCompanyResponse = Company
