// Code generated by oapi-codegen. DO NOT EDIT.
package api

import (
	"net/http"
)

// HealthCheckResponseData wraps the success response with optional headers and status override.
type HealthCheckResponseData struct {
	Body    *HealthCheckResponse
	Headers http.Header
	Status  int // 0 = use default (200)
}

// NewHealthCheckResponseData creates a new HealthCheckResponseData with the given body.
func NewHealthCheckResponseData(body *HealthCheckResponse) *HealthCheckResponseData {
	return &HealthCheckResponseData{Body: body}
}

// WithHeaders sets custom headers on the response.
func (r *HealthCheckResponseData) WithHeaders(h http.Header) *HealthCheckResponseData {
	r.Headers = h
	return r
}

// WithStatus overrides the default status code.
func (r *HealthCheckResponseData) WithStatus(code int) *HealthCheckResponseData {
	r.Status = code
	return r
}

// ListUsersResponseData wraps the success response with optional headers and status override.
type ListUsersResponseData struct {
	Body    *ListUsersResponse
	Headers http.Header
	Status  int // 0 = use default (200)
}

// NewListUsersResponseData creates a new ListUsersResponseData with the given body.
func NewListUsersResponseData(body *ListUsersResponse) *ListUsersResponseData {
	return &ListUsersResponseData{Body: body}
}

// WithHeaders sets custom headers on the response.
func (r *ListUsersResponseData) WithHeaders(h http.Header) *ListUsersResponseData {
	r.Headers = h
	return r
}

// WithStatus overrides the default status code.
func (r *ListUsersResponseData) WithStatus(code int) *ListUsersResponseData {
	r.Status = code
	return r
}

// CreateUserResponseData wraps the success response with optional headers and status override.
type CreateUserResponseData struct {
	Body    *CreateUserResponse
	Headers http.Header
	Status  int // 0 = use default (201)
}

// NewCreateUserResponseData creates a new CreateUserResponseData with the given body.
func NewCreateUserResponseData(body *CreateUserResponse) *CreateUserResponseData {
	return &CreateUserResponseData{Body: body}
}

// WithHeaders sets custom headers on the response.
func (r *CreateUserResponseData) WithHeaders(h http.Header) *CreateUserResponseData {
	r.Headers = h
	return r
}

// WithStatus overrides the default status code.
func (r *CreateUserResponseData) WithStatus(code int) *CreateUserResponseData {
	r.Status = code
	return r
}

// ImportUsersResponseData wraps the success response with optional headers and status override.
type ImportUsersResponseData struct {
	Body    *ImportUsersResponse
	Headers http.Header
	Status  int // 0 = use default (200)
}

// NewImportUsersResponseData creates a new ImportUsersResponseData with the given body.
func NewImportUsersResponseData(body *ImportUsersResponse) *ImportUsersResponseData {
	return &ImportUsersResponseData{Body: body}
}

// WithHeaders sets custom headers on the response.
func (r *ImportUsersResponseData) WithHeaders(h http.Header) *ImportUsersResponseData {
	r.Headers = h
	return r
}

// WithStatus overrides the default status code.
func (r *ImportUsersResponseData) WithStatus(code int) *ImportUsersResponseData {
	r.Status = code
	return r
}

// GetUserResponseData wraps the success response with optional headers and status override.
type GetUserResponseData struct {
	Body    *GetUserResponse
	Headers http.Header
	Status  int // 0 = use default (200)
}

// NewGetUserResponseData creates a new GetUserResponseData with the given body.
func NewGetUserResponseData(body *GetUserResponse) *GetUserResponseData {
	return &GetUserResponseData{Body: body}
}

// WithHeaders sets custom headers on the response.
func (r *GetUserResponseData) WithHeaders(h http.Header) *GetUserResponseData {
	r.Headers = h
	return r
}

// WithStatus overrides the default status code.
func (r *GetUserResponseData) WithStatus(code int) *GetUserResponseData {
	r.Status = code
	return r
}

// DeleteUserResponseData wraps the success response with optional headers and status override.
type DeleteUserResponseData struct {
	Body    *struct{}
	Headers http.Header
	Status  int // 0 = use default (204)
}

// NewDeleteUserResponseData creates a new DeleteUserResponseData with the given body.
func NewDeleteUserResponseData(body *struct{}) *DeleteUserResponseData {
	return &DeleteUserResponseData{Body: body}
}

// WithHeaders sets custom headers on the response.
func (r *DeleteUserResponseData) WithHeaders(h http.Header) *DeleteUserResponseData {
	r.Headers = h
	return r
}

// WithStatus overrides the default status code.
func (r *DeleteUserResponseData) WithStatus(code int) *DeleteUserResponseData {
	r.Status = code
	return r
}

// GetUserAvatarResponseData wraps the success response with optional headers and status override.
type GetUserAvatarResponseData struct {
	Body    *GetUserAvatarResponse
	Headers http.Header
	Status  int // 0 = use default (200)
}

// NewGetUserAvatarResponseData creates a new GetUserAvatarResponseData with the given body.
func NewGetUserAvatarResponseData(body *GetUserAvatarResponse) *GetUserAvatarResponseData {
	return &GetUserAvatarResponseData{Body: body}
}

// WithHeaders sets custom headers on the response.
func (r *GetUserAvatarResponseData) WithHeaders(h http.Header) *GetUserAvatarResponseData {
	r.Headers = h
	return r
}

// WithStatus overrides the default status code.
func (r *GetUserAvatarResponseData) WithStatus(code int) *GetUserAvatarResponseData {
	r.Status = code
	return r
}

// UploadUserAvatarResponseData wraps the success response with optional headers and status override.
type UploadUserAvatarResponseData struct {
	Body    *struct{}
	Headers http.Header
	Status  int // 0 = use default (204)
}

// NewUploadUserAvatarResponseData creates a new UploadUserAvatarResponseData with the given body.
func NewUploadUserAvatarResponseData(body *struct{}) *UploadUserAvatarResponseData {
	return &UploadUserAvatarResponseData{Body: body}
}

// WithHeaders sets custom headers on the response.
func (r *UploadUserAvatarResponseData) WithHeaders(h http.Header) *UploadUserAvatarResponseData {
	r.Headers = h
	return r
}

// WithStatus overrides the default status code.
func (r *UploadUserAvatarResponseData) WithStatus(code int) *UploadUserAvatarResponseData {
	r.Status = code
	return r
}

// SubmitContactFormResponseData wraps the success response with optional headers and status override.
type SubmitContactFormResponseData struct {
	Body    *SubmitContactFormResponse
	Headers http.Header
	Status  int // 0 = use default (200)
}

// NewSubmitContactFormResponseData creates a new SubmitContactFormResponseData with the given body.
func NewSubmitContactFormResponseData(body *SubmitContactFormResponse) *SubmitContactFormResponseData {
	return &SubmitContactFormResponseData{Body: body}
}

// WithHeaders sets custom headers on the response.
func (r *SubmitContactFormResponseData) WithHeaders(h http.Header) *SubmitContactFormResponseData {
	r.Headers = h
	return r
}

// WithStatus overrides the default status code.
func (r *SubmitContactFormResponseData) WithStatus(code int) *SubmitContactFormResponseData {
	r.Status = code
	return r
}

// CreateNoteResponseData wraps the success response with optional headers and status override.
type CreateNoteResponseData struct {
	Body    *CreateNoteResponse
	Headers http.Header
	Status  int // 0 = use default (201)
}

// NewCreateNoteResponseData creates a new CreateNoteResponseData with the given body.
func NewCreateNoteResponseData(body *CreateNoteResponse) *CreateNoteResponseData {
	return &CreateNoteResponseData{Body: body}
}

// WithHeaders sets custom headers on the response.
func (r *CreateNoteResponseData) WithHeaders(h http.Header) *CreateNoteResponseData {
	r.Headers = h
	return r
}

// WithStatus overrides the default status code.
func (r *CreateNoteResponseData) WithStatus(code int) *CreateNoteResponseData {
	r.Status = code
	return r
}

// ProcessXMLDataResponseData wraps the success response with optional headers and status override.
type ProcessXMLDataResponseData struct {
	Body    []byte
	Headers http.Header
	Status  int // 0 = use default (200)
}

// NewProcessXMLDataResponseData creates a new ProcessXMLDataResponseData with the given body.
func NewProcessXMLDataResponseData(body []byte) *ProcessXMLDataResponseData {
	return &ProcessXMLDataResponseData{Body: body}
}

// WithHeaders sets custom headers on the response.
func (r *ProcessXMLDataResponseData) WithHeaders(h http.Header) *ProcessXMLDataResponseData {
	r.Headers = h
	return r
}

// WithStatus overrides the default status code.
func (r *ProcessXMLDataResponseData) WithStatus(code int) *ProcessXMLDataResponseData {
	r.Status = code
	return r
}

// ExportDataResponseData wraps the success response with optional headers and status override.
type ExportDataResponseData struct {
	Body    *ExportDataResponse
	Headers http.Header
	Status  int // 0 = use default (200)
}

// NewExportDataResponseData creates a new ExportDataResponseData with the given body.
func NewExportDataResponseData(body *ExportDataResponse) *ExportDataResponseData {
	return &ExportDataResponseData{Body: body}
}

// WithHeaders sets custom headers on the response.
func (r *ExportDataResponseData) WithHeaders(h http.Header) *ExportDataResponseData {
	r.Headers = h
	return r
}

// WithStatus overrides the default status code.
func (r *ExportDataResponseData) WithStatus(code int) *ExportDataResponseData {
	r.Status = code
	return r
}

// GetOAuthTokenResponseData wraps the success response with optional headers and status override.
type GetOAuthTokenResponseData struct {
	Body    *GetOAuthTokenResponse
	Headers http.Header
	Status  int // 0 = use default (200)
}

// NewGetOAuthTokenResponseData creates a new GetOAuthTokenResponseData with the given body.
func NewGetOAuthTokenResponseData(body *GetOAuthTokenResponse) *GetOAuthTokenResponseData {
	return &GetOAuthTokenResponseData{Body: body}
}

// WithHeaders sets custom headers on the response.
func (r *GetOAuthTokenResponseData) WithHeaders(h http.Header) *GetOAuthTokenResponseData {
	r.Headers = h
	return r
}

// WithStatus overrides the default status code.
func (r *GetOAuthTokenResponseData) WithStatus(code int) *GetOAuthTokenResponseData {
	r.Status = code
	return r
}

// GetItemsByTypeResponseData wraps the success response with optional headers and status override.
type GetItemsByTypeResponseData struct {
	Body    *GetItemsByTypeResponse
	Headers http.Header
	Status  int // 0 = use default (200)
}

// NewGetItemsByTypeResponseData creates a new GetItemsByTypeResponseData with the given body.
func NewGetItemsByTypeResponseData(body *GetItemsByTypeResponse) *GetItemsByTypeResponseData {
	return &GetItemsByTypeResponseData{Body: body}
}

// WithHeaders sets custom headers on the response.
func (r *GetItemsByTypeResponseData) WithHeaders(h http.Header) *GetItemsByTypeResponseData {
	r.Headers = h
	return r
}

// WithStatus overrides the default status code.
func (r *GetItemsByTypeResponseData) WithStatus(code int) *GetItemsByTypeResponseData {
	r.Status = code
	return r
}

// SearchResponseData wraps the success response with optional headers and status override.
type SearchResponseData struct {
	Body    *SearchResponse
	Headers http.Header
	Status  int // 0 = use default (200)
}

// NewSearchResponseData creates a new SearchResponseData with the given body.
func NewSearchResponseData(body *SearchResponse) *SearchResponseData {
	return &SearchResponseData{Body: body}
}

// WithHeaders sets custom headers on the response.
func (r *SearchResponseData) WithHeaders(h http.Header) *SearchResponseData {
	r.Headers = h
	return r
}

// WithStatus overrides the default status code.
func (r *SearchResponseData) WithStatus(code int) *SearchResponseData {
	r.Status = code
	return r
}

// GetStatusResponseData wraps the success response with optional headers and status override.
type GetStatusResponseData struct {
	Body    *GetStatusResponse
	Headers http.Header
	Status  int // 0 = use default (200)
}

// NewGetStatusResponseData creates a new GetStatusResponseData with the given body.
func NewGetStatusResponseData(body *GetStatusResponse) *GetStatusResponseData {
	return &GetStatusResponseData{Body: body}
}

// WithHeaders sets custom headers on the response.
func (r *GetStatusResponseData) WithHeaders(h http.Header) *GetStatusResponseData {
	r.Headers = h
	return r
}

// WithStatus overrides the default status code.
func (r *GetStatusResponseData) WithStatus(code int) *GetStatusResponseData {
	r.Status = code
	return r
}

// UploadImageResponseData wraps the success response with optional headers and status override.
type UploadImageResponseData struct {
	Body    *UploadImageResponse
	Headers http.Header
	Status  int // 0 = use default (201)
}

// NewUploadImageResponseData creates a new UploadImageResponseData with the given body.
func NewUploadImageResponseData(body *UploadImageResponse) *UploadImageResponseData {
	return &UploadImageResponseData{Body: body}
}

// WithHeaders sets custom headers on the response.
func (r *UploadImageResponseData) WithHeaders(h http.Header) *UploadImageResponseData {
	r.Headers = h
	return r
}

// WithStatus overrides the default status code.
func (r *UploadImageResponseData) WithStatus(code int) *UploadImageResponseData {
	r.Status = code
	return r
}

// ListProductsResponseData wraps the success response with optional headers and status override.
type ListProductsResponseData struct {
	Body    *ListProductsResponse
	Headers http.Header
	Status  int // 0 = use default (200)
}

// NewListProductsResponseData creates a new ListProductsResponseData with the given body.
func NewListProductsResponseData(body *ListProductsResponse) *ListProductsResponseData {
	return &ListProductsResponseData{Body: body}
}

// WithHeaders sets custom headers on the response.
func (r *ListProductsResponseData) WithHeaders(h http.Header) *ListProductsResponseData {
	r.Headers = h
	return r
}

// WithStatus overrides the default status code.
func (r *ListProductsResponseData) WithStatus(code int) *ListProductsResponseData {
	r.Status = code
	return r
}

// GetCategoryResponseData wraps the success response with optional headers and status override.
type GetCategoryResponseData struct {
	Body    *GetCategoryResponse
	Headers http.Header
	Status  int // 0 = use default (200)
}

// NewGetCategoryResponseData creates a new GetCategoryResponseData with the given body.
func NewGetCategoryResponseData(body *GetCategoryResponse) *GetCategoryResponseData {
	return &GetCategoryResponseData{Body: body}
}

// WithHeaders sets custom headers on the response.
func (r *GetCategoryResponseData) WithHeaders(h http.Header) *GetCategoryResponseData {
	r.Headers = h
	return r
}

// WithStatus overrides the default status code.
func (r *GetCategoryResponseData) WithStatus(code int) *GetCategoryResponseData {
	r.Status = code
	return r
}

// GetItemsByStatusResponseData wraps the success response with optional headers and status override.
type GetItemsByStatusResponseData struct {
	Body    *GetItemsByStatusResponse
	Headers http.Header
	Status  int // 0 = use default (200)
}

// NewGetItemsByStatusResponseData creates a new GetItemsByStatusResponseData with the given body.
func NewGetItemsByStatusResponseData(body *GetItemsByStatusResponse) *GetItemsByStatusResponseData {
	return &GetItemsByStatusResponseData{Body: body}
}

// WithHeaders sets custom headers on the response.
func (r *GetItemsByStatusResponseData) WithHeaders(h http.Header) *GetItemsByStatusResponseData {
	r.Headers = h
	return r
}

// WithStatus overrides the default status code.
func (r *GetItemsByStatusResponseData) WithStatus(code int) *GetItemsByStatusResponseData {
	r.Status = code
	return r
}

// GetUserPostResponseData wraps the success response with optional headers and status override.
type GetUserPostResponseData struct {
	Body    *GetUserPostResponse
	Headers http.Header
	Status  int // 0 = use default (200)
}

// NewGetUserPostResponseData creates a new GetUserPostResponseData with the given body.
func NewGetUserPostResponseData(body *GetUserPostResponse) *GetUserPostResponseData {
	return &GetUserPostResponseData{Body: body}
}

// WithHeaders sets custom headers on the response.
func (r *GetUserPostResponseData) WithHeaders(h http.Header) *GetUserPostResponseData {
	r.Headers = h
	return r
}

// WithStatus overrides the default status code.
func (r *GetUserPostResponseData) WithStatus(code int) *GetUserPostResponseData {
	r.Status = code
	return r
}

// CreateOrderResponseData wraps the success response with optional headers and status override.
type CreateOrderResponseData struct {
	Body    *CreateOrderResponse
	Headers http.Header
	Status  int // 0 = use default (201)
}

// NewCreateOrderResponseData creates a new CreateOrderResponseData with the given body.
func NewCreateOrderResponseData(body *CreateOrderResponse) *CreateOrderResponseData {
	return &CreateOrderResponseData{Body: body}
}

// WithHeaders sets custom headers on the response.
func (r *CreateOrderResponseData) WithHeaders(h http.Header) *CreateOrderResponseData {
	r.Headers = h
	return r
}

// WithStatus overrides the default status code.
func (r *CreateOrderResponseData) WithStatus(code int) *CreateOrderResponseData {
	r.Status = code
	return r
}

// CreateCompanyResponseData wraps the success response with optional headers and status override.
type CreateCompanyResponseData struct {
	Body    *CreateCompanyResponse
	Headers http.Header
	Status  int // 0 = use default (201)
}

// NewCreateCompanyResponseData creates a new CreateCompanyResponseData with the given body.
func NewCreateCompanyResponseData(body *CreateCompanyResponse) *CreateCompanyResponseData {
	return &CreateCompanyResponseData{Body: body}
}

// WithHeaders sets custom headers on the response.
func (r *CreateCompanyResponseData) WithHeaders(h http.Header) *CreateCompanyResponseData {
	r.Headers = h
	return r
}

// WithStatus overrides the default status code.
func (r *CreateCompanyResponseData) WithStatus(code int) *CreateCompanyResponseData {
	r.Status = code
	return r
}
