// Code generated by oapi-codegen. DO NOT EDIT.

package api

import (
	"fmt"
	"time"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

type SearchItem struct {
	ID          string  `json:"id" validate:"required"`
	Title       string  `json:"title" validate:"required"`
	Description *string `json:"description,omitempty"`
}

func (s SearchItem) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(s))
}

type User struct {
	ID    string `json:"id" validate:"required"`
	Name  string `json:"name" validate:"required"`
	Email string `json:"email" validate:"required"`
}

func (u User) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(u))
}

type CreateUserRequest struct {
	Name  string `json:"name" validate:"required"`
	Email string `json:"email" validate:"required"`
}

func (c CreateUserRequest) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(c))
}

type ImportResult struct {
	Imported *int     `json:"imported,omitempty"`
	Skipped  *int     `json:"skipped,omitempty"`
	Errors   []string `json:"errors,omitempty"`
}

type Error struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

type TokenResponse struct {
	AccessToken string `json:"access_token" validate:"required"`
	TokenType   string `json:"token_type" validate:"required"`
	ExpiresIn   *int   `json:"expires_in,omitempty"`
}

func (t TokenResponse) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(t))
}

type XMLPayload struct {
	Name  *string `json:"name,omitempty"`
	Value *string `json:"value,omitempty"`
}

type Category struct {
	ID          int     `json:"id" validate:"required"`
	Name        string  `json:"name" validate:"required"`
	Description *string `json:"description,omitempty"`
}

func (c Category) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(c))
}

type Product struct {
	ID    string   `json:"id" validate:"required"`
	Name  string   `json:"name" validate:"required"`
	Price float32  `json:"price" validate:"required"`
	Tags  []string `json:"tags,omitempty"`
}

func (p Product) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(p))
}

type Post struct {
	ID        string     `json:"id" validate:"required"`
	UserID    string     `json:"userId" validate:"required"`
	Title     string     `json:"title" validate:"required"`
	Content   string     `json:"content" validate:"required"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
}

func (p Post) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(p))
}

type NotFoundError struct {
	Code    string `json:"code" validate:"required"`
	Message string `json:"message" validate:"required"`

	// Resource The resource type that was not found
	Resource string `json:"resource" validate:"required"`
}

func (n NotFoundError) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(n))
}

func (s NotFoundError) Error() string {
	return "unmapped client error"
}

type ValidationError struct {
	Code    string                 `json:"code" validate:"required"`
	Message string                 `json:"message" validate:"required"`
	Fields  ValidationError_Fields `json:"fields" validate:"required"`
}

func (v ValidationError) Validate() error {
	var errors runtime.ValidationErrors
	if err := typesValidator.Var(v.Code, "required"); err != nil {
		errors = errors.Append("Code", err)
	}
	if err := typesValidator.Var(v.Message, "required"); err != nil {
		errors = errors.Append("Message", err)
	}
	if v, ok := any(v.Fields).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Fields", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (s ValidationError) Error() string {
	return "unmapped client error"
}

type ValidationError_Fields []ValidationError_Fields_Item

func (v ValidationError_Fields) Validate() error {
	var errors runtime.ValidationErrors
	for i, item := range v {
		if v, ok := any(item).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append(fmt.Sprintf("[%d]", i), err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type ValidationError_Fields_Item struct {
	Field     *string `json:"field,omitempty"`
	ErrorData *string `json:"error,omitempty"`
}

type ConflictError struct {
	Code    string `json:"code" validate:"required"`
	Message string `json:"message" validate:"required"`

	// ExistingID ID of the conflicting resource
	ExistingID *string `json:"existingId,omitempty"`
}

func (c ConflictError) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(c))
}

type CreateOrderRequest struct {
	ProductID string  `json:"productId" validate:"required"`
	Quantity  int     `json:"quantity" validate:"required,gte=1"`
	Notes     *string `json:"notes,omitempty"`
}

func (c CreateOrderRequest) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(c))
}

type Order struct {
	ID        string      `json:"id" validate:"required"`
	ProductID string      `json:"productId" validate:"required"`
	Quantity  int         `json:"quantity" validate:"required"`
	Status    OrderStatus `json:"status" validate:"required"`
	CreatedAt *time.Time  `json:"createdAt,omitempty"`
}

func (o Order) Validate() error {
	var errors runtime.ValidationErrors
	if err := typesValidator.Var(o.ID, "required"); err != nil {
		errors = errors.Append("ID", err)
	}
	if err := typesValidator.Var(o.ProductID, "required"); err != nil {
		errors = errors.Append("ProductID", err)
	}
	if err := typesValidator.Var(o.Quantity, "required"); err != nil {
		errors = errors.Append("Quantity", err)
	}
	if v, ok := any(o.Status).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Status", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type Address struct {
	Street     string  `json:"street" validate:"required"`
	City       string  `json:"city" validate:"required"`
	State      *string `json:"state,omitempty"`
	PostalCode *string `json:"postalCode,omitempty"`
	Country    string  `json:"country" validate:"required"`
}

func (a Address) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(a))
}

type CreateCompanyRequest struct {
	Name     string                         `json:"name" validate:"required"`
	Address  Address                        `json:"address"`
	Contacts *CreateCompanyRequest_Contacts `json:"contacts,omitempty"`
}

func (c CreateCompanyRequest) Validate() error {
	var errors runtime.ValidationErrors
	if err := typesValidator.Var(c.Name, "required"); err != nil {
		errors = errors.Append("Name", err)
	}
	if v, ok := any(c.Address).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Address", err)
		}
	}
	if c.Contacts != nil {
		if v, ok := any(c.Contacts).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Contacts", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type CreateCompanyRequest_Contacts []CreateCompanyRequest_Contacts_Item

type CreateCompanyRequest_Contacts_Item struct {
	Name  *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
	Phone *string `json:"phone,omitempty"`
}

type Company struct {
	ID        string            `json:"id" validate:"required"`
	Name      string            `json:"name" validate:"required"`
	Address   Address           `json:"address"`
	Contacts  *Company_Contacts `json:"contacts,omitempty"`
	CreatedAt *time.Time        `json:"createdAt,omitempty"`
}

func (c Company) Validate() error {
	var errors runtime.ValidationErrors
	if err := typesValidator.Var(c.ID, "required"); err != nil {
		errors = errors.Append("ID", err)
	}
	if err := typesValidator.Var(c.Name, "required"); err != nil {
		errors = errors.Append("Name", err)
	}
	if v, ok := any(c.Address).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Address", err)
		}
	}
	if c.Contacts != nil {
		if v, ok := any(c.Contacts).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Contacts", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type Company_Contacts []Company_Contacts_Item

type Company_Contacts_Item struct {
	Name  *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
	Phone *string `json:"phone,omitempty"`
}
