// Code generated by oapi-codegen. DO NOT EDIT.

package api

import (
	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

type Search_Response_OneOf struct {
	runtime.Either[User, SearchItem]
}

func (s *Search_Response_OneOf) Validate() error {
	if s.IsA() {
		if v, ok := any(s.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if s.IsB() {
		if v, ok := any(s.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}
