// Code generated by oapi-codegen. DO NOT EDIT.

package example6

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

// Client is the client for the API implementing the Client interface.
type Client struct {
	apiClient runtime.APIClient
}

// NewClient creates a new instance of the Client client.
func NewClient(apiClient runtime.APIClient) *Client {
	return &Client{apiClient: apiClient}
}

// NewDefaultClient creates a new instance of the Client client with default api client.
func NewDefaultClient(baseURL string, opts ...runtime.APIClientOption) (*Client, error) {
	apiClient, err := runtime.NewAPIClient(baseURL, opts...)
	if err != nil {
		return nil, fmt.Errorf("error creating API client: %w", err)
	}
	return &Client{apiClient: apiClient}, nil
}

// ClientInterface is the interface for the API client.
type ClientInterface interface {
	UpdateUser(ctx context.Context, options *UpdateUserRequestOptions, reqEditors ...runtime.RequestEditorFn) (*UpdateUserResponse, error)
}

func (c *Client) UpdateUser(ctx context.Context, options *UpdateUserRequestOptions, reqEditors ...runtime.RequestEditorFn) (*UpdateUserResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL:  c.apiClient.GetBaseURL() + "/users",
		Method:      "PUT",
		Options:     options,
		ContentType: "application/json",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*UpdateUserResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 202 {
			target := new(UpdateUserErrorResponse)
			// Handle empty error response body gracefully - skip unmarshal if no content
			if len(bodyBytes) > 0 {
				if err = json.Unmarshal(bodyBytes, target); err != nil {
					return nil, &runtime.ResponseDecodeError{
						StatusCode:    resp.StatusCode,
						ContentType:   resp.Headers.Get("Content-Type"),
						ContentLength: len(bodyBytes),
						TargetType:    "UpdateUserErrorResponse",
						Body:          bodyBytes,
						Err:           err,
					}
				}
			}
			// Return error with (possibly empty) target
			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(UpdateUserResponse)
		// Handle empty response body gracefully
		if len(bodyBytes) == 0 {
			return target, nil
		}
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			return nil, &runtime.ResponseDecodeError{
				StatusCode:    resp.StatusCode,
				ContentType:   resp.Headers.Get("Content-Type"),
				ContentLength: len(bodyBytes),
				TargetType:    "UpdateUserResponse",
				Body:          bodyBytes,
				Err:           err,
			}
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/users")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

var _ ClientInterface = (*Client)(nil)
