// Code generated by oapi-codegen. DO NOT EDIT.

package example6

import (
	"fmt"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

type UserType string

const (
	UserTypeCompany    UserType = "company"
	UserTypeIndividual UserType = "individual"
)

// Validate checks if the UserType value is valid
func (u UserType) Validate() error {
	switch u {
	case UserTypeCompany, UserTypeIndividual:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid UserType value, got: %v", u))
	}
}
