// Code generated by oapi-codegen. DO NOT EDIT.

package example6

import (
	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

type UpdateUserResponse = User

type UpdateUserErrorResponse struct {
	Message *string `json:"message,omitempty"`
	Code    *string `json:"code,omitempty"`
}

func (r UpdateUserErrorResponse) Error() string {
	res0 := r.Message
	if res0 == nil {
		return "unknown error"
	}
	res1 := *res0
	return res1
}

func NewUpdateUserErrorResponse(message string) UpdateUserErrorResponse {
	return UpdateUserErrorResponse{Message: runtime.Ptr(message)}
}
