// Code generated by oapi-codegen. DO NOT EDIT.

package noendpoints

import (
	"github.com/mark3labs/mcp-go/server"
)

// MCPToolsOption configures the MCPTools.
type MCPToolsOption func(*MCPTools)

// MCPTools registers API operations as MCP tools.
// It uses an HTTP client to make API calls.
//
// TODO: Add MCPAdapter support for direct service calls (similar to HTTPAdapter)
// that would allow calling ServiceInterface directly without HTTP overhead,
// including proper request validation.
type MCPTools struct {
	server *server.MCPServer
	client ClientInterface
}

// NewMCPTools creates a new MCPTools and registers all tools with the MCP server.
func NewMCPTools(s *server.MCPServer, opts ...MCPToolsOption) *MCPTools {
	t := &MCPTools{server: s}
	for _, opt := range opts {
		opt(t)
	}
	t.registerAll()
	return t
}

// WithClient configures MCPTools to use an HTTP client for API calls.
func WithClient(client ClientInterface) MCPToolsOption {
	return func(t *MCPTools) {
		t.client = client
	}
}

func (t *MCPTools) registerAll() {
}
