// Code generated by oapi-codegen. DO NOT EDIT.

package filteringbytag

import (
	"github.com/go-playground/validator/v10"
)

type GetClientResponse struct {
	Name string `json:"name" validate:"required"`
	Age  *int   `json:"age,omitempty"`
}

var schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type Person struct {
	Name string `json:"name" validate:"required"`
	Age  *int   `json:"age,omitempty"`
}

func (p Person) Validate() error {
	return schemaTypesValidate.Struct(p)
}
