// Code generated by oapi-codegen. DO NOT EDIT.

package circularmutual

import (
	"encoding/json"
	"fmt"

	"github.com/doordash/oapi-codegen/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type FileObject string

const (
	FileObjectFile FileObject = "file"
)

type FilePurpose string

const (
	AccountRequirement     FilePurpose = "account_requirement"
	AdditionalVerification FilePurpose = "additional_verification"
	BusinessIcon           FilePurpose = "business_icon"
)

type FileLinksObject string

const (
	List FileLinksObject = "list"
)

type FileLinkObject string

const (
	FileLinkObjectFileLink FileLinkObject = "file_link"
)

type GetFilesResponse []struct {
	GetFiles_Response_OneOf *GetFiles_Response_OneOf `json:",omitempty"`
}

var schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type File struct {
	Filename *string `json:"filename,omitempty" validate:"omitempty,max=5000"`
	ID       string  `json:"id" validate:"required,max=5000"`
	Author   *struct {
		File_Author_AnyOf *File_Author_AnyOf `json:",omitempty"`
	} `json:"author,omitempty"`
	Links *struct {
		Data    []FileLink      `json:"data" validate:"required"`
		HasMore bool            `json:"has_more"`
		Object  FileLinksObject `json:"object" validate:"required"`
		URL     string          `json:"url" validate:"required,max=5000"`
	} `json:"links,omitempty"`
	Object  FileObject  `json:"object" validate:"required"`
	Purpose FilePurpose `json:"purpose" validate:"required"`
	Size    int         `json:"size" validate:"required"`
	Title   *string     `json:"title,omitempty" validate:"omitempty,max=5000"`
}

func (f File) Validate() error {
	return schemaTypesValidate.Struct(f)
}

type FileLink struct {
	Created int `json:"created" validate:"required"`
	File    struct {
		FileLink_File_AnyOf *FileLink_File_AnyOf `json:",omitempty"`
	} `json:"file" validate:"required"`
	ID       string            `json:"id" validate:"required,max=5000"`
	Livemode *bool             `json:"livemode,omitempty"`
	Metadata map[string]string `json:"metadata,omitempty"`
	Object   *FileLinkObject   `json:"object,omitempty"`
	URL      *string           `json:"url,omitempty" validate:"omitempty,max=5000"`
}

func (f FileLink) Validate() error {
	return schemaTypesValidate.Struct(f)
}

type User struct {
	ID     string `json:"id" validate:"required,max=50"`
	Avatar *struct {
		User_Avatar_AnyOf *User_Avatar_AnyOf `json:",omitempty"`
	} `json:"avatar,omitempty"`
}

func (u User) Validate() error {
	return schemaTypesValidate.Struct(u)
}

func UnmarshalAs[T any](v json.RawMessage) (T, error) {
	var res T
	err := json.Unmarshal(v, &res)
	return res, err
}

func marshalJSONWithDiscriminator(data []byte, field, value string) ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)
	if data != nil {
		if err := json.Unmarshal(data, &object); err != nil {
			return nil, err
		}
	}

	object[field], err = json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling discriminator field '%s': %w", field, err)
	}

	return json.Marshal(object)
}

type GetFiles_Response_OneOf struct {
	runtime.Either[string, File]
}

func (g *GetFiles_Response_OneOf) MarshalJSON() ([]byte, error) {
	data := g.Value()
	if data == nil {
		return nil, nil
	}

	obj, err := json.Marshal(data)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

func (g *GetFiles_Response_OneOf) UnmarshalJSON(data []byte) error {
	return g.Unmarshal(data)
}

type File_Author_AnyOf struct {
	runtime.Either[User, string]
}

func (f *File_Author_AnyOf) MarshalJSON() ([]byte, error) {
	data := f.Value()
	if data == nil {
		return nil, nil
	}

	obj, err := json.Marshal(data)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

func (f *File_Author_AnyOf) UnmarshalJSON(data []byte) error {
	return f.Unmarshal(data)
}

type FileLink_File_AnyOf struct {
	runtime.Either[string, File]
}

func (f *FileLink_File_AnyOf) MarshalJSON() ([]byte, error) {
	data := f.Value()
	if data == nil {
		return nil, nil
	}

	obj, err := json.Marshal(data)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

func (f *FileLink_File_AnyOf) UnmarshalJSON(data []byte) error {
	return f.Unmarshal(data)
}

type User_Avatar_AnyOf struct {
	runtime.Either[File, string]
}

func (u *User_Avatar_AnyOf) MarshalJSON() ([]byte, error) {
	data := u.Value()
	if data == nil {
		return nil, nil
	}

	obj, err := json.Marshal(data)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

func (u *User_Avatar_AnyOf) UnmarshalJSON(data []byte) error {
	return u.Unmarshal(data)
}
