// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"encoding/json"
	"fmt"

	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

var schemaTypesValidate *validator.Validate

func init() {
	schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(schemaTypesValidate)
}

type Items []any

type Location map[string]any

func (l Location) Validate() error {
	return nil
}

type Users map[string]User

func (u Users) Validate() error {
	return nil
}

type User struct {
	Address map[string]any `json:"address,omitempty"`
}

func (u User) Validate() error {
	return schemaTypesValidate.Struct(u)
}

type Pick1 map[string]Pick1_AdditionalProperties

func (p Pick1) Validate() error {
	for k, v := range p {
		if validator, ok := any(v).(runtime.Validator); ok {
			if err := validator.Validate(); err != nil {
				return runtime.NewValidationErrorFromError(k, err)
			}
		}
	}
	return nil
}

type ReferenceWithRequiredExtra struct {
	Index                *Reference           `json:"index,omitempty"`
	AdditionalProperties map[string]Reference `json:"-"`
}

func (r ReferenceWithRequiredExtra) Validate() error {
	if r.Index != nil {
		if v, ok := any(r.Index).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("Index", err)
			}
		}
	}
	return nil
}

// Getter for additional properties for ReferenceWithRequiredExtra. Returns the specified
// element and whether it was found
func (r ReferenceWithRequiredExtra) Get(fieldName string) (value Reference, found bool) {
	if r.AdditionalProperties != nil {
		value, found = r.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ReferenceWithRequiredExtra
func (r *ReferenceWithRequiredExtra) Set(fieldName string, value Reference) {
	if r.AdditionalProperties == nil {
		r.AdditionalProperties = make(map[string]Reference)
	}
	r.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ReferenceWithRequiredExtra to handle AdditionalProperties
func (r *ReferenceWithRequiredExtra) UnmarshalJSON(data []byte) error {
	object := make(map[string]json.RawMessage)
	if err := json.Unmarshal(data, &object); err != nil {
		return err
	}

	if raw, found := object["index"]; found {
		if err := json.Unmarshal(raw, &r.Index); err != nil {
			return fmt.Errorf("error reading 'index': %w", err)
		}
		delete(object, "index")
	}

	if len(object) != 0 {
		r.AdditionalProperties = make(map[string]Reference)
		for fieldName, fieldBuf := range object {
			var fieldVal Reference
			if err := json.Unmarshal(fieldBuf, &fieldVal); err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			r.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ReferenceWithRequiredExtra to handle AdditionalProperties
func (r ReferenceWithRequiredExtra) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if r.Index != nil {
		object["index"], err = json.Marshal(r.Index)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'index': %w", err)
		}
	}

	for fieldName, field := range r.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

type RouteWithOptionalExtra struct {
	Index                *Route           `json:"index,omitempty"`
	AdditionalProperties map[string]Route `json:"-"`
}

func (r RouteWithOptionalExtra) Validate() error {
	if r.Index != nil {
		if v, ok := any(r.Index).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("Index", err)
			}
		}
	}
	return nil
}

// Getter for additional properties for RouteWithOptionalExtra. Returns the specified
// element and whether it was found
func (r RouteWithOptionalExtra) Get(fieldName string) (value Route, found bool) {
	if r.AdditionalProperties != nil {
		value, found = r.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for RouteWithOptionalExtra
func (r *RouteWithOptionalExtra) Set(fieldName string, value Route) {
	if r.AdditionalProperties == nil {
		r.AdditionalProperties = make(map[string]Route)
	}
	r.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for RouteWithOptionalExtra to handle AdditionalProperties
func (r *RouteWithOptionalExtra) UnmarshalJSON(data []byte) error {
	object := make(map[string]json.RawMessage)
	if err := json.Unmarshal(data, &object); err != nil {
		return err
	}

	if raw, found := object["index"]; found {
		if err := json.Unmarshal(raw, &r.Index); err != nil {
			return fmt.Errorf("error reading 'index': %w", err)
		}
		delete(object, "index")
	}

	if len(object) != 0 {
		r.AdditionalProperties = make(map[string]Route)
		for fieldName, fieldBuf := range object {
			var fieldVal Route
			if err := json.Unmarshal(fieldBuf, &fieldVal); err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			r.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for RouteWithOptionalExtra to handle AdditionalProperties
func (r RouteWithOptionalExtra) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if r.Index != nil {
		object["index"], err = json.Marshal(r.Index)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'index': %w", err)
		}
	}

	for fieldName, field := range r.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

type Route = string

type Reference = string

type ConfigWithMinProps map[string]string

func (c ConfigWithMinProps) Validate() error {
	if c == nil {
		return nil
	}
	if len(c) < 1 {
		return runtime.NewValidationError("", fmt.Sprintf("must have at least 1 properties, got %d", len(c)))
	}
	return nil
}

type ConfigWithMaxProps map[string]string

func (c ConfigWithMaxProps) Validate() error {
	if c == nil {
		return nil
	}
	if len(c) > 5 {
		return runtime.NewValidationError("", fmt.Sprintf("must have at most 5 properties, got %d", len(c)))
	}
	return nil
}

type ConfigWithBothProps map[string]int

func (c ConfigWithBothProps) Validate() error {
	if c == nil {
		return nil
	}
	if len(c) < 2 {
		return runtime.NewValidationError("", fmt.Sprintf("must have at least 2 properties, got %d", len(c)))
	}
	if len(c) > 10 {
		return runtime.NewValidationError("", fmt.Sprintf("must have at most 10 properties, got %d", len(c)))
	}
	return nil
}

type UsersWithRequiredFields map[string]UsersWithRequiredFields_AdditionalProperties

func (u UsersWithRequiredFields) Validate() error {
	for k, v := range u {
		if validator, ok := any(v).(runtime.Validator); ok {
			if err := validator.Validate(); err != nil {
				return runtime.NewValidationErrorFromError(k, err)
			}
		}
	}
	return nil
}

type ArrayWithMinItems []string

func (a ArrayWithMinItems) Validate() error {
	if a == nil {
		return nil
	}
	if len(a) < 1 {
		return runtime.NewValidationError("", fmt.Sprintf("must have at least 1 items, got %d", len(a)))
	}
	if len(a) > 100 {
		return runtime.NewValidationError("", fmt.Sprintf("must have at most 100 items, got %d", len(a)))
	}
	return nil
}

type Username string

func (u Username) Validate() error {
	return nil
}

type UserProfile struct {
	Name string `json:"name" validate:"required,max=20,min=3"`
}

func (u UserProfile) Validate() error {
	return schemaTypesValidate.Struct(u)
}

type TagsWithLength map[string]string

func (t TagsWithLength) Validate() error {
	return nil
}

var unionTypesValidate *validator.Validate

func init() {
	unionTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(unionTypesValidate)
}

type Pick1_AdditionalProperties struct {
	Pick1_AdditionalProperties_OneOf *Pick1_AdditionalProperties_OneOf `json:"-"`
}

func (p Pick1_AdditionalProperties) Validate() error {
	if p.Pick1_AdditionalProperties_OneOf != nil {
		if v, ok := any(p.Pick1_AdditionalProperties_OneOf).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("Pick1_AdditionalProperties_OneOf", err)
			}
		}
	}
	return nil
}

type UsersWithRequiredFields_AdditionalProperties struct {
	Name  string `json:"name" validate:"required"`
	Email string `json:"email" validate:"required"`
	Age   *int   `json:"age,omitempty"`
}

func (u UsersWithRequiredFields_AdditionalProperties) Validate() error {
	return unionTypesValidate.Struct(u)
}

func UnmarshalAs[T any](v json.RawMessage) (T, error) {
	var res T
	err := json.Unmarshal(v, &res)
	return res, err
}

func marshalJSONWithDiscriminator(data []byte, field, value string) ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)
	if data != nil {
		if err := json.Unmarshal(data, &object); err != nil {
			return nil, err
		}
	}

	object[field], err = json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling discriminator field '%s': %w", field, err)
	}

	return json.Marshal(object)
}

type Pick1_AdditionalProperties_OneOf struct {
	runtime.Either[string, float32]
}

func (p *Pick1_AdditionalProperties_OneOf) Validate() error {
	if p.IsA() {
		if v, ok := any(p.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if p.IsB() {
		if v, ok := any(p.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}
