// Code generated by oapi-codegen. DO NOT EDIT.

package oneof

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/doordash/oapi-codegen/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

// Client is the client for the API implementing the Client interface.
type Client struct {
	apiClient runtime.APIClient
}

// NewClient creates a new instance of the Client client.
func NewClient(apiClient runtime.APIClient) *Client {
	return &Client{apiClient: apiClient}
}

// NewDefaultClient creates a new instance of the Client client with default api client.
func NewDefaultClient(baseURL string, opts ...runtime.APIClientOption) (*Client, error) {
	apiClient, err := runtime.NewAPIClient(baseURL, opts...)
	if err != nil {
		return nil, fmt.Errorf("error creating API client: %w", err)
	}
	return &Client{apiClient: apiClient}, nil
}

// ClientInterface is the interface for the API client.
type ClientInterface interface {
	// ProcessPayment Process payment operations
	ProcessPayment(ctx context.Context, options *ProcessPaymentRequestOptions, reqEditors ...runtime.RequestEditorFn) (*struct{}, error)
}

// ProcessPayment Process payment operations
func (c *Client) ProcessPayment(ctx context.Context, options *ProcessPaymentRequestOptions, reqEditors ...runtime.RequestEditorFn) (*struct{}, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL:  c.apiClient.GetBaseURL() + "/service/gateway",
		Method:      "POST",
		Options:     options,
		ContentType: "application/x-www-form-urlencoded",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*struct{}, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			return nil, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(struct{})
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/service/gateway")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

var _ ClientInterface = (*Client)(nil)

var clientOptionsValidate = validator.New(validator.WithRequiredStructEnabled())

// ProcessPaymentRequestOptions is the options needed to make a request to ProcessPayment.
type ProcessPaymentRequestOptions struct {
	Body *ProcessPaymentBody
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *ProcessPaymentRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if err := clientOptionsValidate.Struct(o.Body); err != nil {
		errors = append(errors, runtime.NewValidationErrorsFromErrors("Body", []error{err})...)
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *ProcessPaymentRequestOptions) GetPathParams() (map[string]any, error) {
	return nil, nil
}

// GetQuery returns the query params as a map.
func (o *ProcessPaymentRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *ProcessPaymentRequestOptions) GetBody() any {
	return o.Body
}

// GetHeader returns the headers as a map.
func (o *ProcessPaymentRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

func asMap[V any](v any) (map[string]V, error) {
	if v == nil {
		return nil, nil
	}
	res, err := json.Marshal(v)
	if err != nil {
		return nil, err
	}

	var m map[string]V
	err = json.Unmarshal(res, &m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

var bodyTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type ProcessPaymentBody = ProcessPaymentBodyOneOf

var schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type ResponseA struct {
	A *string `json:"a,omitempty"`
}

func (r ResponseA) Validate() error {
	return schemaTypesValidate.Struct(r)
}

type ResponseB struct {
	B *string `json:"b,omitempty"`
}

func (r ResponseB) Validate() error {
	return schemaTypesValidate.Struct(r)
}

type ResponseC struct {
	C *string `json:"c,omitempty"`
}

func (r ResponseC) Validate() error {
	return schemaTypesValidate.Struct(r)
}

func UnmarshalAs[T any](v json.RawMessage) (T, error) {
	var res T
	err := json.Unmarshal(v, &res)
	return res, err
}

func marshalJSONWithDiscriminator(data []byte, field, value string) ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)
	if data != nil {
		if err := json.Unmarshal(data, &object); err != nil {
			return nil, err
		}
	}

	object[field], err = json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling discriminator field '%s': %w", field, err)
	}

	return json.Marshal(object)
}

type ProcessPaymentBodyOneOf struct {
	union json.RawMessage
}

// Raw returns the union data inside the ProcessPaymentBodyOneOf as bytes
func (p *ProcessPaymentBodyOneOf) Raw() json.RawMessage {
	return p.union
}

// AsResponseA returns the union data inside the ProcessPaymentBodyOneOf as a ResponseA
func (p *ProcessPaymentBodyOneOf) AsResponseA() (ResponseA, error) {
	return UnmarshalAs[ResponseA](p.union)
}

// FromResponseA overwrites any union data inside the ProcessPaymentBodyOneOf as the provided ResponseA
func (p *ProcessPaymentBodyOneOf) FromResponseA(v ResponseA) error {
	bts, err := json.Marshal(v)
	p.union = bts
	return err
}

// AsResponseB returns the union data inside the ProcessPaymentBodyOneOf as a ResponseB
func (p *ProcessPaymentBodyOneOf) AsResponseB() (ResponseB, error) {
	return UnmarshalAs[ResponseB](p.union)
}

// FromResponseB overwrites any union data inside the ProcessPaymentBodyOneOf as the provided ResponseB
func (p *ProcessPaymentBodyOneOf) FromResponseB(v ResponseB) error {
	bts, err := json.Marshal(v)
	p.union = bts
	return err
}

// AsResponseC returns the union data inside the ProcessPaymentBodyOneOf as a ResponseC
func (p *ProcessPaymentBodyOneOf) AsResponseC() (ResponseC, error) {
	return UnmarshalAs[ResponseC](p.union)
}

// FromResponseC overwrites any union data inside the ProcessPaymentBodyOneOf as the provided ResponseC
func (p *ProcessPaymentBodyOneOf) FromResponseC(v ResponseC) error {
	bts, err := json.Marshal(v)
	p.union = bts
	return err
}

func (p ProcessPaymentBodyOneOf) MarshalJSON() ([]byte, error) {
	bts, err := p.union.MarshalJSON()

	return bts, err
}

func (p *ProcessPaymentBodyOneOf) UnmarshalJSON(bts []byte) error {
	err := p.union.UnmarshalJSON(bts)

	return err
}
