// Code generated by oapi-codegen. DO NOT EDIT.

package conflicting

import (
	"github.com/go-playground/validator/v10"
)

var bodyTypesValidate = validator.New(validator.WithRequiredStructEnabled())

// CreatePaymentBody The `CreatePaymentRequest` object.
type CreatePaymentBody = CreatePaymentRequest

type CreatePaymentResponseJSON = Payment

// CreatePaymentResponseJSON201 Schema for The `CreatePaymentResponse` object.
type CreatePaymentResponseJSON201 = CreatePaymentResponse

var schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type Payment struct {
	RequestPaymentID *string `json:"requestPaymentId,omitempty"`
}

func (p Payment) Validate() error {
	return schemaTypesValidate.Struct(p)
}

// CreatePaymentRequest The `CreatePaymentRequest` object.
type CreatePaymentRequest struct {
	MinimumUserAge      *int    `json:"minimumUserAge,omitempty"`
	CustomerInteraction *string `json:"customerInteraction,omitempty"`
}

func (c CreatePaymentRequest) Validate() error {
	return schemaTypesValidate.Struct(c)
}

// CreatePaymentResponse Schema for The `CreatePaymentResponse` object.
type CreatePaymentResponse struct {
	RedirectURL *string `json:"redirectUrl,omitempty"`
}

func (c CreatePaymentResponse) Validate() error {
	return schemaTypesValidate.Struct(c)
}
