openapi: "3.0.0"
info:
  version: 1.0.0
  title: Using complex schemas
  description: An example of `anyOf`, `allOf` and `oneOf`
paths:
  /foo:
    get:
      responses:
        '200':
          description: Foo
          content:
            application/json:
              schema:
                type: object
  /pet:
    get:
      responses:
        '200':
          description: Get a pet
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'

components:
  schemas:
    # base types
    Client:
      type: object
      required:
        - name
      properties:
        name:
          type: string

    Identity:
      type: object
      required:
        - issuer
      properties:
        issuer:
          type: string

    # anyOf results in a type that has an `AsClient`/`FromClient` and an `AsIdentity`/`FromIdentity` method
    # so you can choose which of them you want to retrieve
    ClientAndMaybeIdentity:
      properties:
        entity:
          anyOf:
            - $ref: '#/components/schemas/Client'
            - $ref: '#/components/schemas/Identity'
        type:
          type: string
          enum:
            - client
            - identity
            - client-with-id
      required:
        - type

    # oneOf results in a type that has an `AsClient`/`FromClient` and an `AsString`/`FromString` method
    # so you can choose which of them you want to retrieve
    ClientOrId:
      oneOf:
        - $ref: '#/components/schemas/Client'
        - type: string

    ClientOrIdentityWithDiscriminator:
      oneOf:
        - $ref: '#/components/schemas/Client'
        - $ref: '#/components/schemas/Identity'
      discriminator:
        propertyName: type
        mapping:
          client: '#/components/schemas/Client'
          identity: '#/components/schemas/Identity'

    # Test case for discriminator with optional property (pointer type)
    # The discriminator property has a default value, making it optional
    Dog:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        type:
          type: string
          enum:
            - dog
          default: dog

    Cat:
      type: object
      required:
        - name
        - type
      properties:
        name:
          type: string
        type:
          type: string
          enum:
            - cat

    # Union with discriminator where one member has optional discriminator property
    Pet:
      oneOf:
        - $ref: '#/components/schemas/Dog'
        - $ref: '#/components/schemas/Cat'
      discriminator:
        propertyName: type
        mapping:
          dog: '#/components/schemas/Dog'
          cat: '#/components/schemas/Cat'
