openapi: 3.0.0
info:
  title: Request Options Collision Test
  version: 1.0.0

paths:
  /test:
    get:
      operationId: getTest
      parameters:
        - name: query_param
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestResponse'

components:
  schemas:
    TestResponse:
      type: object
      properties:
        message:
          type: string
        # Reference the colliding schema to ensure it gets generated
        options:
          $ref: '#/components/schemas/GetTestRequestOptions'

    # This schema name collides with the generated GetTestRequestOptions type
    GetTestRequestOptions:
      type: object
      properties:
        collision:
          type: string
