// Code generated by oapi-codegen. DO NOT EDIT.

package collision

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

// Client is the client for the API implementing the Client interface.
type Client struct {
	apiClient runtime.APIClient
}

// NewClient creates a new instance of the Client client.
func NewClient(apiClient runtime.APIClient) *Client {
	return &Client{apiClient: apiClient}
}

// NewDefaultClient creates a new instance of the Client client with default api client.
func NewDefaultClient(baseURL string, opts ...runtime.APIClientOption) (*Client, error) {
	apiClient, err := runtime.NewAPIClient(baseURL, opts...)
	if err != nil {
		return nil, fmt.Errorf("error creating API client: %w", err)
	}
	return &Client{apiClient: apiClient}, nil
}

// ClientInterface is the interface for the API client.
type ClientInterface interface {
	GetTest1(ctx context.Context, options *GetTest1RequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetTestResponse, error)
}

func (c *Client) GetTest1(ctx context.Context, options *GetTest1RequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetTestResponse, error) {
	var err error

	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/test",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*GetTestResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			return nil, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(GetTestResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/test")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

var _ ClientInterface = (*Client)(nil)

var clientOptionsValidate = validator.New(validator.WithRequiredStructEnabled())

// GetTest1RequestOptions is the options needed to make a request to GetTest1.
type GetTest1RequestOptions struct {
	Query *GetTestQuery
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *GetTest1RequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if err := clientOptionsValidate.Struct(o.Query); err != nil {
		errors = append(errors, runtime.NewValidationErrorsFromErrors("Query", []error{err})...)
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *GetTest1RequestOptions) GetPathParams() (map[string]any, error) {
	return nil, nil
}

// GetQuery returns the query params as a map.
func (o *GetTest1RequestOptions) GetQuery() (map[string]any, error) {
	return asMap[any](o.Query)
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *GetTest1RequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *GetTest1RequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

func asMap[V any](v any) (map[string]V, error) {
	if v == nil {
		return nil, nil
	}
	res, err := json.Marshal(v)
	if err != nil {
		return nil, err
	}

	var m map[string]V
	err = json.Unmarshal(res, &m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

var queryTypesValidate *validator.Validate

func init() {
	queryTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(queryTypesValidate)
}

type GetTestQuery struct {
	QueryParam *string `json:"query_param,omitempty"`
}

func (g GetTestQuery) Validate() error {
	return queryTypesValidate.Struct(g)
}

type GetTestResponse struct {
	Message *string                `json:"message,omitempty"`
	Options *GetTestRequestOptions `json:"options,omitempty"`
}

var schemaTypesValidate *validator.Validate

func init() {
	schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(schemaTypesValidate)
}

type TestResponse struct {
	Message *string                `json:"message,omitempty"`
	Options *GetTestRequestOptions `json:"options,omitempty"`
}

func (t TestResponse) Validate() error {
	if t.Options != nil {
		if v, ok := any(t.Options).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("Options", err)
			}
		}
	}
	return nil
}

type GetTestRequestOptions struct {
	Collision *string `json:"collision,omitempty"`
}

func (g GetTestRequestOptions) Validate() error {
	return schemaTypesValidate.Struct(g)
}
