openapi: "3.0.0"
info:
  version: 1.0.0
  title: Generate models
paths:
  /client:
    get:
      tags:
        - client
        - person
      operationId: getClient
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Person"
  /clients:
    get:
      tags:
        - client
        - person
      operationId: getClients
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Person"

  /client/{id}/purchases:
    get:
      tags:
        - client
        - purchase
      operationId: getPurchases
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Purchase"
  /client/{id}/purchases/{purchaseId}:
    get:
      tags:
        - client
        - purchase
      operationId: getPurchase
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Purchase"
components:
  schemas:
    Person:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        age:
          type: integer
    Purchase:
      type: object
      required:
        - id
      properties:
        id:
          type: integer

