// Code generated by oapi-codegen. DO NOT EDIT.

package filteringbytag

import (
	"github.com/go-playground/validator/v10"
)

type GetPurchasesResponse []Purchase

type GetPurchaseResponse struct {
	ID int `json:"id" validate:"required"`
}

var schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type Purchase struct {
	ID int `json:"id" validate:"required"`
}

func (p Purchase) Validate() error {
	return schemaTypesValidate.Struct(p)
}
