// Code generated by oapi-codegen. DO NOT EDIT.

package filteringbyproperty

import (
	"github.com/go-playground/validator/v10"
)

var bodyTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type UpdateClientBody = Person

type GetClientResponse struct {
	Name       string `json:"name" validate:"required"`
	Age        *int   `json:"age,omitempty"`
	Employment *Job   `json:"employment,omitempty"`
}

type UpdateClientErrorResponse struct {
	Code    string  `json:"code" validate:"required"`
	Details *string `json:"details,omitempty"`
	Data    *struct {
		// Code Error code
		Code *string `json:"code,omitempty"`

		// Message Error message
		Message *string `json:"message,omitempty"`
	} `json:"data,omitempty"`
}

func (r UpdateClientErrorResponse) Error() string {
	res0 := r.Code
	return res0
}

var schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type Person struct {
	Name       string `json:"name" validate:"required"`
	Age        *int   `json:"age,omitempty"`
	Employment *Job   `json:"employment,omitempty"`
}

func (p Person) Validate() error {
	return schemaTypesValidate.Struct(p)
}

type Job struct {
	Title string `json:"title" validate:"required"`
}

func (j Job) Validate() error {
	return schemaTypesValidate.Struct(j)
}
