// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

// Client is the client for the API implementing the Client interface.
type Client struct {
	apiClient runtime.APIClient
}

// NewClient creates a new instance of the Client client.
func NewClient(apiClient runtime.APIClient) *Client {
	return &Client{apiClient: apiClient}
}

// NewDefaultClient creates a new instance of the Client client with default api client.
func NewDefaultClient(baseURL string, opts ...runtime.APIClientOption) (*Client, error) {
	apiClient, err := runtime.NewAPIClient(baseURL, opts...)
	if err != nil {
		return nil, fmt.Errorf("error creating API client: %w", err)
	}
	return &Client{apiClient: apiClient}, nil
}

// ClientInterface is the interface for the API client.
type ClientInterface interface {
	GetWidget(ctx context.Context, options *GetWidgetRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetWidgetResponse, error)

	GetOrder(ctx context.Context, options *GetOrderRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetOrderResponse, error)

	GetCart(ctx context.Context, options *GetCartRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetCartResponse, error)
}

func (c *Client) GetWidget(ctx context.Context, options *GetWidgetRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetWidgetResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/widgets/{id}",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*GetWidgetResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(GetWidgetErrorResponse)
			// Handle empty error response body gracefully - skip unmarshal if no content
			if len(bodyBytes) > 0 {
				if err = json.Unmarshal(bodyBytes, target); err != nil {
					return nil, &runtime.ResponseDecodeError{
						StatusCode:    resp.StatusCode,
						ContentType:   resp.Headers.Get("Content-Type"),
						ContentLength: len(bodyBytes),
						TargetType:    "GetWidgetErrorResponse",
						Body:          bodyBytes,
						Err:           err,
					}
				}
			}
			// Return error with (possibly empty) target
			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(GetWidgetResponse)
		// Handle empty response body gracefully
		if len(bodyBytes) == 0 {
			return target, nil
		}
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			return nil, &runtime.ResponseDecodeError{
				StatusCode:    resp.StatusCode,
				ContentType:   resp.Headers.Get("Content-Type"),
				ContentLength: len(bodyBytes),
				TargetType:    "GetWidgetResponse",
				Body:          bodyBytes,
				Err:           err,
			}
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/widgets/{id}")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

func (c *Client) GetOrder(ctx context.Context, options *GetOrderRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetOrderResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/orders/{id}",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*GetOrderResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(GetOrderErrorResponse)
			// Handle empty error response body gracefully - skip unmarshal if no content
			if len(bodyBytes) > 0 {
				if err = json.Unmarshal(bodyBytes, target); err != nil {
					return nil, &runtime.ResponseDecodeError{
						StatusCode:    resp.StatusCode,
						ContentType:   resp.Headers.Get("Content-Type"),
						ContentLength: len(bodyBytes),
						TargetType:    "GetOrderErrorResponse",
						Body:          bodyBytes,
						Err:           err,
					}
				}
			}
			// Return error with (possibly empty) target
			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(GetOrderResponse)
		// Handle empty response body gracefully
		if len(bodyBytes) == 0 {
			return target, nil
		}
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			return nil, &runtime.ResponseDecodeError{
				StatusCode:    resp.StatusCode,
				ContentType:   resp.Headers.Get("Content-Type"),
				ContentLength: len(bodyBytes),
				TargetType:    "GetOrderResponse",
				Body:          bodyBytes,
				Err:           err,
			}
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/orders/{id}")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

func (c *Client) GetCart(ctx context.Context, options *GetCartRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetCartResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/carts/{id}",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*GetCartResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(GetCartErrorResponse)
			// Handle empty error response body gracefully - skip unmarshal if no content
			if len(bodyBytes) > 0 {
				if err = json.Unmarshal(bodyBytes, target); err != nil {
					return nil, &runtime.ResponseDecodeError{
						StatusCode:    resp.StatusCode,
						ContentType:   resp.Headers.Get("Content-Type"),
						ContentLength: len(bodyBytes),
						TargetType:    "GetCartErrorResponse",
						Body:          bodyBytes,
						Err:           err,
					}
				}
			}
			// Return error with (possibly empty) target
			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(GetCartResponse)
		// Handle empty response body gracefully
		if len(bodyBytes) == 0 {
			return target, nil
		}
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			return nil, &runtime.ResponseDecodeError{
				StatusCode:    resp.StatusCode,
				ContentType:   resp.Headers.Get("Content-Type"),
				ContentLength: len(bodyBytes),
				TargetType:    "GetCartResponse",
				Body:          bodyBytes,
				Err:           err,
			}
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/carts/{id}")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

var _ ClientInterface = (*Client)(nil)

// GetWidgetRequestOptions is the options needed to make a request to GetWidget.
type GetWidgetRequestOptions struct {
	PathParams *GetWidgetPath
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *GetWidgetRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *GetWidgetRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *GetWidgetRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *GetWidgetRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *GetWidgetRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// GetOrderRequestOptions is the options needed to make a request to GetOrder.
type GetOrderRequestOptions struct {
	PathParams *GetOrderPath
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *GetOrderRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *GetOrderRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *GetOrderRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *GetOrderRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *GetOrderRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// GetCartRequestOptions is the options needed to make a request to GetCart.
type GetCartRequestOptions struct {
	PathParams *GetCartPath
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *GetCartRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *GetCartRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *GetCartRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *GetCartRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *GetCartRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

type GetWidgetPath struct {
	ID string `json:"id" validate:"required"`
}

func (g GetWidgetPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type GetOrderPath struct {
	ID string `json:"id" validate:"required"`
}

func (g GetOrderPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type GetCartPath struct {
	ID string `json:"id" validate:"required"`
}

func (g GetCartPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type GetWidgetResponse = Item

type GetWidgetErrorResponse = WidgetError

type GetOrderResponse = Item

type GetOrderErrorResponse = OrderError

type GetCartResponse = Item

type GetCartErrorResponse = CartError

type Item struct {
	ID *string `json:"id,omitempty"`
}

type NotFound struct {
	UnderscoreTag string `json:"_tag" validate:"required"`
	Message       string `json:"message" validate:"required"`
}

func (n NotFound) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(n))
}

type Conflict struct {
	UnderscoreTag string `json:"_tag" validate:"required"`
	Message       string `json:"message" validate:"required"`
}

func (c Conflict) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(c))
}

type Gone struct {
	UnderscoreTag string  `json:"_tag" validate:"required"`
	Since         *string `json:"since,omitempty"`
}

func (g Gone) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type WidgetError struct {
	WidgetError_AnyOf *WidgetError_AnyOf `json:"-"`
}

func (w WidgetError) Validate() error {
	var errors runtime.ValidationErrors
	if w.WidgetError_AnyOf != nil {
		if v, ok := any(w.WidgetError_AnyOf).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("WidgetError_AnyOf", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (s WidgetError) Error() string {
	res0 := s.WidgetError_AnyOf
	if res0 == nil {
		return "unknown error"
	}
	res1 := *res0
	switch res2 := res1.Value().(type) {
	case NotFound:
		res3 := res2.Message
		return res3
	}
	return "unknown error"
}

func (w WidgetError) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(w.WidgetError_AnyOf)
		if err != nil {
			return nil, fmt.Errorf("WidgetError_AnyOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (w *WidgetError) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if w.WidgetError_AnyOf == nil {
		w.WidgetError_AnyOf = &WidgetError_AnyOf{}
	}

	if err := runtime.UnmarshalJSON(data, w.WidgetError_AnyOf); err != nil {
		return fmt.Errorf("WidgetError_AnyOf unmarshal: %w", err)
	}

	return nil
}

type OrderError struct {
	OrderError_OneOf *OrderError_OneOf `json:"-"`
}

func (o OrderError) Validate() error {
	var errors runtime.ValidationErrors
	if o.OrderError_OneOf != nil {
		if v, ok := any(o.OrderError_OneOf).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("OrderError_OneOf", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (s OrderError) Error() string {
	res0 := s.OrderError_OneOf
	if res0 == nil {
		return "unknown error"
	}
	res1 := *res0
	res2, _ := res1.ValueByDiscriminator()
	switch res3 := res2.(type) {
	case NotFound:
		res4 := res3.Message
		return res4
	case Conflict:
		res5 := res3.Message
		return res5
	}
	return "unknown error"
}

func (o OrderError) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(o.OrderError_OneOf)
		if err != nil {
			return nil, fmt.Errorf("OrderError_OneOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (o *OrderError) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if o.OrderError_OneOf == nil {
		o.OrderError_OneOf = &OrderError_OneOf{}
	}

	if err := runtime.UnmarshalJSON(data, o.OrderError_OneOf); err != nil {
		return fmt.Errorf("OrderError_OneOf unmarshal: %w", err)
	}

	return nil
}

type CartError struct {
	ErrorData *CartError_Error `json:"error,omitempty"`
}

func (c CartError) Validate() error {
	var errors runtime.ValidationErrors
	if c.ErrorData != nil {
		if v, ok := any(c.ErrorData).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("ErrorData", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (s CartError) Error() string {
	res0 := s.ErrorData
	if res0 == nil {
		return "unknown error"
	}
	res1 := *res0
	res2 := res1.CartError_Error_OneOf
	if res2 == nil {
		return "unknown error"
	}
	res3 := *res2
	switch res4 := res3.Value().(type) {
	case NotFound:
		res5 := res4.Message
		return res5
	}
	return "unknown error"
}

type CartError_Error struct {
	CartError_Error_OneOf *CartError_Error_OneOf `json:"-"`
}

func (c CartError_Error) Validate() error {
	var errors runtime.ValidationErrors
	if c.CartError_Error_OneOf != nil {
		if v, ok := any(c.CartError_Error_OneOf).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("CartError_Error_OneOf", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (c CartError_Error) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(c.CartError_Error_OneOf)
		if err != nil {
			return nil, fmt.Errorf("CartError_Error_OneOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (c *CartError_Error) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if c.CartError_Error_OneOf == nil {
		c.CartError_Error_OneOf = &CartError_Error_OneOf{}
	}

	if err := runtime.UnmarshalJSON(data, c.CartError_Error_OneOf); err != nil {
		return fmt.Errorf("CartError_Error_OneOf unmarshal: %w", err)
	}

	return nil
}

type WidgetError_AnyOf struct {
	runtime.Either[NotFound, string]
}

func (w *WidgetError_AnyOf) Validate() error {
	if w.IsA() {
		if v, ok := any(w.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if w.IsB() {
		if v, ok := any(w.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}

type OrderError_OneOf struct {
	union json.RawMessage
}

func (o *OrderError_OneOf) Validate() error {
	// NOTE: Validation is not supported for unions with more than 2 elements.
	// Validating would require unmarshaling against each possible type, which is inefficient.
	// Use AsValidated<Type>() methods to validate after retrieving the specific type.
	return nil
}

// Raw returns the union data inside the OrderError_OneOf as bytes
func (o *OrderError_OneOf) Raw() json.RawMessage {
	return o.union
}

// AsNotFound returns the union data inside the OrderError_OneOf as a NotFound
func (o *OrderError_OneOf) AsNotFound() (NotFound, error) {
	return runtime.UnmarshalAs[NotFound](o.union)
}

// AsValidatedNotFound returns the union data inside the OrderError_OneOf as a validated NotFound
func (o *OrderError_OneOf) AsValidatedNotFound() (NotFound, error) {
	val, err := o.AsNotFound()
	if err != nil {
		var zero NotFound
		return zero, err
	}
	if err := o.validateNotFound(val); err != nil {
		var zero NotFound
		return zero, err
	}
	return val, nil
}

// FromNotFound overwrites any union data inside the OrderError_OneOf as the provided NotFound
func (o *OrderError_OneOf) FromNotFound(val NotFound) error {
	// Validate before storing
	if err := o.validateNotFound(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	o.union = bts
	return err
}

// AsConflict returns the union data inside the OrderError_OneOf as a Conflict
func (o *OrderError_OneOf) AsConflict() (Conflict, error) {
	return runtime.UnmarshalAs[Conflict](o.union)
}

// AsValidatedConflict returns the union data inside the OrderError_OneOf as a validated Conflict
func (o *OrderError_OneOf) AsValidatedConflict() (Conflict, error) {
	val, err := o.AsConflict()
	if err != nil {
		var zero Conflict
		return zero, err
	}
	if err := o.validateConflict(val); err != nil {
		var zero Conflict
		return zero, err
	}
	return val, nil
}

// FromConflict overwrites any union data inside the OrderError_OneOf as the provided Conflict
func (o *OrderError_OneOf) FromConflict(val Conflict) error {
	// Validate before storing
	if err := o.validateConflict(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	o.union = bts
	return err
}

// AsGone returns the union data inside the OrderError_OneOf as a Gone
func (o *OrderError_OneOf) AsGone() (Gone, error) {
	return runtime.UnmarshalAs[Gone](o.union)
}

// AsValidatedGone returns the union data inside the OrderError_OneOf as a validated Gone
func (o *OrderError_OneOf) AsValidatedGone() (Gone, error) {
	val, err := o.AsGone()
	if err != nil {
		var zero Gone
		return zero, err
	}
	if err := o.validateGone(val); err != nil {
		var zero Gone
		return zero, err
	}
	return val, nil
}

// FromGone overwrites any union data inside the OrderError_OneOf as the provided Gone
func (o *OrderError_OneOf) FromGone(val Gone) error {
	// Validate before storing
	if err := o.validateGone(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	o.union = bts
	return err
}

// validateNotFound validates a NotFound value
func (o *OrderError_OneOf) validateNotFound(val NotFound) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateConflict validates a Conflict value
func (o *OrderError_OneOf) validateConflict(val Conflict) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateGone validates a Gone value
func (o *OrderError_OneOf) validateGone(val Gone) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

func (o OrderError_OneOf) discriminator(data []byte) (string, error) {
	var discriminator struct {
		Value string `json:"_tag"`
	}
	if err := json.Unmarshal(data, &discriminator); err != nil {
		return "", err
	}
	return discriminator.Value, nil
}

func (o OrderError_OneOf) ValueByDiscriminator() (any, error) {
	discriminator, err := o.discriminator(o.union)
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "Conflict":
		return o.AsConflict()
	case "Gone":
		return o.AsGone()
	case "NotFound":
		return o.AsNotFound()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (o OrderError_OneOf) MarshalJSON() ([]byte, error) {
	bts, err := o.union.MarshalJSON()

	return bts, err
}

func (o *OrderError_OneOf) UnmarshalJSON(bts []byte) error {
	err := o.union.UnmarshalJSON(bts)

	return err
}

type CartError_Error_OneOf struct {
	runtime.Either[NotFound, Gone]
}

func (c *CartError_Error_OneOf) Validate() error {
	if c.IsA() {
		if v, ok := any(c.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if c.IsB() {
		if v, ok := any(c.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
