openapi: "3.0.0"
info:
  version: 1.0.0
  title: Collapsed anyOf, oneOf example
  description: An example of `anyOf` and `oneOf` used together where allOf can be collapsed
components:
  schemas:
    Order:
      type: object
      properties:
        client:
          allOf:
            - $ref: '#/components/schemas/Client'
            - properties:
                id:
                  type: integer
                identity:
                  anyOf:
                    - $ref: '#/components/schemas/Identity'
                address:
                  oneOf:
                    - $ref: '#/components/schemas/Address'

    Client:
      type: object
      required:
        - name
      properties:
        name:
          type: string

    Identity:
      type: object
      required:
        - issuer
      properties:
        issuer:
          type: string

    Address:
      type: object
      properties:
        city:
          type: string
        country:
          type: string
