// Code generated by oapi-codegen. DO NOT EDIT.

package example1

import (
	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

type MSN = string

type GetClientHeaders struct {
	MerchantSerialNumber MSN `json:"Merchant-Serial-Number" validate:"required,max=7,min=4"`
}

func (g GetClientHeaders) Validate() error {
	var errors runtime.ValidationErrors
	if err := typesValidator.Var(g.MerchantSerialNumber, "required,max=7,min=4"); err != nil {
		errors = errors.Append("MerchantSerialNumber", err)
	}
	if err := runtime.ValidatePattern(g.MerchantSerialNumber, `^[0-9]{4,7}$`); err != nil {
		errors = errors.Append("MerchantSerialNumber", err)
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type UpdateClientHeaders struct {
	MerchantSerialNumber MSN `json:"Merchant-Serial-Number" validate:"required,max=7,min=4"`
}

func (u UpdateClientHeaders) Validate() error {
	var errors runtime.ValidationErrors
	if err := typesValidator.Var(u.MerchantSerialNumber, "required,max=7,min=4"); err != nil {
		errors = errors.Append("MerchantSerialNumber", err)
	}
	if err := runtime.ValidatePattern(u.MerchantSerialNumber, `^[0-9]{4,7}$`); err != nil {
		errors = errors.Append("MerchantSerialNumber", err)
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}
